### PR TITLE
remove invalid device file

### PR DESCRIPTION
**Pull request by tangming1996**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by tangming1996** [comment]
@Shelley-BaoYue please help review this pr

**Comment by wbc6080** [comment]
It seems that both v1alpha1 and v1alpha2 version device definitions are outdated. How about deleting the v1alpha1 version too?
@cl2017 @WillardHu 
c3

**Comment by Shelley-BaoYue** [comment]
> It seems that both v1alpha1 and v1alpha2 version device definitions are outdated. How about deleting the v1alpha1 version too? @cl2017 @WillardHu c3

+1

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
