### PR TITLE
Docs: fix typos

### PR DESCRIPTION
**Pull request by joedborg**
**What type of PR is this?**

/kind cleanup /kind documentation

**What this PR does / why we need it**:
Fixing doc typo.

### CODE REVIEW

**Comment by joedborg** [comment]
https://github.com/kubeedge/kubeedge/pull/2185
https://github.com/kubeedge/kubeedge/pull/2186

**Comment by daixiang0** [comment]
@joedborg please rename tiltle, like: `Docs: fix typos`

**Comment by joedborg** [comment]
> @joedborg please rename tiltle, like: `Docs: fix typos`

done

**Pull request merged**
