### PR TITLE
Encapsulate CA and Certificate operations

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Abstract some methods for certificates, and implement x509

**Which issue(s) this PR fixes**:

A part of issue https://github.com/kubeedge/kubeedge/issues/5498

**Special notes for your reviewer**:

The PR https://github.com/kubeedge/kubeedge/pull/5502 needs to be merged first.

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by WillardHu** [comment]
This change passed some tests in my k8s cluster
- Cloudcore generates a self-signed ca certificate initially ✅
- An new joined edge node(Edgecore) can connect to Cloudcore and obtains a service certificate ✅

PTAL  @fisherxu  @Shelley-BaoYue

**Review by fisherxu — COMMENTED** [review]
Overall looks good, and we need to ensure the compatibility with the older version :) @WillardHu

**Comment by WillardHu** [comment]
> Overall looks good, and we need to ensure the compatibility with the older version :) @WillardHu

Yes, codes has been abstracted, but the external functionality has not changed.

**Comment by fisherxu** [comment]
PR need rebased :) @WillardHu

**Comment by WillardHu** [comment]
> PR need rebased :) @WillardHu

Done.

**Review by fisherxu — COMMENTED** [review]
/approve
/assign @Shelley-BaoYue

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Pull request merged**
