### PR TITLE
update beehive vendor

### PR DESCRIPTION
**Pull request by kadisi**
Signed-off-by: zhangjie <iamkadisi@163.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

https://github.com/kubeedge/beehive/pull/6

**Special notes for your reviewer**:
@sids-b

### CODE REVIEW

**Comment by qizha** [comment]
I also updated beehive codes include logger and config, can you please pick up the latest beehive code in this PR？

**Comment by kadisi** [comment]
@qizha ok

**Comment by kadisi** [comment]
@qizha about  https://github.com/kubeedge/beehive/pull/12  ,  Do you need to change `Gopkg.toml` file.  i found you change revision of `github.com/go-chassis/go-archaius`.

**Comment by qizha** [comment]
alright, I will fix that but that upgrade need some more code changes in kubeedge/kubeedge, let's merge this one first and I will use another one to trace my changes. Thanks

**Comment by kadisi** [comment]
@qizha ok

**Comment by rohitsardesai83** [comment]
@kadisi , @qizha , does this need to go in 1.0 or it can wait ?

**Comment by kadisi** [comment]
> alright, I will fix that but that upgrade need some more code changes in kubeedge/kubeedge,let's merge this one first and I will use another one to trace my changes. Thanks

@rohitsardesai83 if we use the latest version of beehive which changed by @qizha , we need change lot of thing about kubeedge, and need more test.   

if  i suggest merge this pr first, and waiting for @qizha new pr.

@qizha what do you think？

**Comment by rohitsardesai83** [comment]
@kadisi , we have conflicts now. please check.

**Comment by kadisi** [comment]
@rohitsardesai83 kubeedge has the lastst beehive vendor, so i suggest close this pr.

**Comment by sids-b** [comment]
Thanks @kadisi for adding the log functions

**Pull request closed without merging**
