### PR TITLE
refactor GenerateServiceFile

### PR DESCRIPTION
**Pull request by gy95**
**What type of PR is this?**

**What this PR does / why we need it**:
refactor function `GenerateServiceFile ` to make it more clear:  we need two parameters: service name and execStart cmd, so don't need to construct execStart 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wackxu** [comment]
```Fix log path to /var/log/kubeedge/edgecore.log```

I do not see any changes about this

**Comment by gy95** [comment]
don't change the edgecore log path, it seems that edgecore log path has always been /etc/kubeedge/kubeedge/edge/edgecore.log
https://github.com/kubeedge/kubeedge/blob/a6a243ca1f0d305f2c9d03400fae2f7e1629825b/keadm/cmd/keadm/app/cmd/util/common.go#L463-L469

**Comment by wackxu** [comment]
> don't change the edgecore log path, it seems that edgecore log path has always been /etc/kubeedge/kubeedge/edge/edgecore.log
> 
> https://github.com/kubeedge/kubeedge/blob/a6a243ca1f0d305f2c9d03400fae2f7e1629825b/keadm/cmd/keadm/app/cmd/util/common.go#L463-L469

ok， please update the the pr title to reflect what has changed

**Comment by wackxu** [comment]
lgtm

**Comment by gy95** [comment]
cc @fisherxu

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
