### PR TITLE
Service-bus to support REST

### LINKED ISSUE #265: Create data routing mechanism between edge and cloud
**What would you like to be added**:
We need to add the data routing mechanism to control the data flow between edge and cloud. The first step is to support mqtt and rest.

**Why is this needed**:
So that the user can reuse the data channel built by the KubeEdge to do data communication between applications.

### PR DESCRIPTION
**Pull request by sids-b**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This is the first step to support REST before supporting data routing mechanism to control the data flow between edge and cloud.
 
**Which issue(s) this PR fixes**:
Partially implements features in #265

### CODE REVIEW

**Comment by m1093782566** [comment]
@sids-b 

I feel ill-equipment to review this PR. Would you please provide an detailed design?

**Comment by sids-b** [comment]
@m1093782566 , EventBus is used to communicate with application running on edge via MQTT. Similarly service-bus is used to communicate with application running on edge via HTTP. The design is exactly similar to that of EventBus.
1) Cloud sends beehive message to Edge via CloudHub.
2) EdgeHub receives the messages and gives it to serviceBus.
3) Service bus just makes the http call and sends the response to cloud via edgeHub.

**Comment by sids-b** [comment]
Opps, looks like i need to rebase as beehive is moved out.

**Comment by Baoqiang-Zhang** [comment]
[introduction](https://github.com/kubeedge/kubeedge#introduction) and [architecture](https://github.com/kubeedge/kubeedge#architecture) should add servicebus

**Comment by m1093782566** [comment]
> introduction and architecture should add servicebus

+1

**Comment by sids-b** [comment]
> [introduction](https://github.com/kubeedge/kubeedge#introduction) and [architecture](https://github.com/kubeedge/kubeedge#architecture) should add servicebus

Sure @Baoqiang-Zhang . @m1093782566 can you share the source file for the architecture design ??

**Comment by sids-b** [comment]
@m1093782566 @Baoqiang-Zhang I have modified the architecture picture and added description in README

**Pull request merged**
