### PR TITLE
docs:[Fix:#608]: Open ports to cloud component for edge nodes in the …

### LINKED ISSUE #608: KubeEdge Installer (keadm) fails
**What happened**:
Tried to install kubeedge with keadm but after connecting my my edge node(ubuntu) to the server(ubuntu) in google cloud it fails and kubectl get nodes shows that my server and edge node are in state NotReady.

**What you expected to happen**:
That my edge node would connect to the master and with kubectl I should show state Ready for both.
**How to reproduce it (as minimally and precisely as possible)**:
Using the instructions in the part "Simple steps to bring up KubeEdge setup and deploy a pod" on this page https://github.com/kubeedge/kubeedge/tree/master/keadm.
For the installation of kubeedge on server and edge node I used the default version for docker and kubernetes. So I run the commands without specifying a version.
**Anything else we need to know?**:
Logs of my edgecontroller on the server:

```

> 2019-05-29 14:41:20.730 +00:00 INFO controller/downstream.go:132 there are 0 nodes need to sync secret, operation: ADDED
> 2019-05-29 14:41:20.811 +00:00 WARN controller/downstream.go:47 built message resource failed with error: required parameter are not set (node id, namespace or resource type)
> 2019-05-29 14:41:20.824 +00:00 INFO controller/downstream.go:66 send message successfully, operation: update, resource: node/instance-1/kube-system/pod/kube-proxy-dfjbw
> 2019-05-29 14:41:20.824 +00:00 ERROR channelq/channelq.go:103 rChannel for edge node instance-1 is removed
> 2019-05-29 14:41:20.824 +00:00 INFO channelq/channelq.go:89 fail to get dispatch channel for instance-1
> E0529 14:41:20.853354   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:20.854084   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> 2019-05-29 14:41:21.271 +00:00 WARN controller/downstream.go:47 built message resource failed with error: required parameter are not set (node id, namespace or resource type)
> 2019-05-29 14:41:21.294 +00:00 WARN controller/downstream.go:47 built message resource failed with error: required parameter are not set (node id, namespace or resource type)
> E0529 14:41:21.854734   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:21.855290   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:22.856047   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:22.856854   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:23.857307   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:23.857887   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:24.858800   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:24.859141   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:25.860053   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:25.860624   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:26.861384   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:26.862036   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:27.862575   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:27.863185   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:28.863942   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:28.864640   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:29.865116   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:29.865692   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:30.866359   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:30.867007   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:31.867638   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:31.868114   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:32.868995   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:32.869485   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:33.870252   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:33.871069   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:34.871558   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:34.872553   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:35.872909   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:35.873427   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:36.874533   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:36.874922   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:37.875930   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:37.876634   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:38.877244   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:38.877964   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:39.878537   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:39.879401   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:40.879983   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:40.880915   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:41.881677   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:41.882208   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:42.883001   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:42.884005   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:43.884226   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:43.884722   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:44.885622   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:44.886084   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:45.886996   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:45.887689   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:46.888319   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:46.889030   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:47.889785   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:47.890705   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:48.891188   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:48.892048   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> 2019-05-29 14:41:49.096 +00:00 INFO controller/downstream.go:66 send message successfully, operation: insert, resource: node/instance-1/kube-system/pod/kube-scheduler-instance-1
> 2019-05-29 14:41:49.096 +00:00 ERROR channelq/channelq.go:103 rChannel for edge node instance-1 is removed
> 2019-05-29 14:41:49.096 +00:00 INFO channelq/channelq.go:89 fail to get dispatch channel for instance-1
> E0529 14:41:49.893042   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/devicemodel.go:39: Failed to list *v1alpha1.DeviceModel: the server could not find the requested resource (get devicemodels.devices.kubeedge.io)
> E0529 14:41:49.893116   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:50.900627   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:51.901851   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:52.903244   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:53.904651   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:54.906037   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:55.907542   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:56.908912   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> E0529 14:41:57.910209   14020 reflector.go:205] github.com/kubeedge/kubeedge/cloud/pkg/devicecontroller/manager/device.go:39: Failed to list *v1alpha1.Device: the server could not find the requested resource (get devices.devices.kubeedge.io)
> 2019-05-29 14:42:06.090 +00:00 INFO controller/downstream.go:66 send message successfully, operation: insert, resource: node/instance-1/kube-system/pod/etcd-instance-1
> 2019-05-29 14:42:06.090 +00:00 ERROR channelq/channelq.go:103 rChannel for edge node instance-1 is removed
> 2019-05-29 14:42:06.090 +00:00 INFO channelq/channelq.go:89 fail to get dispatch channel for instance-1
> 2019-05-29 14:44:17.442 +00:00 WARN controller/downstream.go:47 built message resource failed with error: required parameter are not set (node id, namespace or resource type)

```
**Environment**:
- KubeEdge version: Default version 
- keadm version: Cloned the newest master branch and build it from source

- OS (e.g. from /etc/os-release): Ubuntu 19.04
- Kernel (e.g. `uname -a`): Linux instance-1 5.0.0-1006-gcp #6-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by vizero1**
…installer(keadm) readme

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Extend the readme of kubeedge installer so that the right ports are opened of the cloud component for the edge nodes.
**Which issue(s) this PR fixes**:

Fixes #608 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by m1093782566** [comment]
@vizero1 Please author your commits using your git id and email address instead of your user name.

**Comment by vizero1** [comment]
> @vizero1 Please submit your commits using your github id and email address instead of your computer user name so that github can identify you :)

@m1093782566  Yes, thanks for the hint.

**Pull request merged**
