### PR TITLE
Update default version in manifest to v1.19.0 

### LINKED ISSUE #5927: v1.19.0 Release Onboarding
# New Release Onboarding

This is an issue template aims to provide a comprehensive checklist template for releases onboarding. It includes a detailed list of preparation tasks to complete before the release and additional checkpoints to ensure everything runs smoothly after the release.

## Requirements for release onboarding

- [x] All CI tests pass.
- [x] Update KubeEdge version in [manifests](https://github.com/kubeedge/kubeedge/tree/master/manifests) -- #5929 

## After release onboarding

- [x] Draft staging repository release. (https://github.com/kubeedge/beehive, https://github.com/kubeedge/api, https://github.com/kubeedge/mapper-framework)
- [x] Update [Kubernetes compatibility](https://github.com/kubeedge/kubeedge?tab=readme-ov-file#kubernetes-compatibility).
- [x] Release blog.
- [x] Update KubeEdge [latest version](https://github.com/kubeedge/website/blob/master/functions/latestversion.js).
- [x] Update KubeEdge documentation version.
- [x] Update Kubernetes version in github action CI.

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

As v1.19.0 to be released, update the corresponding version in manifests.  

**Which issue(s) this PR fixes**:

Fixes #5927 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by wbc6080 — COMMENTED** [review]
lgtm

**Review by fisherxu — COMMENTED** [review]
/lgtm
/assign @WillardHu

**Comment by WillardHu** [comment]
Please update the appVersion in manifests/profiles/version.yaml

**Comment by Shelley-BaoYue** [comment]
> Please update the appVersion in manifests/profiles/version.yaml

Fixed. Thx for your reminding,

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
