### PR TITLE
Update Beego import path to use 'beego/beego' repository

### PR DESCRIPTION
**Pull request by MeenuyD**
The Beego framework has been migrated to the official repository at github.com/beego/beego from its previous location at github.com/astaxie/beego. This will update the repository URL to use the new location, ensuring that we are using the latest version of Beego.
#5024

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
@MeenuyD You need to run `make veify` to update the vendor, thanks, and now we still use the `github.com/astaxie/beego` under vendor dir, it should be update to beego/beego

**Comment by MeenuyD** [comment]
Hello @fisherxu after running the make verify command it gave me this can you tell me what should i do 

 kubeedge/hack/../hack/lib/golang.sh: line 26: go: command not found
go detail version: 
/kubeedge/hack/../hack/lib/golang.sh: line 28: go: command not found
make: *** [verify-golang] Error 127

**Comment by fisherxu** [comment]
> Hello @fisherxu after running the make verify command it gave me this can you tell me what should i do
> 
> kubeedge/hack/../hack/lib/golang.sh: line 26: go: command not found go detail version: /kubeedge/hack/../hack/lib/golang.sh: line 28: go: command not found make: *** [verify-golang] Error 127

Please install go1.19 in your host

**Review by fisherxu — COMMENTED** [review]
@MeenuyD  Could you please update this PR? Thanks

**Comment by MeenuyD** [comment]
> > Hello @fisherxu after running the make verify command it gave me this can you tell me what should i do
> > kubeedge/hack/../hack/lib/golang.sh: line 26: go: command not found go detail version: /kubeedge/hack/../hack/lib/golang.sh: line 28: go: command not found make: *** [verify-golang] Error 127
> 
> Please install go1.19 in your host

I have installed the go1.19 but it is giving me same error

**Comment by MeenuyD** [comment]
> @MeenuyD You need to run `make veify` to update the vendor, thanks, and now we still use the `github.com/astaxie/beego` under vendor dir, it should be update to beego/beego

I am confused if it is `make veify` or `make verify`.

**Comment by Shelley-BaoYue** [comment]
> > @MeenuyD You need to run `make veify` to update the vendor, thanks, and now we still use the `github.com/astaxie/beego` under vendor dir, it should be update to beego/beego
> 
> I am confused if it is `make veify` or `make verify`.

make verify

**Comment by MeenuyD** [comment]
> > > @MeenuyD You need to run `make veify` to update the vendor, thanks, and now we still use the `github.com/astaxie/beego` under vendor dir, it should be update to beego/beego
> > 
> > 
> > I am confused if it is `make veify` or `make verify`.
> 
> make verify

I have installed the go1.19 version but it is giving me same error

**Comment by Shelley-BaoYue** [comment]
Could you please provide some screenshots of the error and the result of executing `go version` ?

**Comment by Shelley-BaoYue** [comment]
/close 
Completed in PR #5092

**Pull request closed without merging**
