### PR TITLE
Issue #44 : Fix data race while setting write deadline of websocket connection.

### PR DESCRIPTION
**Pull request by rohitsardesai83**
Issue #44 : Fix data race while setting write deadline of websocket connection.

### CODE REVIEW

**Comment by m1093782566** [comment]
LGTM

@rohitsardesai83 Would you please squash the commits?

**Comment by Baoqiang-Zhang** [comment]
LGTM
@m1093782566 I think it can be merged.

**Comment by m1093782566** [comment]
Okay, @Baoqiang-Zhang you should have the permission to approve this PR, then we can merge it.

**Comment by m1093782566** [comment]
Thanks!

**Pull request merged**
