### PR TITLE
Add more reviewers to OWNERS

### PR DESCRIPTION
**Pull request by fisherxu**
**What this PR does / why we need it**:
Add more reviewer the bot can request :)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fisherxu** [comment]
/hold
Let's hold it until Friday :)

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by sids-b** [comment]
Thanks @fisherxu . +1 binding

Although approvers are added as reviewers. let us make sure that a person adds only one of the lgtm and approve labels in a PR unless the PR is required urgently to ensure through review of the code. Thanks :)

**Comment by fisherxu** [comment]
/hold cancel
Let's got it merged

**Pull request merged**
