### PR TITLE
Optimize the modbus module to adapt to the latest code

### PR DESCRIPTION
**Pull request by Cosmoplat-edge**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
@Cosmoplat-edge Thanks for your contribution!

My concern is that after this change, examples under kubeedge/examples repo still works?

**Comment by daixiang0** [comment]
@ttlv please take a loot at this.

**Comment by fisherxu** [comment]
cc @sailorvii

**Comment by ttlv** [comment]
> @ttlv please take a loot at this.

ok, I have worked together with sailorvii, the modbus refactor is going on now,but it still has some bugs in it and also need more time to fix it,we will speed up for modbus mapper

**Comment by ttlv** [comment]
we will restructure modbus mapper in golang.I mean that golang version will replace js version,just have a look for this issue https://github.com/kubeedge/kubeedge/issues/1953

**Comment by daixiang0** [comment]
ping @Cosmoplat-edge

**Comment by sailorvii** [comment]
The new mapper will not impact other modules. It has been implemented and this issue could be closed.

**Pull request closed without merging**
