### PR TITLE
use constant for pod condition

### PR DESCRIPTION
**Pull request by TianTianBigWang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by mjlshen — APPROVED** [review]

**Comment by zc2638** [comment]
/lgtm
@assign @fisherxu

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
