### PR TITLE
CI: enable go module cache

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**

 /kind test

**What this PR does / why we need it**:

Cache go module to speed up.

Refer to this [blog](https://restic.net/blog/2018-09-02/travis-build-cache/).

### CODE REVIEW

**Comment by fisherxu** [comment]
Looks like no need for linux since there's cache under GOPATH?

**Comment by daixiang0** [comment]
There is cache under GOPATH while travis-ci would clean it if no config.

**Pull request merged**
