### PR TITLE
keadm: refactoring retryDownload

### PR DESCRIPTION
**Pull request by zc2638**
Support to skipping checksum verification and refactoring retryDownload

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by zc2638** [comment]
I found that skipping validation checksum was already being resolved in #2450, so it was removed

**Comment by fisherxu** [comment]
@zc2638 Would you like squash the commits?

**Comment by zc2638** [comment]
> @zc2638 Would you like to squash the commits?

okey

**Comment by fisherxu** [comment]
/lgtm
/approve
thanks :)

**Pull request merged**
