### PR TITLE
bump kubernetes dependency version to v1.27.7

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

upgrade kubernetes dependency version 1.27.7 

#5117

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
PTAL @fisherxu  
CI need to be updated to add 1.27 and remove 1.24. 
image

**Comment by WillardHu** [comment]
This pull request needs to cancel the compatibility test required checks of 1.24 k8s

**Comment by fisherxu** [comment]
> CI need to be updated to add 1.27 and remove 1.24.


After the PR get merged, I'll set it.

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
