### PR TITLE
Optimization part goroutine

### PR DESCRIPTION
**Pull request by qiuax**
Optimization part goroutine

### CODE REVIEW

**Comment by qiuax** [comment]
signed off by /assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Thanks for your contribution, please add DCO sign in your commits. Ref: https://probot.github.io/apps/dco/
And please refresh the PR description according to PR template, this helps reviewers understand what is this PR trying to fix and why changing in this way. :-)

**Comment by qiuax** [comment]
What type of PR is this?
 Add goroutine util:
code in project   /common/goroutine/goroutine.go

What this PR does / why we need it:
The goroutine in the existing code is not robust, and this panic is not captured. If Ctrip internal panic, it will cause the main Ctrip to crash

Which issue(s) this PR fixes:
This PR fixes the capture of panic in goroutine, even if panic appears inside the goroutine, the main Ctrip can operate normally.

/assign @kevin-wangzefeng

**Comment by qiuax** [comment]
What type of PR is this?
 Add goroutine util:
code in project   /common/goroutine/goroutine.go

What this PR does / why we need it:
The goroutine in the existing code is not robust, and this panic is not captured. If Ctrip internal panic, it will cause the main Ctrip to crash

Which issue(s) this PR fixes:
This PR fixes the capture of panic in goroutine, even if panic appears inside the goroutine, the main Ctrip can operate normally.

/assign @kevin-wangzefeng

Signed-off-by: qiuax 704183303@qq.com

**Comment by qiuax** [comment]
What type of PR is this?
Add goroutine util:
code in project /common/goroutine/goroutine.go

What this PR does / why we need it:
The goroutine in the existing code is not robust, and this panic is not captured. If Ctrip internal panic, it will cause the main Ctrip to crash

Which issue(s) this PR fixes:
This PR fixes the capture of panic in goroutine, even if panic appears inside the goroutine, the main Ctrip can operate normally.
/assign @kevin-wangzefeng

Signed off by: qiuax 704183303@qq.com

**Pull request closed without merging**
