### PR TITLE
Rename device dir which place mapper to mappers

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sids-b** [comment]
Thanks @fisherxu

**Comment by rohitsardesai83** [comment]
@fisherxu , please resolve the conflicts. Thanks.

**Comment by fisherxu** [comment]
@rohitsardesai83  have rebased

**Pull request merged**
