### PR TITLE
fix keadm init profile in v1.17.0 for keadm_e2e test.

### PR DESCRIPTION
**Pull request by luomengY**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by luomengY** [comment]
PTAL @Shelley-BaoYue @WillardHu

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm 
And as disscussed in issue [#5601](https://github.com/kubeedge/kubeedge/issues/5601), I think we should still support `--profile version` in v1.17 (maybe 1.18 also), and claim it will be deprecated at 1.19. During these two release, users have enough time to get this change and modify it.

**Comment by luomengY** [comment]
> And as disscussed in issue [#5601](https://github.com/kubeedge/kubeedge/issues/5601), I think we should still support `--profile version` in v1.17 (maybe 1.18 also), and claim it will be deprecated at 1.19. During these two release, users have enough time to get this change and modify it.

ok， I will propose another PR to handle compatibility.

**Comment by luomengY** [comment]
@fisherxu

**Comment by Shelley-BaoYue** [comment]
fix CI issue cause by https://github.com/kubeedge/kubeedge/pull/5461

**Pull request merged**
