### PR TITLE
Fixed a null pointer error when PushMethod is not defined for device properties.

### PR DESCRIPTION
**Pull request by luomengY**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When the device's properties do not define PushMethod, a null pointer error will be reported, such as pptv.PushMethod.DBMethod in the code reporting a null pointer exception. Therefore, this optimization is to avoid reporting null pointer exceptions.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
@cl2017 @wbc6080 
**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
Hi, @luomengY , you need to rebase the master branch and push again to solve the failed CI.

**Comment by wbc6080** [comment]
Could you please help to fix other codes where null pointer error may be present?  I find the same error in device/device.go at the dataHandler function, util/parse/grpc.go at getPushMethodFromGrpc and getDBMethodFromGrpc function.  Thank you very much!

**Comment by luomengY** [comment]
> Could you please help to fix other codes where null pointer error may be present? I find the same error in device/device.go at the dataHandler function, util/parse/grpc.go at getPushMethodFromGrpc and getDBMethodFromGrpc function. Thank you very much!

Just add pptv. PushMethod to line 139 of the buildPropertiesFromGrpc function in util/parse/grpc.go= Neil, the places you mentioned will no longer report null pointers, as all of them have been taken into account in PR.

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Comment by fisherxu** [comment]
Please chery-pick to release-1.15, thanks :) @Shelley-BaoYue @luomengY

**Pull request merged**
