### PR TITLE
fix downstream

### PR DESCRIPTION
**Pull request by guojianyu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
/kind bug
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
/lgtm
Thanks, really a bug. 
```
I0714 15:01:22.585309   17475 objectsync.go:149] configmap: log-config1 has been deleted in K8s, send the delete event to edge
```
I just tested this, first I create a configmap and pod mount configmap, when pod become running, then delete the pod and configmap. And the configmap still be deleted in the edgeside by the `synccontroller` as the log above. But the PR is still reasonable.

**Comment by guojianyu** [comment]
> /lgtm
> Thanks, really a bug.
> 
> ```
> I0714 15:01:22.585309   17475 objectsync.go:149] configmap: log-config1 has been deleted in K8s, send the delete event to edge
> ```
> 
> I just tested this, first I create a configmap and pod mount configmap, when pod become running, then delete the pod and configmap. And the configmap still be deleted in the edgeside by the `synccontroller` as the log above. But the PR is still reasonable.



> /lgtm
> Thanks, really a bug.
> 
> ```
> I0714 15:01:22.585309   17475 objectsync.go:149] configmap: log-config1 has been deleted in K8s, send the delete event to edge
> ```
> 
> I just tested this, first I create a configmap and pod mount configmap, when pod become running, then delete the pod and configmap. And the configmap still be deleted in the edgeside by the `synccontroller` as the log above. But the PR is still reasonable.

yes,edgecore delete pod with delete local configmap 
in kubeedge\edge\pkg\edged\edged.go  have processes  .

**Comment by fisherxu** [comment]
> yes,edgecore delete pod with delete local configmap

When edgecore delete a pod, it will also delete the configmap?

**Comment by guojianyu** [comment]
> > yes,edgecore delete pod with delete local configmap
> 
> When edgecore delete a pod, it will also delete the configmap locally?

it delete cache configmap ,i do not find to delete sqlite data .i also loking at the code .Now
but this fix can solve all problems.

**Pull request merged**
