### PR TITLE
Reducing wait time for edgehub unit test

### PR DESCRIPTION
**Pull request by sujithsimon22**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
Reduces wait time for unit test in edgehub

### CODE REVIEW

**Comment by sujithsimon22** [comment]
cc @fisherxu @kevin-wangzefeng @sids-b @rohitsardesai83

**Comment by sids-b** [comment]
Technically we should not be having sleep here.... We need to find a logical way to deal with the sync problem.

**Comment by sids-b** [comment]
We have sleep's in all test files in edgehub/ directory as well which is not correct way to solve synchronization. Adding sleep for n seconds in a thread ensures that the thread is blocked for n seconds but there is no guarantee that the thread will start executing after n seconds.....

**Comment by fisherxu** [comment]
Do we need the write config file operation here? can read from a exist file? And by the way, when we change to the config API, this test may will be removed :)

**Pull request closed without merging**
