### PR TITLE
add beehive code intree

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes: part of https://github.com/kubeedge/kubeedge/issues/1082

**Special notes for your reviewer**:
- First 27 commits are from beehive/master (generated by scripts from https://github.com/kubeedge/kubeedge/pull/1156)
- Actually only last 5 commits need review.

**Does this PR introduce a user-facing change?**:

```release-note
move beehive code intree
```

### CODE REVIEW

**Comment by edisonxiang** [comment]
@sids-b @rohitsardesai83 for review

**Comment by subpathdev** [comment]
can you rebase to master please?

**Comment by subpathdev** [comment]
sry the commits are the state of kubeedge/beehive;

Can we skip the commit history here?

**Comment by sids-b** [comment]
Thanks @kevin-wangzefeng 

/approve

**Comment by sids-b** [comment]
@subpathdev lets keep the commit history. it will help in tracking the changes.

**Pull request merged**
