### PR TITLE
Update modules info in readme

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**

> /kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by edisonxiang** [comment]
@fisherxu It is ok to me. @kadisi 
/lgtm

**Comment by fisherxu** [comment]
> It seems like lgtm is not able to use to members now:(

Do we have any config to the `lgtm` label, which should can be add by all mebers :) @sids-b @rohitsardesai83 @naveensriram

**Pull request merged**
