### PR TITLE
Adding visio file for KubeEdge architecture diagram

### PR DESCRIPTION
**Pull request by sujithsimon22**
**What type of PR is this?**

 /kind documentation

**What this PR does / why we need it**:
This PR contains the source file for KubeEdge architecture document. Users can use this to update the architecture diagram

### CODE REVIEW

**Comment by sujithsimon22** [comment]
cc @sids-b @rohitsardesai83

**Comment by yamt** [comment]
@sujithsimon22 

thank you!

a question; can we have a Makefile, bat file, or something to convert it to png?
or does it always require manual operation?
(probably a dumb question as i haven't used visio.)

**Comment by sujithsimon22** [comment]
> @sujithsimon22
> 
> thank you!
> 
> a question; can we have a Makefile, bat file, or something to convert it to png?
> or does it always require manual operation?
> (probably a dumb question as i haven't used visio.)

@yamt I understand what you are trying to say. If I'm not wrong, we need to use visio software to view and edit this file and visio provides an option to convert it into PNG file. If you have any kind of script or makefile which could convert these visio source files to png, pls feel free to contribute :), but i guess we still we need to use visio to edit though

**Comment by sids-b** [comment]
I think we should move our architecture picture to some online tool like draw.io, etc and share the link so it can be  made available to everyone for updating and converting to PNG.

**Comment by kevin-wangzefeng** [comment]
Let's get this accepted first and then find alternative solution.

**Pull request merged**
