### PR TITLE
Add tips to clean up certificates in secret

### PR DESCRIPTION
**Pull request by ls889**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

/kind documentation

**What this PR does / why we need it**:
when users have ever manually configured the wrong certificates locally, the cloudcore won't generate the certificates automatically because there are certs in secret. Users need to delete certs in secret.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
@ls889 Delete the `fix logs` commit? The docs change could merged.

**Comment by ls889** [comment]
@fisherxu Sorry, `fix logs` commit should not appear here, I forgot to delete.

**Comment by ls889** [comment]
Kindly ping @fisherxu
`fix logs` commit has been deleted.

**Pull request merged**
