### PR TITLE
WIP: Make

### LINKED ISSUE #613: Make release via script
**What would you like to be added**:

Make release via script in Makefile, e.g. make quick-release.

**Why is this needed**:

### PR DESCRIPTION
**Pull request by subpathdev**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- create release files easy with: make release
- adding make clean 
- ignoring build files in the repository

**Which issue(s) this PR fixes**:
Fixes #613

**Special notes for your reviewer**:
you can check the checksum files with: shasum -c *.checksum
we can simple new operations systems and architectures by adding them in the variables:
 - RELEASE_KUBEEDGE_ARCH
 - RELEASE_EDGE_ARCH
 - RELEASE_KEADM_ARCH
 - RELEASE_OS
The idea to specify the operation system and architecture I found here: https://golangcookbook.com/chapters/running/cross-compiling/

### CODE REVIEW

**Comment by subpathdev** [comment]
I didn't have the chance to test the ARM files. Can somebody run them? (This is the reason to be in work in progress state)

**Comment by m1093782566** [comment]
@subpathdev 

Do you want to join KubeEdge as a member or collaborator?

**Comment by subpathdev** [comment]
> @subpathdev
> 
> Do you want to join KubeEdge as a member or collaborator?
Yes, it would be nice and an honor.

**Comment by m1093782566** [comment]
@subpathdev 

Just sent the invitation :)

**Comment by subpathdev** [comment]
thank you

**Comment by sids-b** [comment]
@subpathdev , can you please add a README for usage of this command ? Also we can you please give sample like how do we specify that from which branch the release is cut, etc ?
I can ask someone to try it out e2e and ping here :)

**Comment by subpathdev** [comment]
I will write a README to use the command and expand architectures and operations systems.

**Comment by sids-b** [comment]
Thanks @subpathdev ... it would help in reviewing this PR :)

**Comment by subpathdev** [comment]
> Thanks @subpathdev ... it would help in reviewing this PR :)
Is added

**Comment by subpathdev** [comment]
I will close this and I will start another version of automated build release packages.

**Pull request closed without merging**
