### PR TITLE
Improve a warn message

### PR DESCRIPTION
**Pull request by hainesc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:
Improve a warn message
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

See 
https://www.quora.com/Which-of-the-following-is-correct-1-He-has-been-elected-as-the-chairman-of-our-college-2-He-has-been-elected-chairman-of-our-college
https://forum.wordreference.com/threads/elected-or-elected-as.3314339/

### CODE REVIEW

**Comment by hainesc** [comment]
/assign @cindyxing

Need retest as it fails because of a flaky test.

**Comment by sids-b** [comment]
@hainesc , just restarted the test job.

**Comment by hainesc** [comment]
@sids-b thanks for the retest.
Please take a look at this pr.

**Comment by sids-b** [comment]
/lgtm
/approve

Thanks @hainesc

**Pull request merged**
