### PR TITLE
update project maintainers

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

- Add @chendave, @kadisi and @fisherxu as new maintainers.

- Move @CindyXing @m1093782566 @rohitsardesai83 to emeritus.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by sids-b** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
### Contributions done by @chendave 
- PR authored: https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Achendave+user%3Akubeedge
- PR reviewed: https://github.com/pulls?q=is%3Apr+is%3Amerged+commenter%3Achendave+user%3Akubeedge
- Issue created: https://github.com/issues?q=is%3Aissue+user%3Akubeedge+author%3Achendave
- Issue commented: https://github.com/issues?q=is%3Aissue+user%3Akubeedge+commenter%3Achendave


### Contributions done by @fisherxu  
- PR authored: https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Afisherxu+user%3Akubeedge
- PR reviewed: https://github.com/pulls?q=is%3Apr+is%3Amerged+commenter%3Afisherxu+user%3Akubeedge
- Issue created: https://github.com/issues?q=is%3Aissue+user%3Akubeedge+author%3Afisherxu
- Issue commented: https://github.com/issues?q=is%3Aissue+user%3Akubeedge+commenter%3Afisherxu

### Contributions done by @kadisi  
- PR authored: https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Akadisi+user%3Akubeedge
- PR reviewed: https://github.com/pulls?q=is%3Apr+is%3Amerged+commenter%3Akadisi+user%3Akubeedge
- Issue created: https://github.com/issues?q=is%3Aissue+user%3Akubeedge+author%3Akadisi
- Issue commented: https://github.com/issues?q=is%3Aissue+user%3Akubeedge+commenter%3Akadisi

**Comment by chendave** [comment]
/lgtm
thanks!

**Pull request merged**
