### PR TITLE
pkg/util/util.go: fix get local ip issue

### PR DESCRIPTION
**Pull request by fisherxu**
Signed-off-by: fisherxu <xufei40@huawei.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This is a follow up pr of #2689 , when looks up from host failed, we will still use ChooseHostInterface to get.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
cc @zc2638 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zc2638** [comment]
looks goo to me.

**Comment by daixiang0** [comment]
/lgtm


/retitle pkg/util/util.go: fix get local ip issue

**Comment by fisherxu** [comment]
> /lgtm
> 
> /retitle pkg/util/util.go: fix get local ip issue

Is there any rules that need always to retitle the pr title?

**Comment by daixiang0** [comment]
Maybe we can discuss the rule on Wednesday.

**Comment by fisherxu** [comment]
> Maybe we can discuss the rule on Wednesday.

Sure, but it's better to not modify it without the author's permission.

**Comment by daixiang0** [comment]
Sure

**Review by chendave — COMMENTED** [review]
/approve

**Pull request merged**
