### PR TITLE
edged.go: Fix pod sync copied from kubelet

### LINKED ISSUE #1364: Network unreachable in container
**What happened**:

I deployed my deployment, but kubeedge ran my container first, then the kubeedge/pause:3.1 container.
So my container can not access the network.

This problem does not happen every time.
When it happens, the "docker ps" command show like this:
image

And in this case, I would get "Network unreachable" in my container.
image

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

### PR DESCRIPTION
**Pull request by faicker**
/kind bug

Fixes #1364 

It happens when two same message from the cloud-hub(because auto resend)

### CODE REVIEW

**Comment by fisherxu** [comment]
Thanks for your fix! @faicker 
And I noticed another PR raised by you #1796, they all fixed #1364, do we need combine them in one PR?

**Comment by faicker** [comment]
These are two different cases which leads to the same result.
Maybe not good to combine them, but I can combine them If you want.

**Comment by fisherxu** [comment]
Sorry for the delay and thanks for the fixing! @faicker

**Pull request merged**
