### PR TITLE
replace vendor github.com/dgrijalva/jwt-go with github.com/golang-jwt/jwt

### PR DESCRIPTION
**Pull request by gy95**
Signed-off-by: gy95 <guoyao17@huawei.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
package `github.com/dgrijalva/jwt-go` is no longer maintained. So just replace this package with `github.com/golang-jwt/jwt` 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
`golang-jwt/jwt` may need a higher go version
Ref: https://github.com/golang/go/commit/c9d5f60eaa4450ccf1ce878d55b4c6a12843f2f3, function `FillBytes` is born in release 1.15beta. But now we are using 1.14 go.

**Comment by fisherxu** [comment]
> when run `make` command to build binaries, error is
> 
> ```
> + go build -o /home/runner/work/kubeedge/kubeedge/_output/local/bin/cloudcore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2021-09-23T02:24:12Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=95e43b709cc08fcd449c33d537943ec6bab58beb -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.8.0-beta.0.127+95e43b709cc08f -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=8+' github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
> # github.com/golang-jwt/jwt
> vendor/github.com/golang-jwt/jwt/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
> vendor/github.com/golang-jwt/jwt/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)
> Makefile:49: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> `golang-jwt/jwt` may need a higher go version
> Ref: [golang/go@c9d5f60](https://github.com/golang/go/commit/c9d5f60eaa4450ccf1ce878d55b4c6a12843f2f3), function `FillBytes` is born in release 1.15beta. But now we are using 1.14 go.

We can upgrade to 1.15.

**Comment by gy95** [comment]
> > when run `make` command to build binaries, error is
> > ```
> > + go build -o /home/runner/work/kubeedge/kubeedge/_output/local/bin/cloudcore -gcflags= -ldflags '-s -w -buildid= -X github.com/kubeedge/kubeedge/pkg/version.buildDate=2021-09-23T02:24:12Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=95e43b709cc08fcd449c33d537943ec6bab58beb -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.8.0-beta.0.127+95e43b709cc08f -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=8+' github.com/kubeedge/kubeedge/cloud/cmd/cloudcore
> > # github.com/golang-jwt/jwt
> > vendor/github.com/golang-jwt/jwt/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
> > vendor/github.com/golang-jwt/jwt/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)
> > Makefile:49: recipe for target 'all' failed
> > make: *** [all] Error 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `golang-jwt/jwt` may need a higher go version
> > Ref: [golang/go@c9d5f60](https://github.com/golang/go/commit/c9d5f60eaa4450ccf1ce878d55b4c6a12843f2f3), function `FillBytes` is born in release 1.15beta. But now we are using 1.14 go.
> 
> We can upgrade to 1.15.

ok, maybe i need open another PR to upgrade go to 1.14, because maybe related codes need huge update

**Comment by fisherxu** [comment]
> ok, maybe i need open another PR to upgrade go to 1.14, because maybe related codes need huge update

yes.

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
