### PR TITLE
WIP: Add dynamic controller on cloudcore

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Send objects based on edge requests dynamically, proposal doc TBD.

This pr will be merged into #2508 later. cc  @threestoneliu  @gccio  @GsssC
 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add dynamic controller on cloudcore, send objects based on edge requests dynamically
```

### CODE REVIEW

**Comment by daixiang0** [comment]
Is it perceived by users?

**Comment by fisherxu** [comment]
> Is it perceived by users?

For the first step, users need to config the gvr to cloudcore.

**Comment by fisherxu** [comment]
@GsssC You can pick this PR to you PR #2508 :)

**Comment by fisherxu** [comment]
Will close this one in favor of #2508

**Pull request closed without merging**
