### PR TITLE
Make sure the bluetoothdevice image is built in Travis CI

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind bug

```release-note
NONE
```

### CODE REVIEW

**Comment by chendave** [comment]
cc @fisherxu

**Comment by fisherxu** [comment]
See #1230

**Comment by chendave** [comment]
@fisherxu , thanks for the info, could you pls let me do some investigation first?

**Comment by fisherxu** [comment]
> could you pls let me do some investigation first?

Sure thanks!

**Comment by chendave** [comment]
hmm, I cannot get through it and filed an issue here:
https://travis-ci.community/t/before-install-cannot-exit-successfully-on-arm/5731

let's see is there any answer by tomorrow. I am also good with comment out all ARM related check by far, we can open it when all those issue got fixed.

cc @fisherxu

**Comment by fisherxu** [comment]
> let's see is there any answer by tomorrow. I am also good with comment out all ARM related check by far, we can open it when all those issue got fixed.

Ok agreed, let's comment them in this PR and avoid block other PRs.

**Comment by chendave** [comment]
Done, pls take another look, thanks!

**Comment by fisherxu** [comment]
/lgtm
Let's got it merged.

**Pull request merged**
