### PR TITLE
fix white noise issue

### PR DESCRIPTION
**Pull request by gy95**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
fix white noise issue of CHANGELOG 1.9
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
this white noise check seems to be confusing 😂 
with a new commit submit based on changelog1.9, white noise will be checked. 
but if without any fix, it will not be checked.

**Comment by daixiang0** [comment]
> this white noise check seems to be confusing 😂

You can use `git diff` to show white noise :)

**Comment by gy95** [comment]
> > this white noise check seems to be confusing 😂
> 
> You can use `git diff` to show white noise :) This check fix issue not visible to the naked eyes.

yes, this path is automated fixed by check, but is checked occasionally, sometimes it can be checked, but sometimes cannot.

**Comment by gy95** [comment]
```
• Failure [253.012 seconds]
Application deployment in edgecore Testing
/home/runner/work/kubeedge/kubeedge/edge/test/integration/appdeployment/application_test.go:39
  Test application deployment and delete deployment
  /home/runner/work/kubeedge/kubeedge/edge/test/integration/appdeployment/application_test.go:41
    TC_TEST_APP_DEPLOYMENT_5: Test application deployment delete from edgecore [It]
    /home/runner/work/kubeedge/kubeedge/edge/test/integration/appdeployment/application_test.go:100

    Timed out after 240.002s.
    Application Deployment is Unsuccessful, Pod has not come to Running State
    Expected
        <string>: Succeeded
    to equal
        <string>: Running

    /home/runner/work/kubeedge/kubeedge/edge/test/integration/utils/helpers/helpers.go:363
```

**Comment by gy95** [comment]
according to the official comment, for pod status, both `Succeeded` and `Running` are OK.
```
// The phase of a Pod is a simple, high-level summary of where the Pod is in its lifecycle.
// The conditions array, the reason and message fields, and the individual container status
// arrays contain more detail about the pod's status.
// There are five possible phase values:
//
// Pending: The pod has been accepted by the Kubernetes system, but one or more of the
// container images has not been created. This includes time before being scheduled as
// well as time spent downloading images over the network, which could take a while.
// Running: The pod has been bound to a node, and all of the containers have been created.
// At least one container is still running, or is in the process of starting or restarting.
// Succeeded: All containers in the pod have terminated in success, and will not be restarted.
// Failed: All containers in the pod have terminated, and at least one container has
// terminated in failure. The container either exited with non-zero status or was terminated
// by the system.
// Unknown: For some reason the state of the pod could not be obtained, typically due to an
// error in communicating with the host of the pod.
//
// More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-phase
// +optional
Phase PodPhase `json:"phase,omitempty" protobuf:"bytes,1,opt,name=phase,casttype=PodPhase"`
```

**Comment by gy95** [comment]
> > this white noise check seems to be confusing 😂
> 
> You can use `git diff` to show white noise :) This check fix issue not visible to the naked eyes.

what's the principle or theroy of this whitenoise check 😄

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by gy95** [comment]
Not sure about why did this command 
`git diff --cached --name-only --diff-filter=ACRMTU master | grep -Ev "externalversions|fake|vendor|images|adopters | xargs --no-run-if-empty $SED_CMD -i 's/[ \t]*$//'"`
not find the white space of this PR  https://github.com/kubeedge/kubeedge/pull/3430.

Is this related to `--cached` or something else. 
@daixiang0 any advice?

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Pull request merged**
