### PR TITLE
Docs: remove useless files

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Now we move docs into website repo, no need them here.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
After https://github.com/kubeedge/website/pull/123 merged, we can remove docs here safely.

**Comment by daixiang0** [comment]
@fisherxu is time to remvoe docs in this repo? Or doc changes here need sync which is not cool.

**Comment by fisherxu** [comment]
@daixiang0  Please get the ci passed, let's get this merged.

**Comment by fisherxu** [comment]
Please keep the roadmap here so far.

**Comment by daixiang0** [comment]
@fisherxu done.

**Comment by kevin-wangzefeng** [comment]
There are a lot of files no longer used in docs/images, maybe remove them as well.

**Comment by kevin-wangzefeng** [comment]
And please fix the deadlink issue

**Review by kevin-wangzefeng — CHANGES_REQUESTED** [review]
Please search for the remainder ref to the `/docs` files and fix the dead link
```bash
find . -name "*.md" |grep -v vendor |xargs grep -on "docs/.*\.md"
```

**Comment by daixiang0** [comment]
ping @fisherxu @kevin-wangzefeng

**Comment by fisherxu** [comment]
Have the dead links been fixed?

**Comment by daixiang0** [comment]
Will update all docs linked to website.

**Comment by fisherxu** [comment]
> Will update all docs linked to website.

Have no in this repo?

**Comment by daixiang0** [comment]
@fisherxu I have updated all links and remove useless images, please review again!

**Review by fisherxu — COMMENTED** [review]
Please leave the `docs/images/KubeEdge_arch.vsdx` file for refactoring the arch pic, thanks.

**Comment by daixiang0** [comment]
> Please leave the `docs/images/KubeEdge_arch.vsdx` file for refactoring the arch pic, thanks.

Now we use arch.png instead, do you mean replace it?

**Comment by fisherxu** [comment]
> > Please leave the `docs/images/KubeEdge_arch.vsdx` file for refactoring the arch pic, thanks.
> 
> Now we use arch.png instead, do you mean replace it?

Do not delete the docs/images/KubeEdge_arch.vsdx

**Comment by daixiang0** [comment]
Done.

**Review by fisherxu — COMMENTED** [review]
/lgtm
/assign @kevin-wangzefeng

**Pull request merged**
