### PR TITLE
fix bug #866

### LINKED ISSUE #866: edge_core cannot connect to edgecontroller after disconnecting once
**What happened**:
Stopped and started edge_core, it caused problem while creating websocket connection

**What you expected to happen**:
Connect successfully via websocket

**How to reproduce it (as minimally and precisely as possible)**:
1) Start edgecontroller
2) Start edge_core
3) Stop edge_core
4) Start edge_core again
Error logs will come in both edgecontroller and edge_corethen

**Anything else we need to know?**:
Looks like some issue in closing of websocket connection

**Environment**:
- KubeEdge version: latest master

### PR DESCRIPTION
**Pull request by shouhong**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
1. When edge node disconnecting from edgecontroller, the edgecontroller does not aware this until the next keepalive message is not received from the edge node. 
2. The edge node connection information is not cleaned up until the edgecontroller aware the edge node is not alive.
3. If the edge node connect to edgecontroller again before the previous obsolete connection information was cleaned up, it will get an error.
4. To fix this problem, add retry mechanism to wait for the previous obsolete connection information to be cleanup.

**Which issue(s) this PR fixes**:
Fixes #866

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sids-b** [comment]
just restarted the test

**Comment by sids-b** [comment]
@kexun @shouhong , I just had 1 question. In websocket, if a client or server loses connection with other, I think it immediately gets notified and err is returned. The previous implementation was something similar. Can we not have something similar in viaduct as well ? I remember that in previous implementation it didn't need to wait for keepalive interval to remove the connection. Any thoughts ?

**Comment by shouhong** [comment]
> @kexun @shouhong , I just had 1 question. In websocket, if a client or server loses connection with other, I think it immediately gets notified and err is returned. The previous implementation was something similar. Can we not have something similar in viaduct as well ? I remember that in previous implementation it didn't need to wait for keepalive interval to remove the connection. Any thoughts ?

@sids-b 
1. In previous implementation, there is a "EventReadLoop" function in which there is loop to **actively** read data from edge node (the timeout value is keepalive interval).  So if the edge node loses connection, the read function will immediately get an error. 
2. After switching to viaduct, we follow the implementation patten in the viaduct example (https://github.com/kubeedge/viaduct/blob/master/examples/chat/server.go). In this example, the server side register a callback function named "handleServer" to **passively** read data from client side. If the client loses connection, the server is not notified immediately. 
3. Do you think we need to follow the previous pattern to actively read data from edge node?

**Comment by sids-b** [comment]
@kexun your thoughts ? I think we may lose some messages in the KeepAliveInterval so an active read loop would be a good option for websocket ??

**Comment by sids-b** [comment]
@rohitsardesai83 @qizha , thoughts ??

**Comment by sids-b** [comment]
I think lets get this fix in first and later we can think about comparing implementation.

/lgtm

**Pull request merged**
