### PR TITLE
use command flag for e2e config

### PR DESCRIPTION
**Pull request by wackxu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

use non-version config file is not user friendly and user need to look the source code to  understand what they can config, so switch to comman line and we also use ginkgo to run the e2e test and user can config ginkgo to run their wanted test.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
LGTM 👍 
/cc @fisherxu

**Comment by gy95** [comment]
LGTM
/assign @fisherxu

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
