### PR TITLE
improve test coverage

### PR DESCRIPTION
**Pull request by gy95**
Signed-off-by: gy95 <guoyao17@huawei.com>

**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
add some test to improve test coverage
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by zc2638** [comment]
Please rename the test file `pkg/util/uitl_test.go` as `pkg/util/util_test.go`

**Comment by gy95** [comment]
> Please rename the test file `pkg/util/uitl_test.go` as `pkg/util/util_test.go`

done

**Review by subpathdev — APPROVED** [review]

**Review by fisherxu — COMMENTED** [review]
/approve

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Pull request merged**
