### PR TITLE
[proposal] Device CRD v1beta1

### PR DESCRIPTION
**Pull request by cl2017**
**What type of PR is this?**
/kind design

**What this PR does / why we need it**:
This proposal describes the concept and design detail of the Device CRD `v1beta1` version, along with an explanation of the reasons behind it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by WillardHu** [comment]
Device Model CRD is deprecated, no new definition here?
```markdown
## Goals

- Refactor the Device module
- Device Instance CRD `v1beta1` - added
- Device Instance CRD `v1alpha2` - deprecated
- Device Model CRD `v1alpha2` - deprecated
- Device ConfigMap - deprecated
```

**Comment by WillardHu** [comment]
Is the `DeviceData.DataTopic` a topic prefix or a single chennel to send all properties json data

**Comment by cl2017** [comment]
> Device Model CRD is deprecated, no new definition here?
> 
> ```
> ## Goals
> 
> - Refactor the Device module
> - Device Instance CRD `v1beta1` - added
> - Device Instance CRD `v1alpha2` - deprecated
> - Device Model CRD `v1alpha2` - deprecated
> - Device ConfigMap - deprecated
> ```

Yes, the deviceModel has been deprecated in this refactoring. There will be new discussions in the future to determine whether the deviceModel is still needed, and its specific and usage will be reconsidered.

**Comment by cl2017** [comment]
> Is the `DeviceData.DataTopic` a topic prefix or a single chennel to send all properties json data

`DeviceData.DataTopic` has been removed now,  please use `PushMethod` to push data to MQTT.

**Review by fisherxu — COMMENTED** [review]
@cl2017 Please update the proposal, thanks :)

**Comment by cl2017** [comment]
> @cl2017 Please update the proposal, thanks :)

I've already updated it, please take a look, thanks. @fisherxu @WillardHu

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
