### PR TITLE
Fix if/else statement have exactly the same implementation

### PR DESCRIPTION
**Pull request by mengjiao-liu**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**:

All branches in a conditional structure should not have exactly the same implementation.

Having all branches in a switch or if chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a switch/if chain at all.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by daixiang0** [comment]
lgtm

**Comment by fisherxu** [comment]
Please sign off in your commit to fix the DCO ci issue. @mengjiao-liu

**Comment by mengjiao-liu** [comment]
> Please sign off in your commit to fix the DCO ci issue. @mengjiao-liu

Tha

**Comment by mengjiao-liu** [comment]
> Please sign off in your commit to fix the DCO ci issue. @mengjiao-liu

Thank you for your reminding. I have signed off it

**Pull request merged**
