### PR TITLE
messagehandler.go: Improve message handling under network jitter

### PR DESCRIPTION
**Pull request by faicker**
Fix the node not-ready state when the edge restarts
Readd the message to queue to prevent the message lost

Signed-off-by: Faicker Mo <faicker.mo@gmail.com>

/kind bug

### CODE REVIEW

**Comment by fisherxu** [comment]
Thanks for your fix! We already have a fix in #1670 , ptal  :) @faicker

**Comment by faicker** [comment]
oh, ignore this PR. 
Hope #1670 will be merged soon. This Happens often. @fisherxu

**Comment by fisherxu** [comment]
#1670  has got merged and will be released in 1.3.2 this week, feel free to rebase on it if needed :)

**Comment by fisherxu** [comment]
The issue has been fixed by #1670, so close it now, feel free to open it again if necessary. :)
/close

**Pull request closed without merging**
