### PR TITLE
Fix log spelling mistake in synccontroller

### PR DESCRIPTION
**Pull request by jidalong**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
Some log spelling mistakes in synccontroller.

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
need pass the DCO :)

**Comment by jidalong** [comment]
> need pass the DCO :)

Okay, DCO has passed :)

**Review by fisherxu — COMMENTED** [review]
/approve

**Review by threestoneliu — COMMENTED** [review]
/lgtm

**Pull request merged**
