### PR TITLE
Update build.md - Path for make

### PR DESCRIPTION
**Pull request by skdwriting**
$GOPATH/src/github.com/kubeedge/kubeedge/edge does not have the make file. Hence changed the path to $GOPATH/src/github.com/kubeedge/kubeedge/

**What type of PR is this?**

**What this PR does / why we need it**:
Fix build,md

**Which issue(s) this PR fixes**:
The make path updated

Fixes #

**Special notes for your reviewer**:
NA
**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
@skdwriting please push from forked repo, also delete this branch since it is in upstream repo.

**Comment by kevin-wangzefeng** [comment]
Added branch protection rules to avoid creating unnecessary branches on main repo.

**Pull request merged**
