### PR TITLE
CI: switch amd64 tests to Github Action

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
/approve
please squash commits

**Comment by daixiang0** [comment]
@kevin-wangzefeng please click repo setting and enable fork action, then we can see test result.

**Pull request merged**
