### PR TITLE
Delete useless function dbm

### PR DESCRIPTION
**Pull request by kadisi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Ref: #1388 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
delete useless function for  dbm package
```

### CODE REVIEW

**Comment by fisherxu** [comment]
Looks like there is something wrong with the arm vm today

**Comment by kevin-wangzefeng** [comment]
Shall we get this in without arm tests then? Other tests have succeeded.

**Comment by fisherxu** [comment]
> Shall we get this in without arm tests then? Other tests have succeeded.

+1

**Comment by kevin-wangzefeng** [comment]
OK, I'm going to manual merge this PR. If travis keeps unavailable for arm vms, we may temporarily disable it

**Pull request merged**
