### PR TITLE
FOSSA scan enabled

### PR DESCRIPTION
**Pull request by idvoretskyi**
Ref.: https://github.com/cncf/foundation/issues/109

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@idvoretskyi does it not block pr if any issues? I check the details and find some existed issues.

**Comment by kevin-wangzefeng** [comment]
/approve
Thanks

**Comment by idvoretskyi** [comment]
@daixiang0 not yet, it's just a reporting tool for now.

**Pull request merged**
