### PR TITLE
Add new reviewers for the project

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/assign @kevin-wangzefeng @chendave @kadisi 

/cc @edisonxiang @rohitsardesai83 We can add you back whenever you want to do some code works
/cc @daixiang0 @Poor12 @XJangel @ls889 @GsssC  

Just added some dirs, it may not be complete, you all can add yourself to any directory that familiar with the code by raise PR later. And reviewer can add `lgtm` label to the PR :)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
@daixiang0 @ls889 @Poor12 @GsssC @XJangel @kadisi 
Please confirm with the updates

**Comment by GsssC** [comment]
lgtm

**Comment by ls889** [comment]
lgtm

**Comment by fisherxu** [comment]
Looking forward to more contributions and reviews :)
@daixiang0 @Poor12 @XJangel @ls889 @GsssC

**Pull request merged**
