### PR TITLE
Add type check for each implementation of Module interface

### PR DESCRIPTION
**Pull request by hainesc**
Signed-off-by: Haines Chan <hainescx@gmail.com>

**What type of PR is this?**

**What this PR does / why we need it**:
Improve code readable, see https://golang.org/doc/effective_go#blank_implements
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gy95** [comment]
this is redundant, if a specifics module doesn't implement all the methods of interface `Module`, will not pass the compiling, and the compilers will report the compiler errors as below
`*cloudHub does not implement "github.com/kubeedge/beehive/pkg/core".Module (missing xxxx method)`

**Comment by gy95** [comment]
ref official docs: `By convention, such declarations are only used when there are **no static conversions** already present in the code, which is a rare event.`

**Comment by hainesc** [comment]
@gy95 see https://github.com/uber-go/guide/pull/86

**Comment by gy95** [comment]
we've tried to use struct `cloudhub` as interface `Module` here, so this is not requisite.
https://github.com/kubeedge/kubeedge/blob/a9d0a01c0c7940997e8eefe9e75b86e2b801251d/cloud/pkg/cloudhub/cloudhub.go#L46

And the interface check is used when there's no static conversions present in the code.

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by hainesc** [comment]
> we've tried to use struct `cloudhub` as interface `Module` here, so this is not requisite.
> 
> https://github.com/kubeedge/kubeedge/blob/a9d0a01c0c7940997e8eefe9e75b86e2b801251d/cloud/pkg/cloudhub/cloudhub.go#L46
> 
> And the interface check is used when there's no static conversions present in the code.

See here: https://github.com/uber-go/guide/blob/master/style.md#verify-interface-compliance
Of course, it not the guide of kubeedge, it's the guide of uber, but I think it makes sense. Refer the discussion following the upper link.

**Comment by hainesc** [comment]
> /approve

Thanks

**Comment by fisherxu** [comment]
Any comments @zc2638? :)

**Comment by zc2638** [comment]
Under normal circumstances, we need to add interface implementation verification.
In the project, `core.Register` has already done this part of the work, we can also omit it.
Of course, there is no problem adding additional interface implementation verification.

LGTM

**Comment by fisherxu** [comment]
> Under normal circumstances, we need to add interface implementation verification. In the project, `core.Register` has already done this part of the work, we can also omit it. Of course, there is no problem adding additional interface implementation verification.
> 
> LGTM

OK, I think it's more readable that indicates modules implement the Module interface.
/lgtm

**Pull request merged**
