### PR TITLE
fix ci

### PR DESCRIPTION
**Pull request by JiaweiGithub**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:
fix ci

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by wackxu — APPROVED** [review]
lgtm

**Review by fisherxu — COMMENTED** [review]
/approve
cc @gy95

**Review by gy95 — APPROVED** [review]
/lgtm

**Pull request merged**
