### PR TITLE
Generate coverprofile when test

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

Ref #2110 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
Please add more description

**Comment by kevin-wangzefeng** [comment]
close/reopen the PR to triger github actions

/close

**Comment by daixiang0** [comment]
ping @fisherxu

**Pull request merged**
