### PR TITLE
Fix Modbus Mapper Metric Param Error.

### PR DESCRIPTION
**Pull request by zongke**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
@zongke Would you like to have a review of #1902?

**Comment by fisherxu** [comment]
lgtm, would you like add your email address in the commit to your github settings? Or github can't count your contributions.
image
(Cannot associate with your GitHub account here. )

**Comment by zongke** [comment]
> lgtm, would you like to add your email address in the commit to your github settings?
> image
> 
> Or github can't count your contributions.
> image
> (Cannot associate with your GitHub account here. )

Sorry to reply late, Email has been set

**Comment by fisherxu** [comment]
> Sorry to reply late, Email has been set

Np, and would you like to have a review of #1902? :)
/lgtm
/approve

**Comment by zongke** [comment]
> > Sorry to reply late, Email has been set
> 
> Np, and would you like to have a review of #1902? :)
> /lgtm
> /approve

OK, I'll take a look

**Pull request merged**
