### PR TITLE
rename edge_core to edgecore

### LINKED ISSUE #997: Rename edge_core to edgecore
**What would you like to be added/modified**:
Now the cloudpart will be named to `cloudcore` as in #988, so `edge_core` also will be rename to `edgecore`.

**Why is this needed**:
Unified component name format.

Task list, need rename in:

- [ ] edge
- [ ] keadm
- [ ] tests
- [ ] docs
- [ ] scripts&yaml files

### PR DESCRIPTION
**Pull request by kexun**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #997 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by subpathdev** [comment]
I think we should stay by the name edge_core in the release notes of all previous releases. Thoughts?

**Comment by kexun** [comment]
> I think we should stay by the name edge_core in the release notes of all previous releases. Thoughts?

done

**Comment by kexun** [comment]
@fisherxu @kevin-wangzefeng @sids-b @rohitsardesai83

**Comment by kexun** [comment]
> I think we should stay by the name edge_core in the release notes of all previous releases. Thoughts?

ok， I've changed it.

**Comment by carlosmkb** [comment]
kubeedge v1.0.0

`keadm init --kubeedge-version=1.0.0 --kubernetes-version=1.15.2`
image

**Pull request merged**
