### PR TITLE
initialize OWNERS file for mappers and tests

### PR DESCRIPTION
**Pull request by sids-b**
**What type of PR is this?**
> /kind documentation

**What this PR does / why we need it**:
Adds Owners file for mappers and tests

**Which issue(s) this PR fixes**:
XREF #638 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by subpathdev** [comment]
I think we should wait till Wednesday to merge.
\hold
\lgtm

**Comment by subpathdev** [comment]
/hold
waiting till wednesday

**Comment by kevin-wangzefeng** [comment]
@sids-b please include items of approvers into reviewers section, so that approvers can be assigned review tasks by bot as well.

**Comment by sids-b** [comment]
Thanks @kevin-wangzefeng , Modified

**Comment by sids-b** [comment]
our CI has become very unstable. I am seeing that it is failing for almost all PRs without any reason. I think we should prioritize and fix it soon.
@kevin-wangzefeng @rohitsardesai83 @fisherxu @subpathdev @sujithsimon22 @naveensriram

**Comment by sujithsimon22** [comment]
> our CI has become very unstable. I am seeing that it is failing for almost all PRs without any reason. I think we should prioritize and fix it soon.
> @kevin-wangzefeng @rohitsardesai83 @fisherxu @subpathdev @sujithsimon22 @naveensriram

+1

**Pull request merged**
