### PR TITLE
Refactor the implementation code for the cloud init command

### PR DESCRIPTION
**Pull request by luomengY**
…gofile keadm/cmd/keadm/app/cmd/helm/cloudcore.go func Install(..) to complete the install logic.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
image

**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubeedge/kubeedge/issues/5317

**Special notes for your reviewer**:
@WillardHu 
**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by WillardHu** [comment]
Please add some test results for keadm init

**Comment by luomengY** [comment]
> Please add some test results for keadm init

test is ok

**Comment by luomengY** [comment]
add to v1.17.@Shelley-BaoYue

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
