### PR TITLE
Add metrics-server configuration with both "kubectl logs feature" and "metrics-server deployment"

### LINKED ISSUE #2092: Metrics-Sever on KubeEdge (configuration process and vague document)
**What happened**:

1. I cannot find the `certgen.sh` in the folder `/etc/kubeedge/`, and I found it in the original git clone folder in `$GOPATH/src/github.com/kubeedge/kubeedge/build/tools/certgen.sh`. Are they the same file or not? (Doc section 4.4.3 "third" step certification part for cloud core.)

2. I have no idea how to activate `cloudStream` and `edgeStream`. In the document, it is said that I could modify cloudcore.yaml **or** edgecore.yaml. However, in the last sentence, it mentioned that we need to set **both** cloudStream and edgeStream to **true**!! (Doc section 4.4.3 "fifth" step cloudStream and edgeStream setting)

3. I only found the edgecore service with the help of @GsssC (Doc section 4.4.3 "sixth" step for restarting cloudcore and edgecore.) However, I still cannot find a way to restart cloudcore.
I cannot even find any services no matter which is activated or not related to KubeEdge service (cloudcore) by using this command `sudo systemctl list-units --all`.
By the way, I used this command to restart edgecore: `systemctl restart edgecore`, and I found out that the kube-proxy containers may cause the problem.
Also, I tried to use this command to restart cloudcore: `cloudcore restart`, though I am not sure if this is the right command or not.

4. If the KubeEdge supports the CNI plugin or not? (@daixiang0 said that CNI plugin is not supported right now, but @GsssC said that )
I am using the weave-net plugin as my CNI plugin since I heard that it has good support for ARM CPU architecture. (Edge node is raspberry pi 4 or NVIDIA Jetson TX2(future)) 
If the answer is yes, could you please help me with the configuration issues.
In k8s_weave-npc container, it said that
`unable to load in-cluster configuration,  KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`
In k8s_weave container, it said that
`[kube-peers] Could not get cluster config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
Failed to get peers`

5. `kubectl top nodes` cannot get any KubeEdge edge node metrics.
image

**What you expected to happen**:

1. Get the `certgen.sh` for certificates generation.

2. Specified YAML file I do need to modify. 
(cloudcore.yaml **or** edgecore.yaml **or** both?)

3. There is a command to restart cloudcore.

4. No terminated error status on weave-net pod anymore.

5. I can see metrics like other Kubernetes nodes.

6. I can see metrics on Kubernetes Dashboard, Grafana, and Prometheus.

**How to reproduce it (as minimally and precisely as possible)**:

1. construct a KubeEdge cluster (1 master node, 1 worker node(k8s), 1 edge node(KubeEdge))
2. deploy Kubernetes Dashboard by Dan Wahlin GitHub scripts
https://github.com/DanWahlin/DockerAndKubernetesCourseCode/tree/master/samples/dashboard-security
3. deploy Grafana, Prometheus, kube-state-metrics, metrics-server by Dan Wahlin GitHub scripts
https://github.com/DanWahlin/DockerAndKubernetesCourseCode/tree/master/samples/prometheus

**Anything else we need to know?**:
Document: https://docs.kubeedge.io/_/downloads/en/latest/pdf/ 
(section 4.4.3 - `kubectl logs`)
(section 4.4.4 - `metrics-server`)
Weave-Net Pod --> contaienrs logs in RPI4
image
image
Grafana, Prometheus, metrics-server, kube-state-metrics scripts:
https://github.com/DanWahlin/DockerAndKubernetesCourseCode/tree/master/samples/prometheus

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

cloudcore:
image
image

edgecore:
edgecore --version: command not found
image

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
root@charlie-latest:/home/charlie# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
Stepping:            10
CPU MHz:             800.071
CPU max MHz:         4100.0000
CPU min MHz:         800.0000
BogoMIPS:            6000.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            9216K
NUMA node0 CPU(s):   0-5
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
- OS (e.g. `cat /etc/os-release`):
image

- Kernel (e.g. `uname -a`):
image

- Go version (e.g. `go version`): 
image

- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
command not found
image

- Hardware configuration (e.g. `lscpu`):
image

- OS (e.g. `cat /etc/os-release`):
image

- Kernel (e.g. `uname -a`):
image

- Go version (e.g. `go version`): 
image

- Others:

@GsssC 
Hi, I finally submitted an issue! Could you please give me a hand?
Thank you very much in advance!

### PR DESCRIPTION
**Pull request by s099064146**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
In issues #2092 , I was motivated by @GsssC to add this document.

**Which issue(s) this PR fixes**:

Fixes #2092 

**Special notes for your reviewer**:
Thank you for your help! Without you guys, I am not able to finish this guide.
@GsssC 
@Poor12 
@x-bytes

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Poor12 — COMMENTED** [review]
Thanks. One suggestion，It seems difficult to unify the styles of pictures. It may be better to describe the content of pictures in words. :)

**Comment by daixiang0** [comment]
Please sqush commits, there are too many commits.

**Comment by daixiang0** [comment]
@fisherxu does bot run as expected? It is not related to api i think.

**Comment by s099064146** [comment]
@Poor12 
Okay, let me try to describe it by words.
@daixiang0 
Okay, let me learn how to squash commits.

**Comment by s099064146** [comment]
@Poor12 
Could you please take a look? I think it is better now. I have transferred pictures into tables.
Thank you very much for your comment!

@daixiang0 
I am still trying to squash them. If there is any news, I will report it here. Thanks!

**Review by Poor12 — COMMENTED** [review]
Please remove pics and sqush commits.

**Comment by s099064146** [comment]
@Poor12 
Could you please tell me how to squash commits? I am trying it but I still failed again and again.
Okay, no problem, I will remove them.

**Comment by daixiang0** [comment]
@s099064146 first, you need pull upstream master and rebase it, then use `git rebase -i` to sqush.

**Comment by s099064146** [comment]
@daixiang0 
So, it should be
`git pull`
`git rebase -i`
Then do squash in vim?

**Comment by daixiang0** [comment]
```
git pull
git rebase upstream/master
git rebase -i
```

**Comment by s099064146** [comment]
@daixiang0 
I tried and it failed with HEAD ref problems.
Now I re-fork one and create a new pull-request. Thanks for your help!
Now I think I need to close this one.

**Comment by daixiang0** [comment]
@s099064146 no need to close this, you can create a branch with same name then you can see this pr updated.

**Comment by s099064146** [comment]
@daixiang0 
It is said that "the repository that submitted this pull request has been deleted."
I have no idea how to merge this back?

**Pull request closed without merging**
