### PR TITLE
Fixed edgecore will not restart when the edge node cannot obtain the IP

### LINKED ISSUE #5642: When the edge node cannot obtain the IP address, edgecore will not restart
**What happened**:

**What you expected to happen**:

When the edge node cannot obtain the IP address, edgecore works properly.

**How to reproduce it (as minimally and precisely as possible)**:

Disconnect the network cable or turn off the wifi.

**Anything else we need to know?**:

When the edge node cannot obtain the IP address, the function `newEdgeStream(..)` returns an error and call `os.Exit(1)`, refer to:
https://github.com/kubeedge/kubeedge/blob/77891f2afa51bb20e43f861d4d2b17006f712da9/edge/pkg/edgestream/edgestream.go#L71

But this IP does not seem to have any effect in the cloud, the cloud uses the node name to select the session, can we delete this get local ip related codes? @fisherxu @Shelley-BaoYue 

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When the edge node cannot obtain the IP address, edgecore will not restart

**Which issue(s) this PR fixes**:

Fixes #5642

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by WillardHu** [comment]
PTAL  @luomengY  @Shelley-BaoYue  @fisherxu

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by fisherxu** [comment]
Can we chery-pick it to releases branch? @WillardHu

**Comment by fisherxu** [comment]
> > Can we chery-pick it to releases branch? @WillardHu
> 
> Ok, cherry-pick to 1.15, 1.16, 1.17?

yes sure :)

**Pull request merged**
