### PR TITLE
added yaml changes to show coverage report

### LINKED ISSUE #111: CI enhancement
CI while running jobs is cloning code from fork, whereas it should clone from kubeedge master and apply commits of PR in it. Also we need daily build, test jobs.
cc @m1093782566 @rohitsardesai83

### PR DESCRIPTION
**Pull request by srivatsav123**
this changes add yaml changes to report coverage in TravisCI

**What type of PR is this?**
 /kind test

**What this PR does / why we need it**:
to show coverage report in CI
**Which issue(s) this PR fixes**:
Adding Unit test coverage report to TravisCI
*Automatically closes linked issue when PR is merged.
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
_If PR is about `failing-tests or flakes`, please post the related issues/tests in a comment and do not use `Fixes`_*
-->
Fixes #111 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sids-b** [comment]
> @sids-b -Please give permission for the below Application to run coverage report
> https://coveralls.io

@m1093782566 @rohitsardesai83 Sugestions ?? Should we give permissions to this application ??

**Comment by m1093782566** [comment]
@sids-b 

I see no issues?

**Comment by srivatsav123** [comment]
@rohitsardesai83 


image


above is the screenshot of the coverage..It would be like

**Comment by m1093782566** [comment]
Please resolve the conflicts.

**Comment by srivatsav123** [comment]
@m1093782566 @sids-b  -Hi ,have you given the permission for Huawei-ci bot to access https://coveralls.io  ..If permission is not given CI will fail..we have been instructed not to raise PR which will break CI build...If you have given write and read permission for coveralls then only i will resolve the conflicts and push the changes..
thanks

**Comment by m1093782566** [comment]
If we don't resolve the conflicts, let's close this PR.

**Pull request closed without merging**
