### PR TITLE
If system has already docker installed then skip docker installation

### PR DESCRIPTION
**Pull request by naveensriram**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:
If docker of any version is already installed in the system then skip docker installation
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Code developed considering, version of docker installed on the system will be having minimum 2 dots.

### CODE REVIEW

**Comment by subpathdev** [comment]
I like the previous version because the edge_core can not run with every version of docker. (kubeadm v1.15 needed docker version 1.13 and higher)
I think you can do something with regex to check if a minimum version is installed.

**Comment by naveensriram** [comment]
> I like the previous version because the edge_core can not run with every version of docker. (kubeadm v1.15 needed docker version 1.13 and higher)
> I think you can do something with regex to check if a minimum version is installed.

Referring to https://github.com/kubernetes/kubernetes/pull/77051 & https://kubernetes.io/docs/setup/release/notes/?origin_team=TDZ5TGXQW#cluster-lifecycle I also thought of introducing such a check for minimum version of docker required set to 1.13.1. 
But on referring to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#external-dependencies I see docker version 18.03 is not been mentioned under valid versions and also in 1.15 release notes "external dependencies" section is missing which should cover the supported docker version section. In such case is it good to introduce minimum docker version check ? Thoughts @sids-b @rohitsardesai83 @subpathdev

**Comment by subpathdev** [comment]
can you please rebase to the master branch and fix ut?

**Comment by subpathdev** [comment]
> > I like the previous version because the edge_core can not run with every version of docker. (kubeadm v1.15 needed docker version 1.13 and higher)
> > I think you can do something with regex to check if a minimum version is installed.
> 
> Referring to [kubernetes/kubernetes#77051](https://github.com/kubernetes/kubernetes/pull/77051) & https://kubernetes.io/docs/setup/release/notes/?origin_team=TDZ5TGXQW#cluster-lifecycle I also thought of introducing such a check for minimum version of docker required set to 1.13.1.
> But on referring to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#external-dependencies I see docker version 18.03 is not been mentioned under valid versions and also in 1.15 release notes "external dependencies" section is missing which should cover the supported docker version section. In such case is it good to introduce minimum docker version check ? Thoughts @sids-b @rohitsardesai83 @subpathdev @fisherxu

Yes I think we should set a minimum version. I think there will not be a problem with non valid versions because the most people will use their package managing tool (like apt or yum) to install the versions. A non valid version should not be installed via the package managing tool. On the other hand docker should not force to install a non valid version. they should say: install the stable version (if you know what can go wrong you can use the unstable version but this could break your programs / system)

If you want to set the minimum version of docker to 1.13, do you have tested kubeedge with these docker version?

**Comment by naveensriram** [comment]
> > > I like the previous version because the edge_core can not run with every version of docker. (kubeadm v1.15 needed docker version 1.13 and higher)
> > > I think you can do something with regex to check if a minimum version is installed.
> > 
> > 
> > Referring to [kubernetes/kubernetes#77051](https://github.com/kubernetes/kubernetes/pull/77051) & https://kubernetes.io/docs/setup/release/notes/?origin_team=TDZ5TGXQW#cluster-lifecycle I also thought of introducing such a check for minimum version of docker required set to 1.13.1.
> > But on referring to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#external-dependencies I see docker version 18.03 is not been mentioned under valid versions and also in 1.15 release notes "external dependencies" section is missing which should cover the supported docker version section. In such case is it good to introduce minimum docker version check ? Thoughts @sids-b @rohitsardesai83 @subpathdev @fisherxu
> 
> Yes I think we should set a minimum version. I think there will not be a problem with non valid versions because the most people will use their package managing tool (like apt or yum) to install the versions. A non valid version should not be installed via the package managing tool. On the other hand docker should not force to install a non valid version. they should say: install the stable version (if you know what can go wrong you can use the unstable version but this could break your programs / system)
> 
> If you want to set the minimum version of docker to 1.13, do you have tested kubeedge with these docker version?

Thanks @subpathdev for providing insights on this, will validate with docker 1.13 and make add that check.

**Comment by sids-b** [comment]
@naveensriram , can you please resolve the review comments ??

**Pull request closed without merging**
