### PR TITLE
Upgrade to Kubernetes v1.15 and Use gomod

### LINKED ISSUE #748: Change to use gomod to manage the dependencies
**What would you like to be added**:
Use gomod to manage the dependies and remove the vendor from the project

**Why is this needed**:
To manage the dependiences more efficient

### PR DESCRIPTION
**Pull request by edisonxiang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
* Upgrade to Kubernetes v1.15 [@edisonxiang]
* Change to use gomod to manage the dependencies [@subpathdev]

**Which issue(s) this PR fixes**:
Fixes #748 #806

**Special notes for your reviewer**:
Since these two features are related, so @subpathdev is working together with me.
Thanks @subpathdev for the great work.

### CODE REVIEW

**Comment by fisherxu** [comment]
Split to two PR maybe more clear, can change vender to gomod first, @edisonxiang @subpathdev what do you think? :)

**Comment by edisonxiang** [comment]
Thanks @fisherxu we will. Perhaps we can upgrade the k8s version firstly since go mod will depend on that.

**Comment by fisherxu** [comment]
> Perhaps we can upgrade the k8s version firstly since go mod will depend on that

Upgrade the k8s version firstly is also fine, and curious about if we don't upgrade the k8s version, this will block to change gomod?

**Comment by edisonxiang** [comment]
> > Perhaps we can upgrade the k8s version firstly since go mod will depend on that
> 
> Upgrade the k8s version firstly is also fine, and curious about if we don't upgrade the k8s version, this will block to change gomod?

yep. Currently @subpathdev has already finish go mod work based on the upgraded k8s version v1.15.0

**Pull request closed without merging**
