### PR TITLE
add devicemodel update valid check

### PR DESCRIPTION
**Pull request by kadisi**
Signed-off-by: zhangjie <iamkadisi@163.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by chendave** [comment]
@kadisi , Good catch! 

Btw, can we test each of the CI by CLI? 
/retest e2e_test for example?

**Comment by fisherxu** [comment]
/hold
test the bot

**Comment by fisherxu** [comment]
> Btw, can we test each of the CI by CLI?
/retest e2e_test for example?

Now we use the travis CI, it's hard to use the CLI. Maybe then we can switch to prow like k8s. Any idea? @chendave @kadisi

**Pull request merged**
