### PR TITLE
update setup steps in docs.kubeedge.io

### LINKED ISSUE #440: documentation issue for edge_core it must be run as root
**What happened**: There was no connectivity to the k8s cluster when both edgecontroller and edge_core were running.

**What you expected to happen**: The edge-node should of became ready as a node in the cluster

**How to reproduce it (as minimally and precisely as possible)**: Follow the instructions and don't run edge_core as root.

**Anything else we need to know?**: Run edge_core as root for it to work. The documentation when telling you to run edge_core should be done as root. It would be nice for it to bomb out it couldn't get here: 
/var/lib/edged/pods/af7134fb-6c26-11e9-8e3e-00155d6d9c0b/volumes/kubernetes.io~configmap/kube-proxy
It just silently worked and I didn't know why it couldn't work until someone on slack showed me the logging and then it was obvious.

**Environment**:
- KubeEdge version:
- Hardware configuration: 
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1
- Kernel (e.g. `uname -a`): 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others:

### LINKED ISSUE #441: docs: Improve README documentation
**What would you like to be added**:
Suggested improvements in documentation  : 

- [ ] Move https://github.com/kubeedge/kubeedge#roadmap below https://github.com/kubeedge/kubeedge#usage

- [ ] Introduce a section in the https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/usage.md#usage which can show how to download a kubeedge release ( e.g v0.2) and run.
Users might just want to try running kubeedge without building from source.

- [ ] Running the cloud [ https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/usage.md#run-cloud ] should first show how to run as a binary and then how to run using K8S deployments. Similarly for edge.

- [ ]  Explicitly specify to run edge component as root user #440 

**Why is this needed**:
To make it easier for community to get started with KubeEdge.

### PR DESCRIPTION
**Pull request by edisonxiang**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
update setup steps in docs.kubeedge.io

Which issue(s) this PR fixes:
Partial Fixes #441
Fixes #440

### CODE REVIEW

**Comment by sids-b** [comment]
@edisonxiang , usage.md and setup.md are the same. Can we give links to one another so that we dont have edit same information in 2 places when there is change in setup steps ? I think usage.md is not showing in docs.kubeedge.io ?? cc @anvithks

**Comment by edisonxiang** [comment]
@sids-b yep. They are almost same.
Just some difference like this
https://github.com/kubeedge/kubeedge/pull/470/files#diff-b3dfdeb3914e756a471a737d21980db4R128

You know we are using `md` in github repository but `html` in website.

I guess it is better to add the website contents into
https://github.com/kubeedge/website

Any ideas?

**Comment by sids-b** [comment]
We are already discussing it. Please have a look at #288 and share your thought there :)

**Comment by edisonxiang** [comment]
@sids-b comments left at #288 
The file `usage.md` will be always exist in kubeedge/kubeedge repository.
The file `setup.md` will be moved somewhere like kubeedge/website in future.
Currently these two files are useful for github repo and website separately .
Could we keep these two files in current version?

**Comment by sids-b** [comment]
yes, I think for this version it's fine. But later we need to have it only in 1 place.

**Comment by rohitsardesai83** [comment]
@edisonxiang , I have mentioned some tasks for doc improvement in #441 . Is it possible for you take a look and resolve some of these as a part of this PR ? Please let me know which subtasks from that issue we can fix and then we can mark those resolved in that issue once addressed.

**Comment by edisonxiang** [comment]
- [x] Move https://github.com/kubeedge/kubeedge#roadmap below https://github.com/kubeedge/kubeedge#usage

- [x] Running the cloud [ https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/usage.md#run-cloud ] should first show how to run as a binary and then how to run using K8S deployments. Similarly for edge.

- [x]  Explicitly specify to run edge component as root user #440

**Comment by edisonxiang** [comment]
Hi @rohitsardesai83 3/4 of #441 are fixed in this pr.

- [ ] Introduce a section in the https://github.com/kubeedge/kubeedge/blob/master/docs/getting-started/usage.md#usage which can show how to download a kubeedge release ( e.g v0.2) and run.
Users might just want to try running kubeedge without building from source.

About this one, I think we can firstly close #441 and #440 and then turn to #447 
What do you think about that?

**Pull request merged**
