### PR TITLE
Add volume downwardAPI and projected

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test

/kind feature

**What this PR does / why we need it**:
These two type of volume are widely used, need to add them.
**TODO:** we need add the test for all the volumes now

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sids-b** [comment]
Thanks @fisherxu 

/approve

**Comment by kevin-wangzefeng** [comment]
TODO: We need a plan to reuse e2e tests from upstream to help check functionalities like this one; and add them to the PR checks.

**Comment by fisherxu** [comment]
> TODO: We need a plan to reuse e2e tests from upstream to help check functionalities like this one; and add them to the PR checks.

Have open an issue #1101 to track

**Comment by edisonxiang** [comment]
/lgtm

Thanks @fisherxu

**Pull request merged**
