### PR TITLE
re-organize documents

### PR DESCRIPTION
**Pull request by m1093782566**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
re-organize documents

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
```
NONE
```

### CODE REVIEW

**Comment by sids-b** [comment]
@m1093782566 Can we create common folder and place beehive in it as it i used in both edge and cloud ?

**Comment by m1093782566** [comment]
Create too deep folder may not be a good ieda.

**Comment by sids-b** [comment]
@anvithks , can you please verify if this placement is okay for docs website ? so that we can goahead and merge this one

**Comment by anvithks** [comment]
This placement will break the documentation on the docs site. If you are changing the folder structure then please change all the links within documents as well. Till then please hold on merging this PR.

**Comment by anvithks** [comment]
You will have to update the index.rst file as well as all links within the individual documents where there is a reference.

**Comment by anvithks** [comment]
@m1093782566 Please provide me with write access to your reorg-doc branch. I will add the fixes needed for this change.

**Comment by anvithks** [comment]
@m1093782566 @sids-b Please review and merge this.

**Pull request merged**
