### PR TITLE
Make device/bluetooth_mapper

### PR DESCRIPTION
**Pull request by subpathdev**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
All parts on the master branch should buildable.
This will also add lint checks and go vet checks to the device/bluetooth_mapper part.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
I have to change parts to run successfully "golangcli-lint" and "go vet".

### CODE REVIEW

**Comment by subpathdev** [comment]
@sujithsimon22
I have fixed all lint problems but one go vet problem is still there. My question is how should I fix this:
>go/src/github.com/kubeedge/kubeedge/device/bluetooth_mapper/watcher/watcher.go:131:6: Infof format %s has arg helper.TwinResult.Twin[twinAttribute.Name].Actual of wrong type *github.com/kubeedge/kubeedge/device/bluetooth_mapper/helper.TwinValue

TwinValue is here always nil so I set it static or I replace %s with %v. (I like the second one but I am not sure about this)

**Comment by sujithsimon22** [comment]
> @sujithsimon22
> I have fixed all lint problems but one go vet problem is still there. My question is how should I fix this:
> 
> > go/src/github.com/kubeedge/kubeedge/device/bluetooth_mapper/watcher/watcher.go:131:6: Infof format %s has arg helper.TwinResult.Twin[twinAttribute.Name].Actual of wrong type *github.com/kubeedge/kubeedge/device/bluetooth_mapper/helper.TwinValue
> 
> TwinValue is here always nil so I set it static or I replace %s with %v. (I like the second one but I am not sure about this)

@subpathdev The second option sounds better to me as well :) I think it is better if we replace %s with %v

**Comment by subpathdev** [comment]
> > @sujithsimon22
> > I have fixed all lint problems but one go vet problem is still there. My question is how should I fix this:
> > > go/src/github.com/kubeedge/kubeedge/device/bluetooth_mapper/watcher/watcher.go:131:6: Infof format %s has arg helper.TwinResult.Twin[twinAttribute.Name].Actual of wrong type *github.com/kubeedge/kubeedge/device/bluetooth_mapper/helper.TwinValue
> > 
> > 
> > TwinValue is here always nil so I set it static or I replace %s with %v. (I like the second one but I am not sure about this)
> 
> @subpathdev The second option sounds better to me as well :) I think it is better if we replace %s with %v

@sujithsimon22 
thanks

**Comment by sids-b** [comment]
/lgtm

Thanks @subpathdev

**Pull request merged**
