### PR TITLE
fix mutex unlock

### PR DESCRIPTION
**Pull request by cl2017**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
We need to unlock the mutex after the loop ends, instead of defining defer when function ends.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wbc6080** [comment]
It is indeed better to change this way
lgtm

**Review by fisherxu — COMMENTED** [review]
Looks good, and just curious any bugs will it cause?
/approve

**Comment by cl2017** [comment]
> Looks good, and just curious any bugs will it cause? /approve

it might be, because `CreateDMIClient` will use another mutex, which can cause blocking in some cases

**Review by fisherxu — COMMENTED** [review]
> it might be, because CreateDMIClient will use another mutex, which can cause blocking in some cases

Ok, so we should cherry-pick it to the release branchs.

**Pull request merged**
