### PR TITLE
fix resource version compare error

### PR DESCRIPTION
**Pull request by threestoneliu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Fix resource version compare error! we need to use objectSync.Status.ObjectResourceVersion instandof objectSync.ResourceVersion

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
lgtm

**Comment by threestoneliu** [comment]
@daixiang0  please review again, add  objectSync.Status.ObjectResourceVersion != ""  judgement condition. In some case, objectSync.Status will be empty when we use kubectl get objectsyncs <nodename.objectid> -oyaml, so we need to avoid strconv.ParseUint error.

**Comment by fisherxu** [comment]
> @daixiang0 please review again, add objectSync.Status.ObjectResourceVersion != "" judgement condition. In some case, objectSync.Status will be empty when we use kubectl get objectsyncs <nodename.objectid> -oyaml, so we need to avoid strconv.ParseUint error.

@threestoneliu Looks good, if objectSync.Status.ObjectResourceVersion == "", we can send the object. For the reason of objectSync.Status.ObjectResourceVersion == "", it's because here https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudhub/handler/messagehandler.go#L547, we create it first, then update the status, so the status can be empty, and do you have any error logs like `Failed to get objectSync` or `Failed to update objectSync` in cloud?

**Comment by fisherxu** [comment]
@threestoneliu Can you please cherry-pick it to release-1.5 branch?

**Comment by threestoneliu** [comment]
> @threestoneliu Can you please cherry-pick it to release-1.5 branch?

have done！[2376](https://github.com/kubeedge/kubeedge/pull/2376)

**Pull request merged**
