### PR TITLE
Test coverage for `cloud/pkg/dynamiccontroller` module

### PR DESCRIPTION
**Pull request by 1Shubham7**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

I have added unit tests for the `cloud/pkg/dynamiccontroller` module

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by wbc6080 — COMMENTED** [review]
Container runtime CI failed have been fixed in #5800. You can rebase the latest code to pass these test

**Review by wbc6080 — COMMENTED** [review]
It looks like you made some unrelated changes when rebase?
image

**Comment by 1Shubham7** [comment]
@WillardHu please review this one as well :)

**Pull request merged**
