### PR TITLE
implement ipv6 valid logic and typo fix

### PR DESCRIPTION
**Pull request by soolaugust**
**What type of PR is this?**

> /kind feature

**What this PR does / why we need it**:
fix typo and implement ipv6 valid logic in shell

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by subpathdev** [comment]
please squash the commits. (you could use `git rebase -i HEAD^^^`)

**Comment by soolaugust** [comment]
@subpathdev done, please check

**Pull request merged**
