### PR TITLE
fix fuzzer extract message error

### PR DESCRIPTION
**Pull request by vincentgoat**
Signed-off-by: vincentgoat <linguohui1@huawei.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
To address the [oss-fuzz issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47779)

cc @AdamKorcz

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
keadm e2e fails just as https://github.com/kubeedge/kubeedge/pull/3894#issuecomment-1144536492

**Comment by vincentgoat** [comment]
image
Check build passed.

**Comment by gy95** [comment]
please rebase the upstream master to fix CI :) @vincentgoat

**Comment by vincentgoat** [comment]
> please rebase the upstream master to fix CI :) @vincentgoat

Thanks. Done

**Comment by fisherxu** [comment]
> > image Check build passed.
> 
> From the OSS-Fuzz side, LGTM.

Is it needed to have the check in CI? cc @vincentgoat @AdamKorcz

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
