### PR TITLE
[WIP] test: add arm64 arch support

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**

Add one of the following kinds:

/kind feature
/kind test

/kind failing-test

**What this PR does / why we need it**:

From [travis blog](https://blog.travis-ci.com/2020-09-11-arm-on-aws), only `virt: vm` tag can not enable arm64 feature, need `group` tag too.

Also from [CI log](https://travis-ci.org/github/kubeedge/kubeedge/jobs/736281853#L470-L494), it stills run on amd64 machine.

`kind` can not run well at arm64, so use `minikube` instead.

### CODE REVIEW

**Comment by daixiang0** [comment]
Now miniube latest support k8s version is 1.19.2 which is used as default.

**Comment by daixiang0** [comment]
Check [doc](https://docs.travis-ci.com/user/multi-cpu-architectures/#multi-cpu-availaibility), we need to switch to `com`.

/cc @kevin-wangzefeng please refer to [doc](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository ) to migrate from `org` to `com`.

**Comment by daixiang0** [comment]
Now only e2e on arm64 vm fails, it needs more time to dig into root cause, so implement it in other pr.

**Comment by kevin-wangzefeng** [comment]
According to the latest travis-ci billing model, we will need credits after moved to travis-ci.com
Maybe we can just move x86 CI jobs to other platform, and keep all the travis-ci credits for arm env validations.

Ref: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by daixiang0** [comment]
switch to GITHUB, abort it.

**Pull request closed without merging**
