### PR TITLE
update workflow to 1.27.7

### PR DESCRIPTION
**Pull request by wbc6080**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
upgrade kubernetes dependency version 1.27.7 in workflow with #5121 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
SGTM. 
I'm wondering if it would be better to update other kubernetes versions to the latest patch version available, although this may not affect the test results.

**Comment by fisherxu** [comment]
We can update to the latest version, which is the tag of `kindest/node:${{ matrix.version }}` here, you should check the tag of `kindest/node` in dockerhub.

**Comment by wbc6080** [comment]
I have corrected it @Shelley-BaoYue @fisherxu

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
