### PR TITLE
update the setup docs about configuration file, and clean the old configuration files

### PR DESCRIPTION
**Pull request by kuramal**
Signed-off-by: kuramal <linxxnil@126.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind cleanup
/kind documentation

**What this PR does / why we need it**:
The configuration of kubeedge has changed， delete the old configuration files
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by kadisi** [comment]
/lgtm 

we need a new pr to change [setup.md](https://github.com/kubeedge/kubeedge/blob/master/docs/setup/setup.md) file. 

#1171

**Comment by bitvijays** [comment]
@kadisi Could you please wait to create a new PR for the documentation (If that's fine)?. I have created a PR for the documentation restructure. https://github.com/kubeedge/kubeedge/pull/1366 . Once this is accepted, it would be great to directly update the documentation in the new files.

**Comment by fisherxu** [comment]
+1, please update the setup docs.

**Comment by kuramal** [comment]
@fisherxu I will update the setup docs at another pr,  and @bitvijays  is restructure the docs. Cloud I update the setup docs after that.

**Comment by fisherxu** [comment]
> @bitvijays is restructure the docs. Cloud I update the setup docs after that.

you just change it first, thanks :)

**Comment by fisherxu** [comment]
/lgtm
Good job!

**Pull request merged**
