### PR TITLE
update DefaultKubeEdgeVersion

### PR DESCRIPTION
**Pull request by wlq1212**
Signed-off-by: wlq <806646991@qq.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
update default version to 1.12.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
@wlq1212 The DCO test seems failed now, ptal

**Comment by liyuerich** [comment]
@wlq1212 
it seems you have the incorrect sign-off. please correct it.
Commit sha: [bd45e7e](https://github.com/kubeedge/kubeedge/pull/4286/commits/bd45e7e7f0f66396410230992ddb54b479e8c7cf), Author: wlq1212, Committer: wlq1212; Expected "wlq1212 [liqing.wu@daocloud.io](mailto:liqing.wu@daocloud.io)", but got "wlq [806646991@qq.com](mailto:806646991@qq.com)".

**Review by fisherxu — COMMENTED** [review]
/approve
/cc @gy95 ptal

**Pull request merged**
