### PR TITLE
Migrate the kubeedge api to staging and modify the method to refer api

### PR DESCRIPTION
**Pull request by wbc6080**
**What type of PR is this?**
/kind feature
/kind api-change

**What this PR does / why we need it**:
Migrate the original kubeedge api to the staging directory, create a new api repo to store the api, and synchronize the modifications to the staging directory. After completion, the user can directly access the api repo by referencing the kubeedge api without referencing the entire kubeedge.
**Which issue(s) this PR fixes**:

A part of #5474

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by wbc6080 — COMMENTED** [review]
Ready to be reviewed.
@WillardHu @fisherxu @Shelley-BaoYue

**Comment by WillardHu** [comment]
It's a big merger that could cause a lot of conflict, so maybe we should let everyone know at a community meeting

**Comment by fisherxu** [comment]
> It's a big merger that could cause a lot of conflict, so maybe we should let everyone know at a community meeting

+1, and I think the auto-generated client codes could be moved to api repo as well, ptal @WillardHu

**Comment by WillardHu** [comment]
> +1, and I think the auto-generated client codes could be moved to api repo as well, ptal @WillardHu

Sounds good.

**Comment by wbc6080** [comment]
Okay, we can discuss this at the meeting tomorrow afternoon

**Comment by wbc6080** [comment]
Ready to be reviewed.
@WillardHu @fisherxu @Shelley-BaoYue

**Review by fisherxu — COMMENTED** [review]
/lgtm

And now the dir structure is api/apis, not sure what was the conclusion of the last meeting ;-)  api/apis or apis/api, but all look good.

Leave @WillardHu @Shelley-BaoYue for final review :)

**Pull request merged**
