### PR TITLE
fix: mqtt broker was not deleted when it run failed

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The MQTT broker was not deleted when it run failed. When MQTT broker run failed for some reasons, the `docker ps` command cannot find container of mqtt, and it need to add the `-a` flag to find it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
cc @gy95

**Review by gy95 — APPROVED** [review]
/lgtm

**Comment by fisherxu** [comment]
@gy95  Seems the `Keadm deprecated e2e test` always failed, ptal :)

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
