### PR TITLE
join node cancels pause images

### PR DESCRIPTION
**Pull request by wlq1212**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
join node cancels pause images

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubeedge/kubeedge/issues/5309

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wlq1212** [comment]
cc @ZhengXinwei-F @WillardHu

**Comment by ZhengXinwei-F** [comment]
lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
