### PR TITLE
Bump k8s 1.26.7

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Update Kubernetes dependency version to v1.26.7

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
/approve
The fuzzing test is not required, and once the PR merged, I will set the K8s verion in github action.

**Comment by fisherxu** [comment]
/assign @WillardHu 
For final review :)

**Comment by WillardHu** [comment]
/lgtm

The historical code has some functions in the pkg package that use `exit` to handle error. In the future, we can see if we can use `panic` instead. The `exit` operation is non-interruptible and cannot be unit tested.

**Comment by fisherxu** [comment]
> The historical code has some functions in the pkg package that use exit to handle error. In the future, we can see if we can use panic instead. The exit operation is non-interruptible and cannot be unit tested.

Can you open an issue to track it? @WillardHu

**Comment by WillardHu** [comment]
> > The historical code has some functions in the pkg package that use exit to handle error. In the future, we can see if we can use panic instead. The exit operation is non-interruptible and cannot be unit tested.
> 
> Can you open an issue to track it? @WillardHu

OK 
https://github.com/kubeedge/kubeedge/issues/5012

**Pull request merged**
