### PR TITLE
adjust nsswitch configuration to fix dns lookup error

### LINKED ISSUE #2647: Streaming server stopped unexpectedly
**What happened and what you expected to happen**:
Edgecore Streaming server stopped unexpectedly: listen tcp: lookup localhost: device or resource busy

**How to reproduce it (as minimally and precisely as possible)**:
Install edgecore by keadm:
```
./keadm
Host has mosquit+ already installed and running. Hence skipping the installation steps !!!
Expected or Default KubeEdge version 1.6.0 is already downloaded and will checksum for it.
kubeedge-v1.6.0-linux-amd64.tar.gz checksum:
checksum_kubeedge-v1.6.0-linux-amd64.tar.gz.txt content:
Expected or Default KubeEdge version 1.6.0 is already downloaded
[Run as service] service file already exisits in /etc/kubeedge//edgecore.service, skip download
kubeedge-v1.6.0-linux-amd64/
kubeedge-v1.6.0-linux-amd64/edge/
kubeedge-v1.6.0-linux-amd64/edge/edgecore
kubeedge-v1.6.0-linux-amd64/cloud/
kubeedge-v1.6.0-linux-amd64/cloud/csidriver/
kubeedge-v1.6.0-linux-amd64/cloud/csidriver/csidriver
kubeedge-v1.6.0-linux-amd64/cloud/admission/
kubeedge-v1.6.0-linux-amd64/cloud/admission/admission
kubeedge-v1.6.0-linux-amd64/cloud/cloudcore/
kubeedge-v1.6.0-linux-amd64/cloud/cloudcore/cloudcore
kubeedge-v1.6.0-linux-amd64/version

KubeEdge edgecore is running, For logs visit: journalctl -u edgecore.service -b
```
Get logs as below:
```

Mar 17 17:28:21 i-53dc6evc systemd[1]: Started edgecore.service.
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: INFO: Install client plugin, protocol: rest
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: INFO: Installed service discovery plugin: edge
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.163085    5607 server.go:72] Version: v1.6.0
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.167743    5607 sql.go:21] Begin to register twin db model
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.167885    5607 module.go:34] Module twin registered successfully
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.178043    5607 client.go:77] Connecting to docker on unix:///var/run/docker.sock
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.178065    5607 client.go:94] Start docker client with request timeout=0s
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.190914    5607 docker_service.go:241] Hairpin mode set to "hairpin-veth"
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: W0317 17:28:21.190998    5607 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: W0317 17:28:21.194059    5607 hostport_manager.go:71] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: W0317 17:28:21.194078    5607 hostport_manager.go:71] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.195356    5607 docker_service.go:256] Docker cri networking managed by kubernetes.io/no-op
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.207048    5607 docker_service.go:261] Docker Info: &{ID:KWNS:35SL:NDYC:SWZL:CDKG:MKQU:FUYE:NZYO:OHYG:FTPE:JY22:FFBG Containers:0 ContainersRunning:0 C
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.207114    5607 docker_service.go:274] Setting cgroupDriver to cgroupfs
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.207226    5607 edged.go:517] RemoteRuntimeEndpoint: "unix:///var/run/dockershim.sock", remoteImageEndpoint: "unix:///var/run/dockershim.sock"
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: I0317 17:28:21.207248    5607 edged.go:520] Starting the GRPC server for the docker CRI shim.
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: F0317 17:28:21.209154    5607 docker_service.go:416] Streaming server stopped unexpectedly: listen tcp: lookup localhost: device or resource busy
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: goroutine 145 [running]:
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: k8s.io/klog/v2.stacks(0xc000128001, 0xc0001ac3c0, 0x92, 0xa0)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: k8s.io/klog/v2.(*loggingT).output(0x4f88f00, 0xc000000003, 0x0, 0x0, 0xc0004230a0, 0x4c48024, 0x11, 0x1a0, 0x0)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:945 +0x191
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: k8s.io/klog/v2.(*loggingT).printf(0x4f88f00, 0x3, 0x0, 0x0, 0x37ddbc5, 0x29, 0xc00008ffb8, 0x1, 0x1)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: k8s.io/klog/v2.Fatalf(...)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1456
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).Start.func1(0xc0002643c0)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_service.go:416 +0xc5
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: created by k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).Start
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_service.go:414 +0x86
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: goroutine 1 [select]:
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: net/http.(*persistConn).roundTrip(0xc000b89e60, 0xc000b17a00, 0x0, 0x0, 0x0)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/.gvm/gos/go1.15/src/net/http/transport.go:2565 +0x779
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: net/http.(*Transport).roundTrip(0xc00037f180, 0xc000b90200, 0x30, 0xc0006ad830, 0x7f89400d61a0)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/.gvm/gos/go1.15/src/net/http/transport.go:582 +0xa65
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: net/http.(*Transport).RoundTrip(0xc00037f180, 0xc000b90200, 0xc00037f180, 0x0, 0x0)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/.gvm/gos/go1.15/src/net/http/roundtrip.go:17 +0x35
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: net/http.send(0xc000b90200, 0x3b261a0, 0xc00037f180, 0x0, 0x0, 0x0, 0xc0006574d0, 0x80, 0x1, 0x0)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/.gvm/gos/go1.15/src/net/http/client.go:252 +0x453
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: net/http.(*Client).send(0xc000417a40, 0xc000b90200, 0x0, 0x0, 0x0, 0xc0006574d0, 0x0, 0x1, 0xf8)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/.gvm/gos/go1.15/src/net/http/client.go:176 +0xff
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: net/http.(*Client).do(0xc000417a40, 0xc000b90200, 0x0, 0x0, 0x0)
Mar 17 17:28:21 i-53dc6evc systemd[1]: edgecore.service: main process exited, code=exited, status=255/n/a
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/.gvm/gos/go1.15/src/net/http/client.go:718 +0x45f
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: net/http.(*Client).Do(...)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/.gvm/gos/go1.15/src/net/http/client.go:586
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: github.com/docker/docker/client.(*Client).doRequest(0xc0001f9480, 0x3ba9d80, 0xc000b593e0, 0xc000b90100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/docker/docker/client/request.go:134 +0x158
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: github.com/docker/docker/client.(*Client).sendRequest(0xc0001f9480, 0x3ba9d80, 0xc000b593e0, 0x377d02d, 0x3, 0x377e598, 0x5, 0xc00052c7e0, 0x0, 0x0, ...)
Mar 17 17:28:21 i-53dc6evc edgecore[5607]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/docker/docker/client/request.go:122 +0x159


```
**Anything else we need to know?**:
os:Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020
docker version: 20.10.5
**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.9
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.6.0

As mentioned [here](https://github.com/kubeedge/kubeedge/blob/master/docs/contributing/edgemesh_guide.md), we need to set the configuration  below if we want to use edgemesh:
```
root@i-6hrk1pfm:~# cat /etc/nsswitch.conf |grep hosts
hosts:          dns file mdns4_minimal [NOTFOUND=return] # check `file` here
```
Actually, on this centos system, i have to modify the configuration like this:
```
[root@i-53dc6evc ~]# cat /etc/nsswitch.conf|grep hosts
hosts:      dns files mdns4_minimal [NOTFOUND=return] # check `files` here
```
If we don't apply this change, it would bring in a huge error by executing `nslookup localhost `. However, on anthor ubuntu os of my machines, the corresponding configuration have not changed. They all work normally.  Is this caused by differences in operating systems?

### PR DESCRIPTION
**Pull request by zhu733756**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
As metioned at #2647, if we don't apply this change, it would bring in a huge error by executing `nslookup localhost `, and the edgecore would not  start properly on some operating system.

**Which issue(s) this PR fixes**:

To fix #2647

**Special notes for your reviewer**:
A description mentioned [here](https://en.wikipedia.org/wiki/Name_Service_Switch#nsswitch.conf)

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
DCO check is failing, please add `Signed-off-by: Your name <your email>` in your commit message.
Ref: https://probot.github.io/apps/dco/

**Comment by zhu733756** [comment]
> DCO check is failing, please add `Signed-off-by: Your name <your email>` in your commit message.
> Ref: https://probot.github.io/apps/dco/

Thanks, i just force-pushed by add "-s" in git.

**Comment by fisherxu** [comment]
Streamingserver in Edged should not depend on the edgemesh, will native kubelet run failed in this panic without this path?

**Comment by fisherxu** [comment]
@zhu733756

**Comment by zhu733756** [comment]
@fisherxu  Even in a fresh centos system,  I set the default configuration by `hosts:      dns file mdns4_minimal [NOTFOUND=return]
`, then executing `ping localhost`, it returns:
```
[root@i-fotnposv ~]# ping localho
ping: localhost: System error
```
This caused the error at #2647

**Comment by daixiang0** [comment]
As https://github.com/kubeedge/kubeedge/issues/2647#issuecomment-804512328 said, we should consider how to improve compatibility.

Also, now all docs have moved to kubeedge/website, so all changes should post there.

This change is ok for me, maybe we can mark this config as optional.

/close

**Pull request closed without merging**
