### PR TITLE
Revert ginkgo from v2 to v1

### PR DESCRIPTION
**Pull request by wackxu**
**What type of PR is this?**

/kind cleanup
**What this PR does / why we need it**:

revert https://github.com/kubeedge/kubeedge/pull/3835

We have direct and many dependencies on the k8s repository. We should keep the relevant dependency package version consistent with the k8s version. If it is inconsistent, it will bring some management and usage problems.

The ginkgo version bump to v2 in k8s 1.25, so we should bump ginkgo when we bump k8s to 1.25. 

If we do not do so, we can not execute kubeedge e2e and k8s e2e together

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by gy95 — APPROVED** [review]

**Comment by wackxu** [comment]
cc @vincentgoat @fisherxu PTAL

**Review by vincentgoat — COMMENTED** [review]
/lgtm cc @fisherxu

**Comment by wackxu** [comment]
cc @fisherxu

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
