### PR TITLE
Edgesiteimprov

### LINKED ISSUE #531: Consolidate the controller code for kubeedge edgenode and edgesite
**What happened**:
Currently we dup-ed controller code for edgenode and edgesite. 

**What you expected to happen**:
To enable code reuse, we should remove the un-necessary redundancy and prevent too many branching in the code. 

The proposal is to keep the controller/manager code for edge and edgesite where edgesite will query pod/configmap/secret metadata specifically for the node; and edge code will query all but route the message to different nodes. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by samy2019**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes duplicated controller code for edgesite.

**Which issue(s) this PR fixes**:
Fixes #531

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sids-b** [comment]
The overall change looks great. We are removing lot of duplicate code.... Lets fix the CI issues.

**Comment by m1093782566** [comment]
@samy2019 Squash commits please.

**Comment by samy2019** [comment]
@CindyXing, Please review the code. The conflicts are due merge of other PR's to master. They shall be resolved. Request you to review the original changes in this PR.

**Comment by samy2019** [comment]
Closing this PR as new PR #629 is created, due to code conflicts.

**Pull request closed without merging**
