### PR TITLE
added edge node role label while running installer

### LINKED ISSUE #643: KubeEdge didn't add a role label while creating a node
**What happened**:
Kubedge Installer didn't add the role label while creating a node.

**What you expected to happen**:
KubeEdge installer should add the role as edge for a node

**How to reproduce it (as minimally and precisely as possible)**:
run kubeedge join

**Anything else we need to know?**:
The addition of role has become mandatory as KubeEdge uses role to differentiate between edge nodes and other nodes.
XREF : #244 #294

### PR DESCRIPTION
**Pull request by sids-b**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR adds role label while creating a node in kubeedge installer code 

**Which issue(s) this PR fixes**:
Fixes #643

### CODE REVIEW

**Comment by sids-b** [comment]
@samy2019 @srivatsav123 , please let me know if we need to add this label in any other place. I will take care of it in this PR

**Comment by samy2019** [comment]
@sids-b , Only 2 places to change where node json is created.

**Pull request merged**
