### PR TITLE
initialize OWNERS file for KubeEdge installer

### PR DESCRIPTION
**Pull request by sids-b**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
initialize owners file for kubeedge installer. For supporting the review process for adding code in installer

**Which issue(s) this PR fixes**:
XREF #638

### CODE REVIEW

**Comment by subpathdev** [comment]
we should resolve the ci issue in another pr

**Comment by sids-b** [comment]
@subpathdev , I just added another commit to fix the govet issue orelse the bot cannot merge the PR

**Pull request merged**
