### PR TITLE
Edgemesh dev

### PR DESCRIPTION
**Pull request by Arcanique**
…,including init container mirroring tools.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind feature

**What this PR does / why we need it**:
>
> In the edgemesh scenario, implement application traffic hijacking which contain DNS inqury using init container and iptables tecnology and contains the init container image creation script containing the Dockerfile for deb and rpm. Currently supports scenarios which the POD and the host's network namespace are isolated (for example, container networks such as bridges and flannels). We support IPv4 messages now .
>

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sids-b** [comment]
@Arcanique , can you please fix the CI ?

**Comment by sids-b** [comment]
@Arcanique please use dep to update the vendor packages. https://github.com/golang/dep

**Comment by Arcanique** [comment]
> @Arcanique please use dep to update the vendor packages. https://github.com/golang/dep

ok，I will do that，thx！

**Pull request closed without merging**
