### PR TITLE
fix print information error of keadm version

### PR DESCRIPTION
**Pull request by yushanjin**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug

**What this PR does / why we need it**:
fix print information error of keadm version
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
Thanks for the fixing @yushanjin , and would you like to add your email which used in the commit to your github [emails](https://github.com/settings/emails)? Or we can't count your contributions.
image

**Comment by yushanjin** [comment]
> Thanks for the fixing @yushanjin , and would you like to add your email which used in the commit to your github [emails](https://github.com/settings/emails)? Or we can't count your contributions.
> image

ok

**Comment by fisherxu** [comment]
/lgtm
/approve

Although the email address has not been configured :)

**Pull request merged**
