### PR TITLE
use constants.MessageSuccessfulContent replace magic number 'OK'

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
We have other places that use the "OK", could you please search and replace all of them?

**Comment by WillardHu** [comment]
@fisherxu  fixed

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
