### PR TITLE
Modify the process for err in metaserver

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
Signed-off-by: Shelley-BaoYue <baoyue2@huawei.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Error in metaserver request processing should not cause edgecore to crash, so `panic(err)` is not appropriate here.

### CODE REVIEW

**Review by vincentgoat — COMMENTED** [review]
image
There are still functions `utilruntime.Must(err)` in module MetaServer, should these be fixed?

**Comment by Shelley-BaoYue** [comment]
> image There are still functions `utilruntime.Must(err)` in module MetaServer, should these be fixed?

Done.

**Review by vincentgoat — COMMENTED** [review]
lgtm

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
