### PR TITLE
fix edgemesh caching serviceList bug

### PR DESCRIPTION
**Pull request by liuzhiyi1993**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug

**What this PR does / why we need it**:
There is a bug inside edgemesh when caching serviceList. When edgemesh tries to cache a serviceList, say {svc1, svc2, svc3}, it would cache them like {svc1Key, svc3Addr}, {svc2Key, svc3Addr}, {svc3Key, svc3Addr}. This bug came from incorrect usage of "slice" of golang. This PR would fix the bug and make it like {svc1Key, svc1Addr}, {svc2Key, svc2Addr}, {svc3Key, svc3Addr}. 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: NONE

```release-note

```

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
Please describe details about the bug and add testcases to cover the scenario, thanks.

**Comment by liuzhiyi1993** [comment]
> Please describe details about the bug and add testcases to cover the scenario, thanks.

done

**Pull request merged**
