### PR TITLE
add dependabot

### PR DESCRIPTION
**Pull request by fengshunli**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
/cc @gy95

**Comment by gy95** [comment]
what's this used for? @fengshunli could you please provide more details or description :)

**Comment by fengshunli** [comment]
> what's this used for? @fengshunli could you please provide more details or description :)

Automatically update dependent packages

**Comment by vincentgoat** [comment]
IMO, the 3rd-party dependence is complex in kubeedge project and the dependabot can't upgrade the package version smoothly.

**Comment by fengshunli** [comment]
> IMO, the 3rd-party dependence is complex in kubeedge project and the dependabot can't upgrade the package version smoothly. Many PRs will be launched frequently.

Yes, many projects are realized by robots @vincentgoat

**Pull request closed without merging**
