### PR TITLE
delete ServiceBus.Enable's tag omitempty

### PR DESCRIPTION
**Pull request by kuramal**
Signed-off-by: kuramal <linxxnil@126.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
 /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:
Set the describe of ServiceBus.Enable to false.,because default config is set to false at the init func NewDefaultEdgeCoreConfig()
Delete the ServiceBus.Enable's omitempty attribute, it shoud be displayed when not config

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by kadisi** [comment]
why need to delete `omitempty ` json tag?

**Comment by kuramal** [comment]
> why need to delete `omitempty ` json tag?

If tag omitempty is set, when show edgecore's default config with command 'edgecore --defaultconfig', the display of servicebus is as follows:
```
  servicebus: {}
```
the display of servicebus without servicebus.enable's tag omitempty:
```
  servicebus:
    enable: false
```

**Comment by kevin-wangzefeng** [comment]
Having omitempty or not would simply affect the boolean fields be shown or not when set default to false.
The essential question is whether show to user that servicebus is disabled by default.
We can actually turn the default value to true after cloud functionality of servicebus complete

**Comment by kevin-wangzefeng** [comment]
> Having omitempty or not would simply affect the boolean fields be shown or not when set default to false.
> The essential question is whether show to user that servicebus is disabled by default.
> We can actually turn the default value to true after cloud functionality of servicebus complete

Pobably make serviceBus explicitly shown false by default, and later on when turning it default to true, we can make it not explicitly shown.

**Comment by kevin-wangzefeng** [comment]
And DBTest is in the same situation, please remove the "omitempty" as well.

**Pull request merged**
