### PR TITLE
update kubeedge release version

### PR DESCRIPTION
**Pull request by wenchajun**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

```
In release1.13, version 1.13 was released but the corresponding version did not change. Is this intentional or an omission?
```

**Does this PR introduce a user-facing change?**:

```release-note
release-1.13
```

### CODE REVIEW

**Comment by wenchajun** [comment]
@zhu733756 @fisherxu @benjaminhuo pls take a look

**Comment by benjaminhuo** [comment]
@fisherxu KubeEdge v1.13.0 publish new images for cloudcore only, but there are no v1.13.0 images for `iptable-manager` and `controller manager`, I think we need new images for all these three components:

https://hub.docker.com/r/kubeedge/cloudcore/tags
https://hub.docker.com/r/kubeedge/controller-manager/tags
https://hub.docker.com/r/kubeedge/iptables-manager/tags

**Comment by zhu733756** [comment]
Yes, Using Ci to publish them is a good way. @wenchajun @benjaminhuo @fisherxu

**Comment by fisherxu** [comment]
> @fisherxu KubeEdge v1.13.0 publish new images for cloudcore only, but there are no v1.13.0 images for `iptable-manager` and `controller manager`, I think we need new images for all these three components？:
> 
> https://hub.docker.com/r/kubeedge/cloudcore/tags https://hub.docker.com/r/kubeedge/controller-manager/tags https://hub.docker.com/r/kubeedge/iptables-manager/tags

@gy95 please take a look, thanks :)

**Comment by gy95** [comment]
> > @fisherxu KubeEdge v1.13.0 publish new images for cloudcore only, but there are no v1.13.0 images for `iptable-manager` and `controller manager`, I think we need new images for all these three components？:
> > https://hub.docker.com/r/kubeedge/cloudcore/tags https://hub.docker.com/r/kubeedge/controller-manager/tags https://hub.docker.com/r/kubeedge/iptables-manager/tags
> 
> @gy95 please take a look, thanks :)

there's something wrong in release script, publish image to `iptablesmanager` and `controllermanager` but not `iptables-manager` and `controller-manager`

**Comment by wenchajun** [comment]
> 



> > > @fisherxu KubeEdge v1.13.0 publish new images for cloudcore only, but there are no v1.13.0 images for `iptable-manager` and `controller manager`, I think we need new images for all these three components？:
> > > https://hub.docker.com/r/kubeedge/cloudcore/tags https://hub.docker.com/r/kubeedge/controller-manager/tags https://hub.docker.com/r/kubeedge/iptables-manager/tags
> > 
> > 
> > @gy95 please take a look, thanks :)
> 
> there's something wrong in release script, publish image to `iptablesmanager` and `controllermanager` but not `iptables-manager` and `controller-manager`

I checked the relevant code and I will fix it.

**Comment by benjaminhuo** [comment]
> there's something wrong in release script, publish image to `iptablesmanager` and `controllermanager` but not `iptables-manager` and `controller-manager`

Here? 
https://github.com/kubeedge/kubeedge/blob/master/.github/workflows/release.yml#L91

**Comment by gy95** [comment]
thanks, i'm working on it, and will open a PR soon.

**Comment by benjaminhuo** [comment]
@gy95 @fisherxu would you help to sync the below images?
kubeedge/controller-manager:v1.13.0
kubeedge/iptables-manager:v1.13.0

When the sync is done, this PR will be ready to be merged

**Comment by benjaminhuo** [comment]
> @gy95 @fisherxu would you help to sync the below images? kubeedge/controllermanager:v1.13.0 -> kubeedge/controller-manager:v1.13.0 kubeedge/iptablesmanager:v1.13.0 -> kubeedge/iptables-manager:v1.13.0
> 
> When the sync is done, this PR will be ready to be merged

@fisherxu @gy95 The images haven't been synced to dockerhub yet, would you help on this?

**Pull request closed without merging**
