### PR TITLE
update to output the information of help

### PR DESCRIPTION
**Pull request by Catherine-monk**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
After the modification, the contents of fields such as KEADM_DEPRECATED_E2E_HELP_INFO and KEADM_E2E_HELP_INFO can be normally output in keadm_e2e.

**Which issue(s) this PR fixes**:

Fixes #
update to output the information of help

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Plz add some PR description:)

**Comment by Catherine-monk** [comment]
add the description:
After the modification, the contents of fields such as `KEADM_DEPRECATED_E2E_HELP_INFO` and `KEADM_E2E_HELP_INFO` can be normally output in `keadm_e2e`.

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
