### PR TITLE
remove unnecessary select clause, replace it with simple chan sending

### PR DESCRIPTION
**Pull request by beautytiger**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fisherxu** [comment]
@beautytiger Please rebased to fix the CI issue :)

**Comment by sids-b** [comment]
Thanks @beautytiger

**Pull request merged**
