### PR TITLE
update CoC, point to kubeedge/community/CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

https://github.com/kubeedge/community/issues/158

update CoC to point to kubeedge/community/CODE_OF_CONDUCT.md

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
It's also need to add coc for repo under staging.

ref: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/code-of-conduct.md

**Comment by Shelley-BaoYue** [comment]
> It's also need to add coc for repos under staging.
> 
> ref: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/code-of-conduct.md

Done. I have added these files under staging.

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by WillardHu** [comment]
lgtm ~

**Review by fisherxu — COMMENTED** [review]
/assign @WillardHu

**Pull request merged**
