### PR TITLE
Change new config format

### PR DESCRIPTION
**Pull request by kadisi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by sids-b** [comment]
@kadisi , the change is huge. Can you please split into 3 different PRs ?
1) Cloud changes
2) Edge Changes
3) Installer changes

It will be easy for review. Also can you please squash a few commits ?

**Comment by kadisi** [comment]
@sids-b  i have squash a few commits . but splitting into 3 prs is difficult because we need to modify the beehive, ci cannot pass.

**Comment by kadisi** [comment]
@sids-b  i have squash a few commits . but splitting into 3 prs is difficult because we need to modify the beehive, ci cannot pass.

**Comment by kadisi** [comment]
@fisherxu @sids-b ok, https://github.com/kubeedge/kubeedge/pull/1212 this pr is about edgecore ,cloudcore,edgesite apis

**Comment by kadisi** [comment]
@fisherxu @sids-b ok, https://github.com/kubeedge/kubeedge/pull/1212 this pr is about edgecore ,cloudcore,edgesite apis

**Comment by kadisi** [comment]
closed , because #1393 has been merged

**Pull request closed without merging**
