### PR TITLE
fix the high-risk vulnerability that the installation package depends on

### PR DESCRIPTION
**Pull request by fengshunli**
dependencies not fixed
image

to upgrade golang.org/x/net  and helm.sh/helm/v3, you need to update the k8s version and upgrade go version to 16 or above

### CODE REVIEW

**Comment by vincentgoat** [comment]
Is this PR only to fix the dependence golang.org/x/net issue?

**Comment by fengshunli** [comment]
> Is this PR only to fix the dependence golang.org/x/net issue?

Solve crypto, text, client_golang, go-restful

**Comment by fisherxu** [comment]
@fengshunli Could you please introduce your tool for detect the cve in dependence? And whether it's possible to integrate in CI :)

**Comment by fengshunli** [comment]
> @fengshunli Could you please introduce your tool for detect the cve in dependence? And whether it's possible to integrate in CI :)

update

**Pull request closed without merging**
