### PR TITLE
[do not merge] test ci

### PR DESCRIPTION
**Pull request by edisonxiang**
test ci

### CODE REVIEW

**Comment by m1093782566** [comment]
I expected the CI result to be green. However, it keeps being pending state though it REALLY skips all test jobs.

**Comment by edisonxiang** [comment]
A moment ago, it was in the queue.
Now it is running.
https://travis-ci.org/kubeedge/kubeedge/builds/521996156

**Comment by edisonxiang** [comment]
Seem good. It saves about 30 mins

**Comment by edisonxiang** [comment]
It works we can close this pr.
If we have better solution to skip the docs-only commit, we will reopen it

**Pull request closed without merging**
