### PR TITLE
Nominate myself(WillardHu) as a new maintainer

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

I was active in the KubeEdge and participated in a lot of functional development and Bug fix, and I also had a lot of imagination about the KubeEdge.

I have more than 10 years(4 years in the cloud native) of development experience, I believe I can help make KubeEdge even better, so I would like to apply myself(WillardHu) as a new maintainer and make more contributions to the community.

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
/lgtm
/assign @kubeedge/maintainers @kubeedge/tsc

**Review by kevin-wangzefeng — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
We've got 6/7 approval from TSC members, 2 approval from core maintainers, thank you all for the support.
/approve

**Pull request merged**
