### PR TITLE
Bump k8s version to  1.29.6

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Bump k8s version to 1.29.6

**Which issue(s) this PR fixes**:

 https://github.com/kubeedge/kubeedge/issues/5597

### CODE REVIEW

**Review by Shelley-BaoYue — COMMENTED** [review]
/hold 
wait for #5653 merged first.

**Comment by Shelley-BaoYue** [comment]
/hold cancel 
ready to be reviewed : )

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
