### PR TITLE
fix helm default values

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

1. Upgrade cloudcore default image tag to "v1.13.0" (controllermanager and iptables-manager no "v1.13.0" tag in dockerhub).
2. If the property `cloudCore.hostNetWork` is a string value,  The expression `{{- if and (eq .Values.cloudCore.service.type "NodePort") ( not .Values.cloudCore.hostNetWork) }}` is always `false` in service_cloudcore.yaml, this means service will not be a NodePort type.
3. Set all enable fields to bool type.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by zhu733756** [comment]
> /assign @zhu733756

Yes

thanks for fixing
/lgtm

**Comment by zhu733756** [comment]
> > /assign @zhu733756
> 
> Yes
> 
> thanks for fixing /lgtm

Pls also check version.yaml

**Comment by WillardHu** [comment]
> > > /assign @zhu733756
> > 
> > 
> > Yes
> > thanks for fixing /lgtm
> 
> Pls also check version.yaml

Done, thanks

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
