### PR TITLE
update controller-manager image tag in profile

### PR DESCRIPTION
**Pull request by my-git9**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The controller-manager image tag should be 1.12.0 like other components

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
LGTM

**Comment by gy95** [comment]
@zhu733756 you're the maintainer, and can just approve directly 😄

**Comment by zhu733756** [comment]
> @zhu733756 you're the maintainer, and can just approve directly 😄

:)

**Comment by zhu733756** [comment]
/approve

Thanks

**Comment by gy95** [comment]
cc @zc2638 @zhu733756 @fisherxu
need a LGTM :)

**Pull request merged**
