### PR TITLE
update latest dependencies of async, chokidar and log4js

### PR DESCRIPTION
**Pull request by RicardoZPHuang**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug

**What this PR does / why we need it**:
update the vulnerable dependency lodash 4.7.11 to 4.7.14
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by fisherxu** [comment]
Does the change satisfed the condition lodash ~> 4.17.13? @RicardoZPHuang @Baoqiang-Zhang @sids-b

**Comment by RicardoZPHuang** [comment]
@fisherxu 

> Does the change satisfed the condition `lodash ~> 4.17.13`? @RicardoZPHuang @Baoqiang-Zhang @sids-b

yes, the version of lodash now is 4.17.14 (line 668 in package-lock.json).

**Comment by fisherxu** [comment]
@RicardoZPHuang  ok, sgtm, thanks!

**Pull request merged**
