### PR TITLE
fix white noise detected by make lint

### PR DESCRIPTION
**Pull request by guihecheng**
Signed-off-by: Gui Hecheng <guihecheng@cmiot.chinamobile.com>

**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
@guihecheng please take care about picture files.

**Comment by guihecheng** [comment]
@daixiang0 hmmm... then I think the script should skip white noise check for the picture files otherwise the lint will still stuck. I'll try to fix the script here.

**Comment by guihecheng** [comment]
As I found, the script intends to skip images already, but the .png(s) are not placed into a proper folder, so fix it and keep the lint script untouched.

**Review by fisherxu — COMMENTED** [review]
@guihecheng Pics are part of docs so we shoud create the images dir under docs

**Comment by guihecheng** [comment]
@fisherxu ok, thanks for reminding, xxx/images -> xxx/docs/images, updated :)

**Comment by fisherxu** [comment]
/lgtm
/approve
Thanks for the fixing @guihecheng

**Pull request merged**
