### PR TITLE
[WIP] support kubectl exec feature

### PR DESCRIPTION
**Pull request by kadisi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

/kind feature
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Refs #1477 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

support kubectl exec feature

```

### CODE REVIEW

**Comment by Yellow-L** [comment]
@kadisi @fisherxu  I finished the rest coding work and could run exec command through tunnel. 
following is the code and for your information:
cloud/pkg/cloudstream/containerexec_connection.go 
```
func (c *ContainerExecConnection) Serve() error {
	defer func() {
		klog.Infof("%s end successful", c.String())
	}()

	// first send connect message
	if _, err := c.SendConnection(); err != nil {
		klog.Errorf("%s send %s info error %v", c.String(), stream.MessageTypeExecConnect, err)
		return err
	}

	stop := make(chan struct{})
	spdyHeader := make([]byte, 8)
	go func() {
		for{
			n, err := io.ReadFull(c.Conn, spdyHeader)
			if err != nil {
				close(stop)
				klog.Error("read form apiserver error: ", err)
				return
			}
			klog.Info("#### read form apiserver, len header: ", len(spdyHeader), "n: ", n, " content: ", spdyHeader)
			t := make([]byte, 4)
			for i:= 5; i<8; i++ {
				t[i-4] = spdyHeader[i]
			}
			dataLen := binary.BigEndian.Uint32(t)
			spdyData := make([]byte, dataLen)
			n, err = io.ReadFull(c.Conn, spdyData)
			if err != nil {
				close(stop)
				klog.Error("read form apiserver error: ", err)
				return
			}
			klog.Info("#### read form apiserver, len spdyData: ", len(spdyData), "n: ", n, " content: ", spdyData)

			var msgData []byte
			msgData = append(msgData, spdyHeader...)
			msgData = append(msgData, spdyData...)
			klog.Info("#### read form apiserver, len msgData: ", len(msgData), " content: ", msgData)


			msg := stream.NewMessage(c.MessageID, stream.MessageTypeData, msgData)
			err = c.WriteToTunnel(msg)
			if err != nil {
				klog.Errorf("%v write tunnel message %v error", c.String(), msg)
				close(stop)
				return
			}
			klog.Info("#### write exec data.")
		}
		klog.Info("#### exec finished")
	}()
	for{
		select {
		case <-c.ctx.Done():
			// if apiserver request end, send close message to edge
			msg := stream.NewMessage(c.MessageID, stream.MessageTypeRemoveConnect, nil)
			for retry := 0; retry < 3; retry++ {
				if err := c.WriteToTunnel(msg); err != nil {
					klog.Warningf("%v send %s message to edge error %v", c, msg.MessageType, err)
				} else {
					break
				}
			}
			klog.Infof("%s send close message to edge successfully", c.String())
			return nil
		case <-c.EdgePeerDone():
			klog.Infof("%s find edge peer done, so stop this connection", c.String())
			return nil
		case <-stop:
			klog.Infof("receive stop single, so stop exec ...")
			return nil
		}
	}
	klog.Info("#### server exec finished")
	return nil
}
```
pkg/stream/edgedexecconnection.go
```
func GetResponse(r io.Reader) (*http.Response, []byte, error) {
	rawResponse := bytes.NewBuffer(make([]byte, 0, 256))
	// Save the bytes read while reading the response headers into the rawResponse buffer
	resp, err := http.ReadResponse(bufio.NewReader(io.TeeReader(r, rawResponse)), nil)
	if err != nil {
		return nil, nil, err
	}
	// return the http response and the raw bytes consumed from the reader in the process
	return resp, rawResponse.Bytes(), nil
}

func (e *EdgedExecConnection) Serve(tunnel SafeWriteTunneler) error {
    var rawResponse []byte
    spdyHeader := make([]byte, 8)
	upgrade := machineryspdy.NewSpdyRoundTripper(nil, true, true)

	req, err := http.NewRequest(e.Method, e.URL.String(), nil)
	if err != nil {
		return fmt.Errorf("error creating request: %v", err)
	}
	req.Header = e.Header

	klog.Infof("Exec Dial request:%++v", *req)

	con, err := upgrade.Dial(req)
	if err != nil {
		klog.Errorf("%s Dailer error %v", e.String(), err)
		return err
	}
	defer con.Close()
	klog.Infof("Exec Dial successfully ...")

	backendHTTPResponse, headerBytes, err := GetResponse(io.MultiReader(bytes.NewReader(rawResponse), con))
	if err != nil {
		klog.Infof("Proxy connection error: %v", err)
		//h.Responder.Error(w, req, err)
		return err
	}

	if backendHTTPResponse.StatusCode != http.StatusSwitchingProtocols {
		// If the backend did not upgrade the request, echo the response from the backend to the client and return, closing the connection.
		klog.Errorf("Proxy upgrade error, status code %d", backendHTTPResponse.StatusCode)
		return err
	}

	if len(headerBytes) > len(rawResponse) {
		// we read beyond the bytes stored in rawResponse, update rawResponse to the full set of bytes read from the backend
		klog.Infoln("headerBytes: ", len(headerBytes), "rawResponse: ", len(rawResponse))
		rawResponse = headerBytes
	}
	if len(rawResponse) > 0 {
		klog.Infof("Writing %d bytes to hijacked connection, data: %s", len(rawResponse), string(rawResponse))
		msg := NewMessage(e.MessID, MessageTypeData, rawResponse)
		klog.Info("#### send tunnel message: ", string(rawResponse))
		err := msg.WriteTo(tunnel)
		if err != nil {
			klog.Errorf("%v write tunnel message %v error", e.String(), msg)
			return err
		}
	}

	stop := make(chan struct{})
	go func() {
		for mess := range e.ReadChan {
			klog.Info("#### message type: ", mess.MessageType, " data: ", string(mess.Data))
			switch mess.MessageType {
			case MessageTypeRemoveConnect:
				klog.Infof("%s receive remove client id %v", e.String(), mess.ConnectID)
				close(stop)
				return
			case MessageTypeData:
				klog.Info("TODO ######## write exec data len: ", len(mess.Data), " data: ", mess.Data)
				con.Write(mess.Data)
				//return
			}
		}

	}()

	go func() {
		for {
			n, err := io.ReadFull(con, spdyHeader)
			if err != nil {
				close(stop)
				klog.Error("read form edged error: ", err)
				return
			}
			klog.Info("#### read form edged, len header: ", len(spdyHeader), "n: ", n, " content: ", spdyHeader)
			t := make([]byte, 4)
			for i:= 5; i<8; i++ {
				t[i-4] = spdyHeader[i]
			}
			dataLen := binary.BigEndian.Uint32(t)
			spdyData := make([]byte, dataLen)
			n, err = io.ReadFull(con, spdyData)
			if err != nil {
				close(stop)
				klog.Error("read form edged error: ", err)
				return
			}
			klog.Info("#### read form edged, len spdyData: ", len(spdyData), "n: ", n, " content: ", spdyData)

			var msgData []byte
			msgData = append(msgData, spdyHeader...)
			msgData = append(msgData, spdyData...)
			klog.Info("#### read form edged, len msgData: ", len(msgData), " content: ", msgData)


			msg := NewMessage(e.MessID, MessageTypeData, msgData)
			klog.Info("#### received message: ", msgData)
			err = msg.WriteTo(tunnel)
			if err != nil {
				klog.Errorf("%v write tunnel message %v error", e.String(), msg)
				close(stop)
				return 
			}
		}
	}()

	defer func() {
		for retry := 0; retry < 3; retry++ {
			msg := NewMessage(e.MessID, MessageTypeRemoveConnect, nil)
			if err := msg.WriteTo(tunnel); err != nil {
				klog.Errorf("%v send %s message error %v", e, msg.MessageType, err)
			} else {
				break
			}
		}
	}()

	for {
		select {
		case <-stop:
			klog.Infof("receive stop single, so stop exec scan ...")
			return nil
		}
	}
	klog.Info("#### edge exec finished")

	return nil
}
```

**Comment by fisherxu** [comment]
@Yellow-L Thanks for the great work, we also have another PR #2075 to complete this feature, will you take a review?

**Comment by Yellow-L** [comment]
@fisherxu ok, I'll take a code review to this PR.

**Comment by chendave** [comment]
pls review this instead: https://github.com/kubeedge/kubeedge/pull/2075

**Pull request closed without merging**
