### PR TITLE
Run cloudcore as service

### PR DESCRIPTION
**Pull request by GsssC**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

support cloudcore run as systemd service, so we can restart cloudcore by `systemctl restart cloudcore`

also fix some closely related bugs, so merge them into one pr:

1. Stop to Re-download `service file` if it exsists.
2. More msg about why failed to install.
3. change `klog.Fatal` to `klog.Error`, I think it is too superficial too log func stack here, no help for debug but make user nervers
https://github.com/kubeedge/kubeedge/blob/7c415600ccd66e6cf4c18999939586e71e8ac59d/keadm/cmd/keadm/keadm.go#L27
shown as below:
image
image

**Which issue(s) this PR fixes**:

Fixes None-related-issue

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None
```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
Why not run cloudcore as container? @GsssC  ref: #1635  #1781

**Comment by GsssC** [comment]
@fisherxu Yes, run as container also matters. Not compare `run as system service` with `run as container`, see it as a upgrade of `run as binary` ->**nohup cloudcore 2 &> 1 1 > cloudcore.log &**, I think it is make sense.
: )

**Comment by fisherxu** [comment]
Let's run it as deployment

**Comment by GsssC** [comment]
@fisherxu So will we still remain the way of `run as binary` ? If no, `run as system service` make no sense.

**Comment by fisherxu** [comment]
Need to review and merge #1781

**Comment by luogangyi** [comment]
+ 1
From user's prospective, running cloudcore as systemd service is useful.
Especially in scenery that user do not have full control of K8S. Running cloudcore need some iptables setting, it's hard to do in third-party K8S service. In that situation, runing cloudcore in a standalone VM is better.

**Comment by fisherxu** [comment]
> Running cloudcore need some iptables setting, it's hard to do in third-party K8S service. 

CloudCore just watch objects from apiserver, for setting iptable rules, we can just use hostnetwork. Within container, cloudcore can also be isolated with other k8s control plane component :)

**Comment by luogangyi** [comment]
> > Running cloudcore need some iptables setting, it's hard to do in third-party K8S service.
> 
> CloudCore just watch objects from apiserver, for setting iptable rules, we can just use hostnetwork. Within container, cloudcore can also be isolated with other k8s control plane component :)

Cloudcore also proxy kube-api's and metric server's api request in logs and metrics, that requires iptabels config. Hostnetwork does not solve all problem.( Sure we can also config iptables in pod when we use NET_RAW and NET_ADMIN flag)

I think running cloudcore in containers is easy to achieve high availability while running in systemd is easy to configure and test. They are not conflict.

**Comment by luogangyi** [comment]
related to #2142

**Comment by fisherxu** [comment]
/hold
Need more discussion.

**Pull request closed without merging**
