### PR TITLE
Issue #299 fix

### LINKED ISSUE #299: IT test cases failing randomly for device test
Screenshot from 2019-03-26 15-13-20
**Which jobs are failing**:
edge_integration_test jobs are failing
**Which test(s) are failing**:
TC_TEST_EBUS_6,TC_TEST_EBUS_7,TC_TEST_EBUS_8
**Since when has it been failing**:
Since past 2 Days
**Reason for failure**:
May be Environment issue,Could not be reproduced in the Local environment
**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by pavan187**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
It Fixes Issue #299 

**Which issue(s) this PR fixes**:
Fixes #299

### CODE REVIEW

**Comment by m1093782566** [comment]
cc @srivatsav123 for review.

**Comment by m1093782566** [comment]
@pavan187 Please describe why the changes can fix the issue #299.

**Comment by sids-b** [comment]
The main change I can see over here is that we have completely independent test cases.

**Comment by sids-b** [comment]
Also we are connecting MQTT at the beginning and disconnecting at the end to maintain the subscription throughout.

**Comment by m1093782566** [comment]
OK, let CI tell us the result.

**Pull request merged**
