### PR TITLE
Modify keadm RunMQTT(CRIRuntime)

### PR DESCRIPTION
**Pull request by luomengY**
The source code modification is mainly to solve the defects: https://github.com/kubeedge/kubeedge/issues/4783, edgecore system bin directory will be deleted after launch, detailed bug tracking report, please read the links: https://github.com/xingleigao/kubeedge/blob/keadm-mqtt-bug/docs/proposals/keadm-mqtt-bug.md.

### CODE REVIEW

**Comment by luomengY** [comment]
Please review this pr, @kevin-wangzefeng  @subpathdev  @sids-b ; This problem has serious consequences, which can cause the user's system to crash.

**Comment by luomengY** [comment]
@fisherxu @FengyunPan2 @daixiang0 @zhu733756

**Comment by luomengY** [comment]
/assign @sids-b




---Original---
From: "KubeEdge ***@***.***&gt;
Date: Sun, May 28, 2023 15:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kubeedge/kubeedge] Modify keadm RunMQTT(CRIRuntime) (PR #4794)




 
[APPROVALNOTIFIER] This PR is NOT APPROVED
 
This pull-request has been approved by:
 To complete the pull request process, please assign sids-b after the PR has been reviewed.
 You can assign the PR to them by writing /assign @sids-b in a comment when ready.
 
The full list of commands accepted by this bot can be found here.
  Needs approval from an approver in each of these files:  
keadm/OWNERS
  
Approvers can indicate their approval by writing /approve in a comment
 Approvers can cancel approval by writing /approve cancel in a comment

**Comment by Shelley-BaoYue** [comment]
Hi, @luomengY , I have pushed a pr: #4814 . It can solve mqtt container exited when using cri runtime, and also use kubelet to solve the log path problem.
image

**Comment by luomengY** [comment]
鲍玥老师你好，我们能加个微信讨论一下这个问题么？19138986073









      发自我的企业微信         

 
 
 ----------Reply to Message----------
 On Tue, Jun 6, 2023 21:18 PM Shelley ***@***.***&gt; wrote:

  

 
Hi, @luomengY , I have pushed a pr: #4814 . It can solve mqtt container exited when using cri runtime, and also use kubelet to solve the log path problem.

**Pull request closed without merging**
