### PR TITLE
Set PluginBinDirString instead of PluginBinDirs directly

### PR DESCRIPTION
**Pull request by 420691301**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

 /kind bug

**What this PR does / why we need it**:
Now edged set PluginBinDirs of NetworkPluginSettings directly, which will be overwritten by empty strings in [`NewDockerService()`](https://github.com/kubernetes/kubernetes/blob/2e5d5ebf593c551cdba2e4eff76ddb37e72d9b50/pkg/kubelet/dockershim/docker_service.go#L241) .Set PluginBinDirString instead of PluginBinDirs, just like [kubelet](https://github.com/kubernetes/kubernetes/blob/2e5d5ebf593c551cdba2e4eff76ddb37e72d9b50/pkg/kubelet/kubelet.go#L350).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
/lgtm
Are you trying cni? @420691301

**Comment by 420691301** [comment]
@fisherxu yes. I test cni with bridge plugins.

**Comment by fisherxu** [comment]
> @fisherxu yes. I test cni with bridge plugins.

ok, thanks for the effort, looking forward to more feedback. @420691301

**Pull request merged**
