### PR TITLE
Remove unused fields placement/refresh-ak-sk-interval/auth-info-files-path/placement-url

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/cc @kadisi  @Baoqiang-Zhang @kexun @rohitsardesai83 @sids-b

### CODE REVIEW

**Comment by kadisi** [comment]
@fisherxu  i think , keadm need to be changed at the same time . :)

**Comment by fisherxu** [comment]
@kadisi yes, right, need to deleted in keadm. Have done, patl

**Comment by rohitsardesai83** [comment]
/lgtm.

Let's remove references of placement url from: 

1. https://github.com/kubeedge/kubeedge/blob/master/docs/modules/edge/edgehub.md#get-cloudhub-url
2. https://github.com/kubeedge/kubeedge/blob/master/edge/hack/setup_for_IEF.sh#L175

**Comment by fisherxu** [comment]
@rohitsardesai83  I have remove them. And just the `Get CloudHub URL` part from `edgehub.md`, how about it?

**Pull request merged**
