### PR TITLE
Fix release_package.md bug

### LINKED ISSUE #803: docs: bug of release_package.md, urls were wrong
Just a little urls location bug when I following the steps to run kubeedge. The contents of  `kubeedge/docs/getting-started/release_package.md`:

>## Generate Certificates
>```
>wget -L https://github.com/kubeedge/kubeedge/blob/master/build/tools/certgen.sh
># make script executable
>chmod +x certgen.sh
>bash -x ./certgen.sh genCertAndKey edge
>```

>- Create device model and device CRDs
>```
>wget -L https://github.com/kubeedge/kubeedge/blob/master/build/crds/devices/devices_v1alpha1_devicemodel.yaml
># make script executable
>chmod +x devices_v1alpha1_devicemodel.yaml
>kubectl create -f devices_v1alpha1_devicemodel.yaml
>wget -L https://github.com/kubeedge/kubeedge/blob/master/build/crds/devices/devices_v1alpha1_device.yaml
># make script executable
>chmod +x devices_v1alpha1_device.yaml
>kubectl create -f devices_v1alpha1_device.yaml
>```

I think URLS were wrong since I used the commands just got HTML file. And the right urls are below:
## Generate Certificates
```
wget -L https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/tools/certgen.sh
# make script executable
chmod +x certgen.sh
bash -x ./certgen.sh genCertAndKey edge
```
- Create device model and device CRDs
```
wget -L https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_devicemodel.yaml
# make script executable
chmod +x devices_v1alpha1_devicemodel.yaml
kubectl create -f devices_v1alpha1_devicemodel.yaml
wget -L https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_device.yaml
# make script executable
chmod +x devices_v1alpha1_device.yaml
kubectl create -f devices_v1alpha1_device.yaml
```

### PR DESCRIPTION
**Pull request by HeathKang**
1) change URLS after `wget -L` commands

close #803

**What type of PR is this?**

 /kind documentation

**What this PR does / why we need it**:
fix doc urls bug

**Which issue(s) this PR fixes**:

Fixes #803

### CODE REVIEW

**Comment by sids-b** [comment]
@HeathKang can you please change the commit message ? The bot is indicating invalid commit message. I think it is because of the word Fix in the message

**Comment by HeathKang** [comment]
ok, I will do it later

**Comment by rohitsardesai83** [comment]
@HeathKang , please remove other commits from your PR.

**Comment by HeathKang** [comment]
reopen on #821

**Comment by kevin-wangzefeng** [comment]
Please rebase to latest master. The following commands would help:
```bash
# add upstream as one of your remote
git remote add upstream https://github.com/kubeedge/kubeedge.git

# fetch upstream updates
git fetch upstream

# on your working branch
git rebase upstream/master
```

**Comment by kevin-wangzefeng** [comment]
And you may indicate the "--force" flag when pushing after you use `git rebase` command.

**Comment by kevin-wangzefeng** [comment]
Just saw the other PR accepted, no worries.

**Comment by HeathKang** [comment]
@kevin-wangzefeng thanks for help, I missed  `--force` option in this commit

**Pull request closed without merging**
