### PR TITLE
update crds to newer ones

### PR DESCRIPTION
**Pull request by snstaberah**
crds in this file use apiextensions.k8s.io/v1beta1,which has been removed from kubernetes 1.22; use newer generated crds instead of the old ones;

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
update crds in this file to adapt k8s after 1.22；
 apiextensions.k8s.io/v1 is available in k8s 1.16；
**Which issue(s) this PR fixes**:

Fixes #
3bf38f9923d0eeec60d0a8a0db6c4f4

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
LGTM

**Review by fisherxu — COMMENTED** [review]
@snstaberah Whether this crd be same as file under build/crds/devices? :)

**Comment by snstaberah** [comment]
> 



> @snstaberah Whether this crd be same as file under build/crds/devices? :)

yes,i regenerate the crds by  run 'make generate', and replace the crds in this file  by  the copys  of  build/crds/devices;

besides, the  build/crds contains  some old crds  of v1alpha1, which is generated 2 years age and  out of date;   maybe we can  remove those  out of date files  to reduce some misunderstand;

**Comment by fisherxu** [comment]
> besides, the build/crds contains some old crds of v1alpha1, which is generated 2 years ago and out of date; maybe we can remove those out of date files to reduce some misunderstanding;

Agree.

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
