### PR TITLE
update chart default image tag to v1.12.0

### PR DESCRIPTION
**Pull request by my-git9**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Update chart default image tag to v1.12.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wackxu** [comment]
cc @gy95

**Comment by zc2638** [comment]
/lgtm
wait for @zhu733756

**Comment by zhu733756** [comment]
/lgtm 
waiting for @fisherxu

**Comment by zhu733756** [comment]
/approve

Thanks!

**Pull request merged**
