### PR TITLE
Fix EdgeApplication image path annotation error

### PR DESCRIPTION
**Pull request by tangming1996**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
An incorrect image path will result in a failure to create a deployment instance.
**Which issue(s) this PR fixes**: 
The deployment instance could not be created due to a image path error.

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
LGTM, and the yaml under build and manifest dir should be auto-generated? @tangming1996

**Comment by tangming1996** [comment]
> LGTM，构建和清单目录下的yaml应该是自动生成的？@tangming1996

Yes, it is automatically generated using the kubeedge CRD script

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
