### PR TITLE
Update kubeedge architecture picture

### PR DESCRIPTION
**Pull request by m1093782566**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind documentation

**What this PR does / why we need it**:

Update kubeedge architecture picture to complete the cloud part details.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by m1093782566** [comment]
cc @kevin-wangzefeng @rohitsardesai83 @sids-b @skdwriting @qizha

**Comment by m1093782566** [comment]
@pavan187 seems `/kind documentation` does not work?

**Comment by rohitsardesai83** [comment]
@m1093782566 , please update the arch to include controllers like edge, device etc. thanks !

**Comment by m1093782566** [comment]
I am going to merge this PR, let's refine the picture in follow-ups.

**Pull request merged**
