### PR TITLE
remove out of date crds

### PR DESCRIPTION
**Pull request by snstaberah**
crds of device v1alpha1 is out of date,remove them to avoid
misunderstanding

Signed-off-by: snstaberah <yangyonglc@inspur.com>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
https://github.com/kubeedge/kubeedge/pull/3907#issuecomment-1153569822
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by snstaberah** [comment]
> maybe some versions <=v1.3 cannot install successfully with keadm, even though we not support those releases anymore, is this OK? https://github.com/kubeedge/kubeedge/blob/release-1.3/keadm/cmd/keadm/app/cmd/util/k8sinstaller.go
> 
> https://github.com/kubeedge/kubeedge/blob/2a64a950a791d8ff62f4540a02f1110e3e80d0da/keadm/cmd/keadm/app/cmd/util/k8sinstaller.go#L120-L135

thanks，i think this is a hardcore coding ：） ，maybe i can optimize this in next pr？

**Comment by fisherxu** [comment]
>  the common method to support old version crds is write a conversion webhook to update them 

Sounds good for compatibility. Could you please open an issue to track it?
And for 1.3 release, it's too old.. and have been out of maintenance period. So no need to keep it.

**Comment by snstaberah** [comment]
> > the common method to support old version crds is write a conversion webhook to update them
> 
> Sounds good for compatibility. Could you please open an issue to track it? And for 1.3 release, it's too old.. and have been out of maintenance period. So no need to keep it.

ok，I have opened a new issue here ：
https://github.com/kubeedge/kubeedge/issues/3913#issue-1270361473

**Pull request closed without merging**
