### PR TITLE
keadm init/reset panic

### LINKED ISSUE #2190: keadm init/reset panic
**What happened**:
panic with command init/reset when cloudcore already running/stoped. 
```
[root@node1 tmp]# ./keadm init --advertise-address="172.16.68.71"
Error: CloudCore is already running on this node, please run reset to clean up first
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.2.1  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --advertise-address string   Use this key to set SANs in certificate of cloudcore. eg: 10.10.102.78,10.10.102.79
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080

F0924 19:44:41.167123    5961 keadm.go:27] CloudCore is already running on this node, please run reset to clean up first
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0002b7f00, 0xc00030e000, 0x79, 0xcd)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:883 +0xb8
k8s.io/klog.(*loggingT).output(0x2006980, 0xc000000003, 0xc0002f6070, 0x1f7ca9c, 0x8, 0x1b, 0x0)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:834 +0x330
k8s.io/klog.(*loggingT).printDepth(0x2006980, 0xc000000003, 0x1, 0xc0000ebf40, 0x1, 0x1)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:706 +0x129
k8s.io/klog.(*loggingT).print(...)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:697
k8s.io/klog.Fatal(...)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1264
main.main()
	/opt/projetcs/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0x8a
[root@node1 tmp]# ./keadm reset
KubeEdge cloudcore is stopped, For logs visit:  /var/log/kubeedge/cloudcore.log
Error: TearDown failed, err:fail to clean kubeedge namespace, err:namespaces "kubeedge" not found
Usage:
  keadm reset [flags]

Examples:

For cloud node:
keadm reset

For edge node:
keadm reset


Flags:
  -h, --help                 help for reset
      --kube-config string   Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")

F0924 19:45:36.568494    6724 keadm.go:27] TearDown failed, err:fail to clean kubeedge namespace, err:namespaces "kubeedge" not found
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0003edf00, 0xc000452000, 0x86, 0xda)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:883 +0xb8
k8s.io/klog.(*loggingT).output(0x2006980, 0xc000000003, 0xc00044e000, 0x1f7ca9c, 0x8, 0x1b, 0x0)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:834 +0x330
k8s.io/klog.(*loggingT).printDepth(0x2006980, 0xc000000003, 0x1, 0xc000101f40, 0x1, 0x1)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:706 +0x129
k8s.io/klog.(*loggingT).print(...)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:697
k8s.io/klog.Fatal(...)
	/opt/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1264
main.main()
	/opt/projetcs/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0x8a
```
**What you expected to happen**:
no panic 

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.4.0

### PR DESCRIPTION
**Pull request by Yellow-L**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
keadm just show error message when encounter an error, not panic.
**Which issue(s) this PR fixes**:

Fixes #2190

### CODE REVIEW

**Review by GsssC — COMMENTED** [review]
/lgtm, panic here makes users nervers, and no help for debug.

**Comment by GsssC** [comment]
I restart fail-ci-test and need to wait for pass.

**Comment by Yellow-L** [comment]
@GsssC error encountered with CI.

**Comment by GsssC** [comment]
@daixiang0 SOS, need help for this weird ci-fail.
image

**Comment by daixiang0** [comment]
Retest it may work.

**Comment by GsssC** [comment]
@daixiang0 reset serveral times but still fail.

**Comment by fisherxu** [comment]
Could you please add `pflag.Set("logtostderr", "true")` to L31 of keadm/cmd/keadm/app/keadm.go? Maybe help.

**Comment by fisherxu** [comment]
@Yellow-L @GsssC

**Comment by Yellow-L** [comment]
@fisherxu Is it need to add an error checking? Branch 1.4.0 doesn't have that error check.

**Comment by fisherxu** [comment]
> @fisherxu Is it need to add an error checking? Branch 1.4.0 doesn't have that error check.

Error checking for what? For `pflag.Set("logtostderr", "true")` we can just add a checking.

**Comment by Yellow-L** [comment]
@fisherxu Need your help, explicit initialization of log flag set could solve this error but other log subcommands will be introduced at same time. Code version 1.4.0 doesn't do this and no other imported packages but without not fount flag -logtostderr error.

**Pull request closed without merging**
