### PR TITLE
edged add ReasonCache

### PR DESCRIPTION
**Pull request by gy95**
Signed-off-by: gy95 <guoyao17@huawei.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
According to k8s ReasonCache comments:
```
ReasonCache stores the failure reason of the latest container start
in a string, keyed by <pod_UID>_<container_name>. The goal is to
propagate this reason to the container status.
```
By introducing this structure, we could provide more details or status about pod to kube-apiserver, so we can find more details about the reason why pods failed to be started.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Has any bugs if without this patch?

**Comment by gy95** [comment]
> Has any bugs if without this patch?

this is feature from @XuShiwei, just along with  https://github.com/kubeedge/kubeedge/pull/3077, https://github.com/kubeedge/kubeedge/pull/3060,  to provide more details about status.

**Comment by fisherxu** [comment]
> > Has any bugs if without this patch?
> 
> this is feature from @xushiwei, just along with #3077, #3060, to provide more details about status.

Please add more description in the pr, like what info will add with this patch.

**Comment by gy95** [comment]
> > > Has any bugs if without this patch?
> > 
> > 
> > this is feature from @xushiwei, just along with #3077, #3060, to provide more details about status.
> 
> Please add more description in the pr, like what info will add with this patch.

ok, done.

**Pull request closed without merging**
