### PR TITLE
Automated cherry pick of #493: Refactor the code to remove redundant statements

### PR DESCRIPTION
**Pull request by rohitsardesai83**
Cherry pick of #493 on release-0.3.

#493: Refactor the code to remove redundant statements

### CODE REVIEW

**Comment by m1093782566** [comment]
Is this a bug fix or usage guide? If not, I would suggest move it to v1.0.

**Comment by rohitsardesai83** [comment]
> Is this a bug fix or usage guide? If not, I would suggest move it to v1.0.

This is a code improvement needed for v0.3

**Comment by sids-b** [comment]
@m1093782566 , it is just removal of redundant code.

**Comment by m1093782566** [comment]
@rohitsardesai83 @sids-b 

I think you may misunderstand the criteria of cherry-pick. Actually I think only bug fixes worth cherry-picking to a specific release - you may refer to Kubernetes.

cc @kevin-wangzefeng

**Comment by sids-b** [comment]
Actually it is code cleanup of the feature(deviceController) which was introduced in v0.3.0-beta.0.

**Comment by rohitsardesai83** [comment]
> @rohitsardesai83 @sids-b
> 
> I think you may misunderstand the criteria of cherry-pick. I think only bug fixes worth cherry-picking to a specific release branch - you may refer to Kubernetes.
> 
> cc @kevin-wangzefeng

since the device controller was introduced as a part of 0.3 release , and this code doesn't introduce any new feature , it is a cleanup activity which I think should be ok to be cherry picked. Only thing is this activity was not associated with any issue. We should in such cases follow practice of always opening issues and then raise PRs.

**Comment by sids-b** [comment]
And also we are cherry picking for 0.3.0 which is a minor release and not a patch release. So i feel adding code cleanups , docs and CRD examples should be fine ?
Thoughts @kevin-wangzefeng @m1093782566 ?

**Comment by m1093782566** [comment]
>  it is a cleanup activity which I think should be ok to be cherry picked.

I think we need to set some barries for cherry-picks for decreasing the number of cherry-picks. Thoughts?

**Comment by m1093782566** [comment]
>  So i feel adding code cleanups , docs and CRD examples should be fine ?

Do you mean all?

**Comment by kevin-wangzefeng** [comment]
The release-xx branches only accepts imporntant bugfixes and document updates. New features, refactoring, clean-up, or fixes that changing function behaviour should not be accepted.

**Pull request closed without merging**
