### PR TITLE
Fix for issue #995

### LINKED ISSUE #995: nil pointer error in Device controller
**What happened**:
Nil pointer error in downstream.go of device controller
image

### PR DESCRIPTION
**Pull request by sujithsimon22**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
Fixes nil pointer error in downstream.go of device controller

**Which issue(s) this PR fixes**:

Fixes #995

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sujithsimon22** [comment]
cc @subpathdev @fisherxu @rohitsardesai83 @sids-b @chendave

**Comment by fisherxu** [comment]
> I am wondering whether some testcases is needed for the PR like this.

Agreed, seems have no test case covered this @sujithsimon22

**Comment by sujithsimon22** [comment]
@chendave @fisherxu There are already test cases added for this along with the e2e functionality of device managment. We were not running it in CI, since our CI was reusing a static setup. PR #856 is almost ready, once that is merged we will have test cases enabled in CI :)

**Comment by sujithsimon22** [comment]
Also the issue was found since the test cases were failing, once we merge this and PR #998, all device related test cases will pass.

**Pull request merged**
