### PR TITLE
add vincent as reviewer

### PR DESCRIPTION
**Pull request by vincentgoat**
Signed-off-by: vincentgoat <linguohui1@huawei.com>

**What type of PR is this?**

**What this PR does / why we need it**:
Add vincentgoat as reviewer.
PR: https://github.com/kubeedge/kubeedge/pulls?q=is%3Apr+author%3Avincentgoat+is%3Aclosed

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by vincentgoat** [comment]
cc @Congrool, Added you as a reviewer in the dir `controllermanager`

**Review by fisherxu — COMMENTED** [review]
/assign @kevin-wangzefeng

**Review by kevin-wangzefeng — COMMENTED** [review]
/approve
Thanks

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Pull request merged**
