### PR TITLE
test: fix keadm test case missing issue

### LINKED ISSUE #2006: make test failed:    can't load package: named files must be .go files:xxx
**Which jobs are failing**:
unit test
**Which test(s) are failing**:
make test
**Since when has it been failing**:
make test
**Reason for failure**:
when I add a unit test. Has nothing to do with the following path 
```
[root@centos-kubeedge kubeedge]# make test
hack/make-rules/clean.sh
hack/make-rules/test.sh 
running tests cases 
can't load package: named files must be .go files: ./cloud/pkg/cloudhub/common/model
make: *** [test] Error 1
```
**Anything else we need to know**:
I find the the reason in  hack/lib/golang.sh  kubeedge::golang::get_keadm_test_dirs()
when I try  to perform this step, not only get the directory, but also get the go file
```
[root@centos-kubeedge kubeedge]# find -L ./keadm \
    -name '*_test.go' -print | xargs -0n1 dirname | uniq
./keadm/cmd/keadm/app/cmd/debug/collect_test.go
./keadm/cmd/keadm/app/cmd/util
```

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2006

### CODE REVIEW

**Comment by shenkonghui** [comment]
> Signed-off-by: Xiang Dai [long0dai@foxmail.com](mailto:long0dai@foxmail.com)
> 
> **What type of PR is this?**
> /kind bug
> 
> **What this PR does / why we need it**:
> 
> **Which issue(s) this PR fixes**:
> 
> Fixes #2006

I tested it and there are still problems, I guess it should change "-print" to "-print0" like `kubeedge::golang::get_cloud_test_dirs()`

**Comment by daixiang0** [comment]
@shenkonghui in fact this would fix first part of your issue: new added test files not cover.

**Pull request merged**
