### PR TITLE
fix the wrong Servicebus group name

### PR DESCRIPTION
**Pull request by muxuelan**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Group of ServiceBus is wrong, ”modules.UserGroup" represents ServiceBus while ”modules.BusGroup" represents EventBus.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
@muxuelan Thanks for the fixing, and could you please modify the commit message and pr title to, like `fix the wrong Servicebus group name`?

**Comment by muxuelan** [comment]
> @muxuelan Thanks for the fixing, and could you please modify the commit message and pr title to, like `fix the wrong Servicebus group name`?

Okay~

**Comment by muxuelan** [comment]
> @muxuelan Thanks for the fixing, and could you please modify the commit message and pr title to, like `fix the wrong Servicebus group name`?

Could this be approved too ?◠◡◠

**Pull request merged**
