### PR TITLE
fix keadm_deprecated_e2e error

### PR DESCRIPTION
**Pull request by gy95**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In `keadm deprecated e2e`, we will run 2 versions test: one is based on the latest source codes, the other is based on the latest official release. So we must cleanup all related things of the first e2e test before we run the second e2e test. And in `keadm deprecated e2e`, we'll use systemd to start edgecore, so we must cleanup edgecore.service also
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
cc @wackxu @fisherxu 
ptal

**Comment by wackxu** [comment]
we need merge this to solve the e2e failed asap

**Comment by gy95** [comment]
by test many times, it indeed works well...

**Pull request merged**
