### PR TITLE
fix missing protocol common config update

### LINKED ISSUE #2264: ProtocolCommonConfig failed to update
**What happened**:
Update a device with new ProtocolCommonConfig, deviceProfile in ConfigMap will show NULL.
(feedback by @sailorvii )

**What you expected to happen**:
Update ProtocolCommonConfig correctly.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a device with ProtocolCommonConfig
2.Update the device with new ProtocolCommonConfig

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

</details>

<details><summary>v.1.4</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

### PR DESCRIPTION
**Pull request by luogangyi**
**What type of PR is this?**

**What this PR does / why we need it**:
Update a device with new ProtocolCommonConfig, deviceProfile in ConfigMap will show NULL.

**Which issue(s) this PR fixes**:

Fixes #2264 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
Please add unit test or e2e test for device upgrade case.

**Comment by luogangyi** [comment]
> Please add unit test or e2e test for device upgrade case.

done

**Comment by luogangyi** [comment]
> Please add unit test or e2e test for device upgrade case.

done

**Comment by daixiang0** [comment]
lgtm

**Pull request merged**
