### PR TITLE
fix:fix-validate imageprepull crdexample,now it is use nodeNames not …

### PR DESCRIPTION
**Pull request by Piwriw**
**What type of PR is this?**
fix:fix-validate imageprepull crdexample,now it is use nodeNames not nodes
ref:https://github.com/kubeedge/kubeedge/blob/fed3fcdf466abcdbad4751963c08879cda753c10/build/crds/operations/operations_v1alpha1_imageprepulljob.yaml#L118

**What this PR does / why we need it**:
image

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Piwriw** [comment]
@Shelley-BaoYue I encountered a test CI error, but I don't know how to solve it, can you help me?

**Comment by Piwriw** [comment]
I encountered a test CI error, but I don't know how to solve it, can you help me @Shelley-BaoYue

**Review by wbc6080 — COMMENTED** [review]
You can retry the CI test by close and reopen the PR.

**Comment by Piwriw** [comment]
> You can retry the CI test by close and reopen the PR.

I try it，but still failed. Can you help me to check it ?

**Comment by wbc6080** [comment]
You can try it several times. This CI test does sometimes have a high failure rate. I tried to locate the problem before but haven't found the reason yet. Testing locally has always been successful, but for some reason the github action fails easily.

**Comment by Piwriw** [comment]
> You can try it several times. This CI test does sometimes have a high failure rate. I tried to locate the problem before but haven't found the reason yet. Testing locally has always been successful, but for some reason the github action fails easily.

It work， Thanks！！！

**Review by Shelley-BaoYue — COMMENTED** [review]
/approve

**Pull request merged**
