### PR TITLE
Link root changelog to ./CHANGELOG/README

### PR DESCRIPTION
**Pull request by snstaberah**
modify root changelog links to ./CHANGELOG/README
so we can avoid modify 2 same changelog index files in one project
Signed-off-by: snstaberah <yangyonglc@inspur.com>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
LGTM
Thanks

**Comment by zc2638** [comment]
Thanks for your contribution. 
And LGTM for me.

But I have a question, we already have a README in the CHANGELOG directory, do we still need to keep the CHANGELOG.md in the root directory?
@gy95 @fisherxu

**Comment by fisherxu** [comment]
> But I have a question, we already have a README in the CHANGELOG directory, do we still need to keep the CHANGELOG.md in the root directory?

Good idea, how about making the `CHANGELOG.md` in root link to README in the CHANGELOG directory as in k8s. @snstaberah @zc2638 

Ref:  https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md

**Comment by snstaberah** [comment]
> 

i think this is a better way to avoid maintain 2 changelog index file in one project，i have modified the commit，please take a look

**Comment by zc2638** [comment]
Maybe it's better to use file softlink?

**Comment by fisherxu** [comment]
> Maybe it's better to use file softlink?

`softlink` as in k8s will be better :)

**Comment by fisherxu** [comment]
@snstaberah Looks like it's not a softlink now, we need to run `ln -s CHANGELOG/README.md CHANGELOG.md` to create it.

**Comment by snstaberah** [comment]
> @snstaberah Looks like it's not a softlink now, we need to run `ln -s CHANGELOG/README.md CHANGELOG.md` to create it.

done，please take a look again

**Review by fisherxu — COMMENTED** [review]
/approve

cc @zc2638

**Pull request merged**
