### PR TITLE
Supports installing edgecore without installing the CNI plugin.

### PR DESCRIPTION
**Pull request by luomengY**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When running the container installation-package:v1.15.0 during keadm join, we use the hostNetwork mode to avoid users manually installing CNI plugins before this, which is also not logical.（https://github.com/kubeedge/kubeedge/issues/5195 ）

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubeedge/kubeedge/issues/5195

**Special notes for your reviewer**:
@fisherxu  @Shelley-BaoYue 
**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
Have you tested it with other runtimes? Like cri-docker, cri-o.

**Comment by luomengY** [comment]
> Have you tested it with other runtimes? Like cri-docker, cri-o.

I have tested the cri-docker and containerd, and I would like to know which cri-o versions are supported by kubeedge v1.15.0. My cri-o version is v1.23.0, and I found that the keadm join was executing a copy edgecore in the container and reported an error: cp: cannot create regular file '/tmp/usr/local/bin/edgecore': Permission denied.

**Comment by luomengY** [comment]
> > Have you tested it with other runtimes? Like cri-docker, cri-o.
> 
> I have tested the cri-docker and containerd, and I would like to know which cri-o versions are supported by kubeedge v1.15.0. My cri-o version is v1.23.0, and I found that the keadm join was executing a copy edgecore in the container and reported an error: cp: cannot create regular file '/tmp/usr/local/bin/edgecore': Permission denied.

I seem to have found the answer. When using CRI-O, we can solve this problem by turning off selinux, as shown in isuue: https://github.com/cri-o/cri-o/issues/5501 .

**Comment by ravaga** [comment]
> > Have you tested it with other runtimes? Like cri-docker, cri-o.
> 
> I have tested the cri-docker and containerd, and I would like to know which cri-o versions are supported by kubeedge v1.15.0. My cri-o version is v1.23.0, and I found that the keadm join was executing a copy edgecore in the container and reported an error: cp: cannot create regular file '/tmp/usr/local/bin/edgecore': Permission denied.

I successfully installed Kubeedge v1.15.0 using cri-o v1.24.6. I hope it could be helpful.

**Comment by luomengY** [comment]
> > > Have you tested it with other runtimes? Like cri-docker, cri-o.
> > 
> > 
> > I have tested the cri-docker and containerd, and I would like to know which cri-o versions are supported by kubeedge v1.15.0. My cri-o version is v1.23.0, and I found that the keadm join was executing a copy edgecore in the container and reported an error: cp: cannot create regular file '/tmp/usr/local/bin/edgecore': Permission denied.
> 
> I successfully installed Kubeedge v1.15.0 using cri-o v1.24.6. I hope it could be helpful.

Thank you. I have already resolved this issue .

**Comment by Shelley-BaoYue** [comment]
> > > Have you tested it with other runtimes? Like cri-docker, cri-o.
> > 
> > 
> > I have tested the cri-docker and containerd, and I would like to know which cri-o versions are supported by kubeedge v1.15.0. My cri-o version is v1.23.0, and I found that the keadm join was executing a copy edgecore in the container and reported an error: cp: cannot create regular file '/tmp/usr/local/bin/edgecore': Permission denied.
> 
> I successfully installed Kubeedge v1.15.0 using cri-o v1.24.6. I hope it could be helpful.

Maybe with this pr, we use the hostNetwork mode when we keadm join edgecore, there will be some wrong with cri-o runtime 😢    As @luomengY said, we need to turn off selinux, rignt?

**Comment by Shelley-BaoYue** [comment]
I have another question: Even if we use hostNetwork mode and join edgecore successfully, if we don't install cni plugin, are pods can be running on edgenodes successfully？

**Comment by luomengY** [comment]
> selinux

Yes, I think cri-o v1.23.0 has selinux turned off by default, and the latest version has it turned on by default. But when I see other containers running, such as cri docker, containerd, and isulad, selinux is disabled by default. There are two solutions here: ① close selinux directly.  ② add a parameter --selinux=false when cri-o starts. I have tested cri-o, cri-docker, containerd, and isuald, and they all operate normally.

**Comment by luomengY** [comment]
> I have another question: Even if we use hostNetwork mode and join edgecore successfully, if we don't install cni plugin, are pods can be running on edgenodes successfully？

If the pod chooses container network, users need to install CNI plugins such as Flanenl, Calico, etc. These installations are usually completed on the cloud through kubectl apply - f kube cni.yaml. However, the installation process of kubeedge should not involve dependencies related to CNI plugins, and this step should be completed after cluster deployment.

**Comment by luomengY** [comment]
> > > > Have you tested it with other runtimes? Like cri-docker, cri-o.
> > > 
> > > 
> > > I have tested the cri-docker and containerd, and I would like to know which cri-o versions are supported by kubeedge v1.15.0. My cri-o version is v1.23.0, and I found that the keadm join was executing a copy edgecore in the container and reported an error: cp: cannot create regular file '/tmp/usr/local/bin/edgecore': Permission denied.
> > 
> > 
> > I successfully installed Kubeedge v1.15.0 using cri-o v1.24.6. I hope it could be helpful.
> 
> Maybe with this pr, we use the hostNetwork mode when we keadm join edgecore, there will be some wrong with cri-o runtime 😢 As @luomengY said, we need to turn off selinux, rignt?



> > > > Have you tested it with other runtimes? Like cri-docker, cri-o.
> > > 
> > > 
> > > I have tested the cri-docker and containerd, and I would like to know which cri-o versions are supported by kubeedge v1.15.0. My cri-o version is v1.23.0, and I found that the keadm join was executing a copy edgecore in the container and reported an error: cp: cannot create regular file '/tmp/usr/local/bin/edgecore': Permission denied.
> > 
> > 
> > I successfully installed Kubeedge v1.15.0 using cri-o v1.24.6. I hope it could be helpful.
> 
> Maybe with this pr, we use the hostNetwork mode when we keadm join edgecore, there will be some wrong with cri-o runtime 😢 As @luomengY said, we need to turn off selinux, rignt?

The issue of CRI-O error is not related to the network mode used by hostNetwokr. It is necessary to consider the situation when CR opens selinux (issue: https://github.com/kubeedge/kubeedge/issues/5209 ）.In this PR, this issue has also been considered together. Currently, containerd, docker, and isulad all default to disabling selinux. CRI-O lower versions default to disabling, but higher versions default to opening, such as CRI-O v1.28.2. Therefore, I believe that opening selinux is worth considering.@Shelley-BaoYue  @fisherxu

**Comment by wbc6080** [comment]
Thanks for your contribution, you can execute `make verify` locally to make the CI check pass

**Comment by luomengY** [comment]
> Thanks for your contribution, you can execute `make verify` locally to make the CI check pass

I tried to execute make verify, but ended up stuck in the step of "running 'go mod vendor' for repo root".
52314de0816076417ae7b9ca93bdfeb

**Comment by luomengY** [comment]
> > Thanks for your contribution, you can execute `make verify` locally to make the CI check pass
> 
> I tried to execute make verify, but ended up stuck in the step of "running 'go mod vendor' for repo root". 52314de0816076417ae7b9ca93bdfeb

**Comment by wbc6080** [comment]
Yes, then you can run` git status `to find the changes by verify script. This script will verify and change dependencies, you need to commit and push the changes too.

**Comment by luomengY** [comment]
> Yes, then you can run`git status`to find the changes by verify script. This script will verify and change dependencies, you need to commit and push the changes too.

ok

**Comment by luomengY** [comment]
@Shelley-BaoYue @fisherxu

**Review by Shelley-BaoYue — COMMENTED** [review]
I believe this PR will help users to avoid a lot of trouble when installing edgecore. If it is merged, can we consider cherrp-pick it to the previous version?  @fisherxu

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by fisherxu** [comment]
Let's cherry-pick it to the release branch. @luomengY

**Pull request merged**
