### PR TITLE
remove not used kubeedge-version flag in keadm init command

### PR DESCRIPTION
**Pull request by gy95**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
remove not used kubeedge-version flag in keadm init command
this flag is never used, we can remove it(now we use --profile version=v1.10.1 to set image version)
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
`kubeedgeversion` should be a better name than `profile version`? cc @zhu733756

**Comment by gy95** [comment]
https://github.com/kubeedge/kubeedge/blob/821009caab97eb0f69f82b47463e8fdf62d5f9a0/keadm/cmd/keadm/app/cmd/cloud/init.go#L111-L114
now both `--profile` and `--set` are used to set deploy parameters, we may do some work to unify this.

**Comment by zhu733756** [comment]
> `kubeedgeversion` should be a better name than `profile version`? cc @zhu733756

Yes

**Comment by zhu733756** [comment]
> https://github.com/kubeedge/kubeedge/blob/821009caab97eb0f69f82b47463e8fdf62d5f9a0/keadm/cmd/keadm/app/cmd/cloud/init.go#L111-L114
> 
> 
> now both `--profile` and `--set` are used to set deploy parameters, we may do some more work to unify this.

Agree.  I think "--profile" includes the defined profiles such as external iptablesmgr and so on, "--set" is the function of helm. They do the same thing.

**Pull request closed without merging**
