### PR TITLE
Enabled install debug handlers to enable the logs feature

### PR DESCRIPTION
**Pull request by siredmar**
Signed-off-by: Armin Schlegel <armin.schlegel@gmx.de>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Enables the `kubectl logs` feature for edge nodes. 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by subpathdev** [comment]
\lgtm
thanks for fixing

**Comment by subpathdev** [comment]
@fisherxu I think we should add this in the next patch release.

**Comment by fisherxu** [comment]
> @fisherxu I think we should add this in the next patch release.

/approve
Sure, could you please cherry-pick the patch to release-1.8 branch with `hack\cherry_pick_pull.sh` script? @siredmar

**Comment by siredmar** [comment]
@fisherxu done. see #3134

**Pull request merged**
