### PR TITLE
Automated cherry pick of #2349: upgrade klog@0.4.0 to klog/v2@2.2.0

### PR DESCRIPTION
**Pull request by GsssC**
Cherry pick of #2349 on release-1.5.

#2349: upgrade klog@0.4.0 to klog/v2@2.2.0

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
Since the x86 CI checks have been moved to Github Actions, we shall probably cherry-pick the `.github/` things to release branches under support.

/cc @daixiang0

**Comment by daixiang0** [comment]
@kevin-wangzefeng Since Github Actions introduced after 1.5, if need it in 1.5, we need to cherry-pick it first.

**Comment by fisherxu** [comment]
> @kevin-wangzefeng Since Github Actions introduced after 1.5, if need it in 1.5, we need to cherry-pick it first.

We can cherry-pick them to 1.5

**Pull request merged**
