### PR TITLE
Fix external dependency repo link

### PR DESCRIPTION
**Pull request by liyuerich**
Signed-off-by: liyue <yue.li@daocloud.io>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by zc2638** [comment]
Thanks for your contribution.
Please sign off the commit first to resolve `DCO` errors.

**Comment by zc2638** [comment]
At present, all dependencies will be exported to the `vendor`, and the licenses of all dependencies are saved in `LICENSES`. I don't think this document is needed to record project dependencies. 
WDYT, @fisherxu

**Comment by fisherxu** [comment]
> At present, all dependencies will be exported to the `vendor`, and the licenses of all dependencies are saved in `LICENSES`. I don't think this document is needed to record project dependencies. WDYT, @fisherxu

Yes, this file is needed by CNCF, we can check whether it's still needed now.

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
