### PR TITLE
remove unnecessary type check

### PR DESCRIPTION
**Pull request by zc2638**
Signed-off-by: zc <zc2638@qq.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

the same as https://github.com/istio/istio/pull/36787

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
Is this introduced in go1.17? but now we are using gol.16

**Comment by zc2638** [comment]
> Is this introduced in go1.17? but now we are using gol.16

the same as go 1.16

**Comment by zc2638** [comment]
The `embed` feature was introduced in go version 1.16.
@gy95

**Comment by zhu733756** [comment]
LGTM

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
