### PR TITLE
cleanup edgemesh

### LINKED ISSUE #1037: edgemesh has redundant code that needs to be cleanup
**What happened**:
- The initialization operation is done twice in cmd/edgemesh.go and pkg/server/server.go, cmd/edgemesh.go is redundant.
- No need to init HystrixConfig when go-chassis upgrade to v1.6.1

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: v1.0.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by anyushun**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

/kind cleanup

**What this PR does / why we need it**:
1. everything init in pkg/server/server.go, so cmd/edgemesh.go no need
do it
2. go-chassis upgrade to v1.6.1, no need to init HystrixConfig now

**Which issue(s) this PR fixes**: 

Fixes #1037 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by sids-b** [comment]
@anyushun , have we upgraded the go-chassis in our vendor code ?

Can you please run edgemesh manually and confirm if it works fine ? Since we currently dont have e2e for edgemesh

**Comment by anyushun** [comment]
> @anyushun , have we upgraded the go-chassis in our vendor code ?
> 
> Can you please run edgemesh manually and confirm if it works fine ? Since we currently dont have e2e for edgemesh

Hello Sid: I have test it, it works fine, thanks for your review

**Comment by tianxiaoliang** [comment]
LGTM

**Comment by sids-b** [comment]
Thanks @anyushun 

/approve

**Pull request merged**
