### PR TITLE
fix edgeconfig nodeLabels converted to kubelet nodeLabels

### LINKED ISSUE #4280: How to use nodeLabels in edgecore config
**What happened and what you expected to happen**:

I have added nodeLabels to the edgecore config:

    edged:

      nodeLabels:
        nodetype: edgeDevice
           
However, when I list labels using:

   kubectl get nodes --show-labels

I cannot see the nodetype label, have I added nodeLabels into the correct bit?

**How to reproduce it (as minimally and precisely as possible)**:

Add nodeLabels into edgecore config

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

Latest from github head.

### PR DESCRIPTION
**Pull request by hexiaodai**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix edgeconfig nodeLabels converted to kubelet nodeLabels

**Which issue(s) this PR fixes**:

Fixes #4280

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wackxu** [comment]
Please signoff the commit to fix the failed DCO test, thx :)

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
