### PR TITLE
cloud/leaderelection: fix recorder

### PR DESCRIPTION
**Pull request by Iceber**
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
The recorder not started

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Iceber** [comment]
/kind feature
send event to kubernetes

**Comment by daixiang0** [comment]
lgtm

**Review by GsssC — APPROVED** [review]

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by fisherxu** [comment]
@Iceber Please rebase the PR :)

**Comment by Iceber** [comment]
@fisherxu rebased, need lgtm.

**Pull request merged**
