### PR TITLE
docker: Build everything in container

### PR DESCRIPTION
**Pull request by rzr**
As the date of today this trivial dockerfile
only serve for development purposes
(on controled reference environement).

On benefit of using a top level Dockerfile,
is that the project can be built from URL
without manually cloning source:

```sh
docker build https://github.com/tizenteam/kubeedge.git
```

Official golang image in debian-10 flavour
is currenly used as base which is closer to what developer might use.

For deployment, consider to use per applications smaller images.
(./build/*/Dockerfile).

This docker file will be improved,
once my other pending packaging patches are merged.

Change-Id: Id7e6045aa049bd531e08c0c3ad3e137974751e9c
Relate-to: https://github.com/kubeedge/kubeedge/issues/1246
Signed-off-by: Philippe Coval <rzr@users.sf.net>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by rzr** [comment]
Patch rebased

/assign @m1093782566

**Comment by rzr** [comment]
Please 1st review:
https://github.com/kubeedge/kubeedge/pull/1237#

**Comment by daixiang0** [comment]
It is cover by #1698

**Comment by rzr** [comment]
well a top level docker file would help but anyway it depends on:
https://github.com/kubeedge/kubeedge/pull/1237

**Pull request closed without merging**
