### PR TITLE
Added tests for `keadm beta` and `cloud` packages

### PR DESCRIPTION
**Pull request by 1Shubham7**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

I have added unit tests for the `keadm/cmd/keadm/app/cmd/beta` and `cloud` package

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by 1Shubham7** [comment]
please review @WillardHu :)

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
