### PR TITLE
keadm: support the installation of cloudcore in systemd

### PR DESCRIPTION
**Pull request by zc2638**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
To stop the cloudcore, we maybe also need to modify the function synchronously.
maybe here 😂 
https://github.com/kubeedge/kubeedge/blob/c3dd45071f5963ece6046528ad03076aa2fe9a42/keadm/cmd/keadm/app/cmd/util/common.go#L365-L373

**Comment by zc2638** [comment]
> To stop the cloudcore, we maybe also need to modify the function synchronously. maybe here 😂
> 
> https://github.com/kubeedge/kubeedge/blob/c3dd45071f5963ece6046528ad03076aa2fe9a42/keadm/cmd/keadm/app/cmd/util/common.go#L365-L373

I will do it.

**Review by fisherxu — COMMENTED** [review]
I think we can modify to install cloudcore as container?

**Comment by fisherxu** [comment]
Now we already support helm installation, is it possible to use helm in keadm？

**Comment by zc2638** [comment]
Perhaps helm has become a standard for k8s application deployment, 
but I think there are still a large number of people who don’t use helm or even understand helm. 
And some people don’t like to use helm.

More discussion may be needed here, and keadm may be changed widely?

**Comment by fisherxu** [comment]
> More discussion may be needed here, and keadm may be changed widely?

Yes, I think whether using helm or not, cloudcore should be deployed as ccontainer, how do you think? :) @zc2638 @zhu733756

**Comment by zhu733756** [comment]
> > More discussion may be needed here, and keadm may be changed widely?
> 
> Yes, I think whether using helm or not, cloudcore should be deployed as ccontainer, how do you think? :) @zc2638 @zhu733756

I think container deployment is preferred for security reasons, However, as an open-source project, we can offer a variety of alternatives.

**Comment by zc2638** [comment]
My idea is that `kubeedge` is based on `k8s`, so we can support native resource deployment and helm deployment at the same time.
Process deployment may not be preferred here, but we can provide responsive documents to support process deployment.

**Comment by zc2638** [comment]
will refactor keadm in #3475.
/close

**Pull request closed without merging**
