### PR TITLE
Added tests for `cloud/pkg/csidriver` pkg

### PR DESCRIPTION
**Pull request by 1Shubham7**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

I have added unit tests for the `cloud/pkg/csidriver` module

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by WillardHu** [comment]
Please merge your commits into one.

**Comment by 1Shubham7** [comment]
> Please merge your commits into one.

done

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
