### PR TITLE
fix device compile error

### PR DESCRIPTION
**Pull request by JiaweiGithub**
Signed-off-by: jiawei <jiawei.liu@daocloud.io>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
obviously those are undefined arguments, lgtm with green CI.

**Review by wbc6080 — COMMENTED** [review]
Thanks for finding this bug. By the way, can we also put `otel` into the `case` below? Can make the code clearer.
image

**Comment by JiaweiGithub** [comment]
> otel

Good idea. I read the otel related code. This requires making some changes to the original code, which is a bit of work. I can try it when I have time.

**Comment by JiaweiGithub** [comment]
> Thanks for finding this bug. By the way, can we also put `otel` into the `case` below? Can make the code clearer.感谢您发现这个错误。顺便问一下，我们是否也可以将`otel`放入下面的`case`中？可以让代码更加清晰。 image

This requires some adjustments to the original otel code. Do you have time to look at this issue?
@forsaken628

**Review by wbc6080 — COMMENTED** [review]
/lgtm
And we need to cherry-pick to release-1.19 after merged

**Pull request merged**
