### PR TITLE
trigger fossa ci on every pr

### PR DESCRIPTION
**Pull request by gy95**
**What type of PR is this?**
trigger fossa ci on every pr, but not only on PRs of master branch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by vincentgoat — COMMENTED** [review]
Fossa ci currently supports github action integration, can you do the integration also?
https://github.com/marketplace/actions/official-fossa-action

**Comment by gy95** [comment]
> Fossa ci currently supports github action integration, can you do the integration also? https://github.com/marketplace/actions/official-fossa-action

Good catch

**Comment by gy95** [comment]
the second commit is related to fossa action, PTAL  @vincentgoat

**Review by vincentgoat — COMMENTED** [review]
lgtm

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
