### PR TITLE
build: Install more files in system dirs

### PR DESCRIPTION
**Pull request by rzr**
Links to /etc are added for compatility

Change-Id: I5c2359f31834886e85dc8c4fb1bdb50ac056438c
Forwarded: https://github.com/kubeedge/kubeedge/pull/1237#
Relate-to: https://github.com/kubeedge/kubeedge/issues/1246
Origin: https://github.com/CrossStream/kubeedge/
Last-update: 2020-10-23
Signed-off-by: Philippe Coval <rzr@users.sf.net>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
I'd like to support `installPath` option in keadm, since `make` is usually for contributors.

**Comment by rzr** [comment]
This change is part if debian packaging efforts

**Comment by daixiang0** [comment]
Not sure, pachaging can be done in temp dir to package them into a deb package.

**Comment by rzr** [comment]
I have rebased on current master and solved conflicts

/assign @qizha

yes this change is desirable to ease packaging job
at least for a generic profile

I might also open a ticket debian side to request for new package
once some of my changes to build a snapshot package are merged here

**Pull request closed without merging**
