### PR TITLE
[cloudHub] move some helper function to package common

### PR DESCRIPTION
**Pull request by wackxu**
Signed-off-by: wackxu <xushiwei5@huawei.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

split https://github.com/kubeedge/kubeedge/pull/4105 into serveral small pr

in https://github.com/kubeedge/kubeedge/pull/4105 Cloudhub refactor implementation, we do some refactor to make the cloudhub layering clearer and more robust. In that PR, we move serveral helper function to the common package,  but it will make the CIFUZZ unhappy, because the CIFUZZ will run the fuzz that according to the code package, such as fuzz_volume_regexp， in https://github.com/cncf/cncf-fuzzing/blob/main/projects/kubeedge/build.sh

```
cp $SRC/cncf-fuzzing/projects/kubeedge/cloudhub_messagehandler_fuzzer.go $SRC/kubeedge/cloud/pkg/cloudhub/handler/
compile_go_fuzzer github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/handler FuzzVolumeRegExp fuzz_volume_regexp
```

we move the VolumeRegExp to the common package so the CIFUZZ will failed. 

So we extract this pr and modify the fuzz check rules in https://github.com/cncf/cncf-fuzzing/blob/main/projects/kubeedge/ to make fuzz happy 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wackxu** [comment]
we need merge this asap since we have updated the fuzz code in https://github.com/cncf/cncf-fuzzing/pull/227, otherwise other pr will run CIFUZZ failed

**Review by vincentgoat — COMMENTED** [review]
lgtm

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
