### PR TITLE
Workflows updated in main.yml

### LINKED ISSUE #5182: Add CI test case for different runtimes
**What would you like to be added/modified**: 

Add tests for more commonly used runtimes like cri-o, docker. 

- [ ] Add a new job and define CONTAINER_RUNTIME in the matrix as either cri-o or docker (also update CONTAINER_RUNTIME to containerd on line 229).
- [ ] Currently, "make e2e" installs kubeedge using the `hack/local-up-kubeedge.sh`, which only supports containerd. It needs to be modified to support installation with different runtime types depend on the CONTAINER_RUNTIME value.
- [ ] When using docker, cri-dockerd also needs to be installed. Therefore, steps for installing cri-dockerd should be included.

**Why is this needed**: 

Now the KubeEdge CI only use containerd as runtime to test, we need to add more test for commonly used runtimes so that we can ensure KubeEdge run properly with different runtimes.

### PR DESCRIPTION
**Pull request by heysourin**
Added tests for runtimes like cri-o, docker.
Tries to fix #5182

### CODE REVIEW

**Comment by WillardHu** [comment]
Thanks for your contribution, is it not good to install three container runtimes in the basic environment, and is it better to use the matrix method?

**Comment by Shelley-BaoYue** [comment]
Sorry, maybe I didn't provide a clear introduction to the requirements earlier. I hope we can add another action, similar to the other E2e_test. Currently, the E2e_test uses containerd as the runtime. We need to create a new action that installs cri-o, selects the websocket protocol, chooses Kubernetes version 1.26, and then executes "make e2e".

**Comment by Shelley-BaoYue** [comment]
The error with DCO needs to be addressed as well. Please use "-s" when git commit.

**Comment by heysourin** [comment]
Hi @WillardHu, you mean I should create a new job `test`? which will look like this:
```
jobs:
.
.
.
 test:
   runs-on: ubuntu-22.04
   strategy:
     matrix:
       container-runtime: [cri-o, docker]
   steps:
     - name: Install ${{ matrix.container-runtime }}
       run: |
         if [ "${{ matrix.container-runtime }}" == "cri-o" ]; then
           sudo apt update
           sudo apt install -y cri-o cri-o-runc
           sudo systemctl start crio
           sudo systemctl enable crio
         elif [ "${{ matrix.container-runtime }}" == "docker" ]; then
           sudo apt-get update
           sudo apt-get install \
               apt-transport-https \
               ca-certificates \
               curl \
               gnupg \
               lsb-release
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
           echo \
             "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update
           sudo apt-get install docker-ce docker-ce-cli containerd.io
```
           
Right?

**Comment by WillardHu** [comment]
> Hi @WillardHu, you mean I should create a new job `test`? which will look like this:
> ...
> Right?

Yeah, you can talk to Shelley about how this matrix should be designed.  @Shelley-BaoYue

**Comment by heysourin** [comment]
Hi @Shelley-BaoYue, can you please guide me a bit?

**Comment by Shelley-BaoYue** [comment]
> Hi @WillardHu, you mean I should create a new job `test`? which will look like this:
> 
> ```
> jobs:
> .
> .
> .
>  test:
>    runs-on: ubuntu-22.04
>    strategy:
>      matrix:
>        container-runtime: [cri-o, docker]
>    steps:
>      - name: Install ${{ matrix.container-runtime }}
>        run: |
>          if [ "${{ matrix.container-runtime }}" == "cri-o" ]; then
>            sudo apt update
>            sudo apt install -y cri-o cri-o-runc
>            sudo systemctl start crio
>            sudo systemctl enable crio
>          elif [ "${{ matrix.container-runtime }}" == "docker" ]; then
>            sudo apt-get update
>            sudo apt-get install \
>                apt-transport-https \
>                ca-certificates \
>                curl \
>                gnupg \
>                lsb-release
>            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
>            echo \
>              "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
>              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
>            sudo apt-get update
>            sudo apt-get install docker-ce docker-ce-cli containerd.io
> ```
> 
> Right?

Yes!

**Comment by Shelley-BaoYue** [comment]
I think there are several tasks involved here. I will update these tasks in issue #5182, and you can choose to claim one or multiple tasks if you'd like.

- [ ] Add a new job and define CONTAINER_RUNTIME in the matrix as either cri-o or docker (also update CONTAINER_RUNTIME to containerd on line 229).
- [ ] Currently, "make e2e" installs kubeedge using the `hack/local-up-kubeedge.sh`, which only supports containerd. It needs to be modified to support installation with different runtime types depend on the CONTAINER_RUNTIME value.
- [ ] When using docker, cri-dockerd also needs to be installed. Therefore, steps for installing cri-dockerd should be included.

**Comment by heysourin** [comment]
@Shelley-BaoYue  Okay thanks, I am closing this.

**Pull request closed without merging**
