### PR TITLE
refactor e2e directory

### PR DESCRIPTION
**Pull request by wackxu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
It works depend on https://github.com/kubeedge/kubeedge/pull/4398
Refactor the e2e directory to make the directory structure more reasonable

```
├── e2e
│   ├── apps
│   │   ├── deployment.go
│   │   └── framework.go
│   ├── constants
│   │   └── constants.go
│   ├── device
│   │   ├── device.go
│   │   └── framework.go
│   ├── e2e.go
│   ├── e2e_test.go
│   ├── OWNERS
│   ├── rule
│   │   ├── framework.go
│   │   └── rule.go
│   ├── testsuite
│   │   └── testsuite.go
│   └── utils
│       ├── common.go
│       ├── config.go
│       ├── context.go
│       ├── device.go
│       ├── log.go
│       ├── node.go
│       ├── pod.go
│       ├── rule.go
│       └── timer.go
├── e2e_edgesite
│   ├── edgesite_suite_test.go
│   └── edgesite_test.go
├── e2e_keadm
│   ├── keadm_suite_test.go
│   └── keadm_test.go
├── integration
│   ├── framework
│   │   └── util.go
│   └── metaserver
│       ├── access_test.go
│       └── main_test.go
├── OWNERS
└── scripts
    ├── cleanup.sh
    ├── compile.sh
    ├── execute.sh
    ├── fast_test.sh
    ├── generate_cert.sh
    ├── keadm_deprecated_e2e.sh
    └── keadm_e2e.sh

```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
LGTM

**Review by vincentgoat — COMMENTED** [review]
Need to rebase. Then /lgtm

**Pull request closed without merging**
