### PR TITLE
delete unwanted labels

### PR DESCRIPTION
**Pull request by allenleu**
Confirm that this tag needs to be deleted

### CODE REVIEW

**Comment by fisherxu** [comment]
Please signoff the commit with cmd below to fix the failed DCO CI :)
```
git commit --amend --no-edit --signoff
git push --force-with-lease origin dev
```

**Comment by allenleu** [comment]
> Please signoff the commit with cmd below to fix the failed DCO CI :)
> 
> ```
> git commit --amend --no-edit --signoff
> git push --force-with-lease origin dev
> ```

ok

> Please signoff the commit with cmd below to fix the failed DCO CI :)
> 
> ```
> git commit --amend --no-edit --signoff
> git push --force-with-lease origin dev
> ```

ok

**Comment by allenleu** [comment]
> Please signoff the commit with cmd below to fix the failed DCO CI :)
> 
> ```
> git commit --amend --no-edit --signoff
> git push --force-with-lease origin dev
> ```

ok

**Review by fisherxu — COMMENTED** [review]
/approve

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Pull request merged**
