### PR TITLE
fix use certificate from local directory problem

### PR DESCRIPTION
**Pull request by threestoneliu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
when use certificate from local dirctory，there have two problem
1. cloudcore won't create cloudcoresecrect
2. tunnel server cert/key file was not decode

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
cc @ls889 @XJangel

**Comment by ls889** [comment]
@threestoneliu @fisherxu Thanks for pointing out and revising. it seems good

**Comment by threestoneliu** [comment]
@ls889 In the cloudcore.yaml configuration file, is the tunnel server's certificate still allowed to be configured?

**Comment by ls889** [comment]
@threestoneliu  yes,  tunnel server's certificate is allowed to be configured. and now we usually configure tunnel certs using the same certs with edgecore's.

**Pull request merged**
