### PR TITLE
Fix 'kubectl/edgecore' command in 'bug-report.md'

### PR DESCRIPTION
**Pull request by llhuii**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
lgtm

**Review by GsssC — COMMENTED** [review]
/lgtm

**Pull request merged**
