### PR TITLE
edgecontroller: improve test coverage

### LINKED ISSUE #2239: cloud/pkg/edgecontroller/manager: improve the test coverage
Add more tests to import test coverage. Details refer to #2110 .

### PR DESCRIPTION
**Pull request by gccio**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:
improve edgecontroller test coverage

**Which issue(s) this PR fixes**:

Ref: #2239 

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by daixiang0** [comment]
Please share test coverage with those changes.

**Comment by gccio** [comment]
> Please share test coverage with those changes.

```
$ git diff
diff --git a/hack/lib/golang.sh b/hack/lib/golang.sh
index 9bba8e1e..10569a7a 100755
--- a/hack/lib/golang.sh
+++ b/hack/lib/golang.sh
@@ -434,5 +434,5 @@ kubeedge::golang::run_test() {
     testdirs+=("${KUBEEDGE_ALL_TESTCASES[@]}")
   fi

-  go test ${testdirs[@]}
+  go test -coverprofile=./coverprofile.cov ${testdirs[@]}
 }

$ https_proxy=127.0.0.1:7890 make test
hack/make-rules/clean.sh
hack/make-rules/test.sh
running tests cases
ok      github.com/kubeedge/kubeedge/cloud/pkg/cloudhub/common/model    0.047s  coverage: 96.8% of statements
ok      github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/config    0.019s  coverage: 100.0% of statements
ok      github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager   0.049s  coverage: 99.5% of statements
ok      github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer      0.006s  coverage: 100.0% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/edgehub/clients/wsclient  0.095s  coverage: 2.8% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/edgehub/common/http       0.240s  coverage: 36.7% of statements
[sudo] password for gccio:
ok      github.com/kubeedge/kubeedge/edge/pkg/edgehub   22.021s coverage: 59.2% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/servicebus/util   0.033s  coverage: 60.6% of statements
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:125322:10: warning: function may return address of local variable [-Wreturn-local-addr]
125322 |   return pNew;
       |          ^~~~
sqlite3-binding.c:125282:10: note: declared here
125282 |   Select standin;
       |          ^~~~~~~
ok      github.com/kubeedge/kubeedge/edge/pkg/metamanager/dao   0.017s  coverage: 100.0% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/metamanager       63.026s coverage: 60.9% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/eventbus/dao      0.022s  coverage: 100.0% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/eventbus/common/util      0.028s  coverage: 65.9% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtclient       0.034s  coverage: 96.1% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtcommon       0.006s  coverage: 100.0% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dttype 0.032s  coverage: 95.4% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmodule       0.006s  coverage: 55.6% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/devicetwin        0.016s  coverage: 82.2% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager      51.058s coverage: 85.6% of statements
ok      github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtcontext      0.004s  coverage: 93.8% of statements
ok      github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/debug      0.034s  coverage: 3.1% of statements
ok      github.com/kubeedge/kubeedge/keadm/cmd/keadm/app/cmd/util       2.521s  coverage: 6.9% of statements

$ go tool cover -func=./coverprofile.cov | grep edgecontroller
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/config/config.go:19:              InitConfigure                   100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/common.go:19:             obj2Event                       100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/common.go:29:             OnAdd                           100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/common.go:34:             OnUpdate                        100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/common.go:39:             OnDelete                        100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/common.go:44:             NewCommonResourceEventHandler   100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/configmap.go:19:          Events                          100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/configmap.go:24:          NewConfigMapManager             100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/endpoint.go:19:           Events                          100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/endpoint.go:24:           NewEndpointsManager             100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:28:           PodConfigMapsAndSecrets         100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:55:           newNodes                        100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:65:           AddOrUpdatePod                  100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:97:           ConfigMapNodes                  100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:109:          SecretNodes                     100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:121:          IsEdgeNode                      100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:127:          GetNodeStatus                   100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:134:          UpdateEdgeNode                  100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:139:          DeleteConfigMap                 100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:144:          DeleteSecret                    100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:149:          DeleteNode                      100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:154:          AddOrUpdateService              100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:159:          DeleteService                   100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:164:          GetAllServices                  100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:177:          GetService                      100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:187:          AddOrUpdateServicePods          100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:192:          DeleteServicePods               100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:197:          GetServicePods                  100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:207:          AddOrUpdateEndpoints            100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:212:          DeleteEndpoints                 100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:217:          IsEndpointsUpdated              100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/location.go:235:          GetAllEndpoints                 100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/node.go:23:               Events                          100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/node.go:28:               NewNodesManager                 100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/pod.go:36:                isPodUpdated                    100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/pod.go:45:                merge                           94.4%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/pod.go:78:                Events                          100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/pod.go:83:                NewPodManager                   100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/secret.go:19:             Events                          100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/secret.go:24:             NewSecretManager                100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/service.go:19:            Events                          100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/manager/service.go:24:            NewServiceManager               100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/context.go:24:       Send                            100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/context.go:30:       Receive                         100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/context.go:35:       Response                        100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/context.go:45:       NewContextMessageLayer          100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/util.go:16:          BuildResource                   100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/util.go:37:          GetNodeID                       100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/util.go:46:          GetNamespace                    100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/util.go:69:          GetResourceType                 100.0%
github.com/kubeedge/kubeedge/cloud/pkg/edgecontroller/messagelayer/util.go:93:          GetResourceName                 100.0%
```

**Comment by daixiang0** [comment]
please rebase until #2487 merged.

**Comment by daixiang0** [comment]
lgtm

**Comment by fisherxu** [comment]
Need to fix the ci failure :)

**Comment by fisherxu** [comment]
Looks good, could you please add the license header for all the files? @gccio

**Comment by gccio** [comment]
> Need to fix the ci failure :)

fixed.

> Looks good, could you please add the license header for all the files? @gccio

Done

**Pull request merged**
