### PR TITLE
delete unwanted mutex

### PR DESCRIPTION
**Pull request by elementyang**
Generally speaking, only data synchronization is needed, not function synchronization. So we need to remove unnecessary function synchronization.

### CODE REVIEW

**Comment by fisherxu** [comment]
@elementyang Thanks for the fixing :) And `sendToCloud` is called by two goroutine `routeToCloud` and `keepalive`, if we have no the mutex here, edgecore will panic occasionally.

**Comment by elementyang** [comment]
@fisherxu Thanks.
I known sendToCloud and eh.chClient.Send(message) are called by routeToCloud and keepalive. But sendToCloud and eh.chClient.Send() are function, and they should exist in every goroutine. So there is no need to synchronize functions, only need to synchronize data.

**Comment by fisherxu** [comment]
With this patch, we need to test whether edgecore will panic in a little long period.

**Comment by elementyang** [comment]
@fisherxu 
Thanks!

**Comment by elementyang** [comment]
Generally speaking, only data synchronization is needed, not function synchronization. So we need to remove unnecessary function synchronization.
Please check it. 
Thanks.

**Pull request closed without merging**
