### PR TITLE
Fixed failure to run unit-tests on non-Linux

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

I get an error when I run unit tests on the non-Linux system(Mac OS), the error message is:
```
# github.com/vishvananda/netlink/nl
/Users/willardhu/dev/gomods/github.com/kubeedge/kubeedge/vendor/github.com/vishvananda/netlink/nl/parse_attr.go:26:9: undefined: rtaAlignOf
/Users/willardhu/dev/gomods/github.com/kubeedge/kubeedge/vendor/github.com/vishvananda/netlink/nl/parse_attr.go:43:23: undefined: NLA_F_NESTED
/Users/willardhu/dev/gomods/github.com/kubeedge/kubeedge/vendor/github.com/vishvananda/netlink/nl/parse_attr.go:44:57: undefined: NLA_TYPE_MASK
/Users/willardhu/dev/gomods/github.com/kubeedge/kubeedge/vendor/github.com/vishvananda/netlink/nl/parse_attr.go:53:15: undefined: NLA_F_NET_BYTEORDER
/Users/willardhu/dev/gomods/github.com/kubeedge/kubeedge/vendor/github.com/vishvananda/netlink/nl/parse_attr.go:62:15: undefined: NLA_F_NET_BYTEORDER
FAIL	github.com/kubeedge/kubeedge/pkg/util [build failed]
```
This is because functions in the package `github.com/vishvananda/netlink` that are intended for Linux.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by WillardHu** [comment]
PTAL @Shelley-BaoYue

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by WillardHu** [comment]
> Plz cherry-pick to release-1.17, thanks :) @WillardHu

Done, thanks

**Pull request merged**
