### PR TITLE
admission: handle errors the right way

### PR DESCRIPTION
**Pull request by orangegzx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Need to fix the failed DCO test.

**Comment by gy95** [comment]
please rebase to the master to fix Travis CI

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
