### PR TITLE
add _tmp to gitignore

### PR DESCRIPTION
**Pull request by zhijianli88**
it's created by hack/verify-vendor-licenses.sh. Though we can update hack/verify-vendor-licenses.sh
to clean up this directory at exiting, we prefer to keep it being same with
https://github.com/kubernetes/kubernetes/blob/master/hack/verify-vendor-licenses.sh#L32

Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
@zhijianli88 Thanks for the pr, and here we keep same as K8s upstream, ref: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-vendor-licenses.sh#L32, we should add `_tmp` to `.gitignore`.

**Comment by daixiang0** [comment]
+1

**Comment by daixiang0** [comment]
lgtm

**Pull request merged**
