### PR TITLE
Refactor KubeEdge architecture diagram

### LINKED ISSUE #1319: Architecture diagram “edge part”  is "edge core"
**What would you like to be added/modified**:
Architecture diagram “edge part”  is "edge core"
https://github.com/kubeedge/kubeedge/blob/master/docs/images/kubeedge_arch.png
**Why is this needed**:
"edge core" is proper for KubeEdge.

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1319

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sids-b** [comment]
Looks nice... please squash the commits

/approve

**Comment by fisherxu** [comment]
@sids-b  I'm still resizing it in readme :)

**Comment by fisherxu** [comment]
Preview link: https://github.com/fisherxu/kubeedge/tree/refactor-arch#architecture
/hold
cc @kevin-wangzefeng @sids-b  @kadisi @chendave @subpathdev @du2016 @cwl233 @FengyunPan2  ptal :)

**Comment by fisherxu** [comment]
cc @ccccbjcn

**Comment by kevin-wangzefeng** [comment]
s/ContainerD/containerd/, ref: https://containerd.io/
s/Cri-O/CRI-O/, ref:https://cri-o.io/

**Comment by fisherxu** [comment]
> s/ContainerD/containerd/, ref: https://containerd.io/
s/Cri-O/CRI-O/, ref:https://cri-o.io/

Done.

**Comment by ccccbjcn** [comment]
Great.

**Pull request merged**
