### PR TITLE
fix keadm issue

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix keadm issue when installing edgecore

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fisherxu** [comment]
Not sure how the ci passed before...

**Comment by Abirdcfly** [comment]
> Not sure how the ci passed before...

[Log](https://github.com/kubeedge/kubeedge/pull/2585/checks?check_run_id=1977442229#step:6:47) shows previous pr version use version 1.5.0.code shows it is from https://kubeedge.io/latestversion
  and 1.5.0 edgecore.service is /etc/kubeedge/edgecore [source code](https://github.com/kubeedge/kubeedge/blob/release-1.5/build/tools/edgecore.service#L6) so it has no error. 
but why this pr ci paas....I have no idea.
/retest

**Comment by fisherxu** [comment]
> > Not sure how the ci passed before...
> 
> [Log](https://github.com/kubeedge/kubeedge/pull/2585/checks?check_run_id=1977442229#step:6:47) shows previous pr version use version 1.5.0.code shows it is from https://kubeedge.io/latestversion
> and 1.5.0 edgecore.service is /etc/kubeedge/edgecore [source code](https://github.com/kubeedge/kubeedge/blob/release-1.5/build/tools/edgecore.service#L6) so it has no error.
> but why this pr ci paas....I have no idea.
> /retest

Get it @Abirdcfly  Before release 1.6, like release 1.5, the binary path in edgecore.service is /etc/kubeedge/edgecore, keadm will download the service file from 1.5 release branch, so keadm can install successfully.

From release 1.6. the binary path in edgecore.service changed, keadm still use the path before, so ci failed.

**Pull request merged**
