### PR TITLE
change log level for err info

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
Signed-off-by: Shelley-BaoYue <baoyue2@huawei.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
use Errorf to print err info 

**Which issue(s) this PR fixes**:
Fixes #

### CODE REVIEW

**Review by wackxu — COMMENTED** [review]
lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Pull request merged**
