### PR TITLE
clean up `io/ioutil` for new go version

### PR DESCRIPTION
**Pull request by Fish-pro**
Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

"io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.
https://go.dev/doc/go1.16#ioutil

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by gy95 — COMMENTED** [review]
lgtm, we'd better add this deprecated package to golangci-lint check lists

**Comment by fisherxu** [comment]
> lgtm, we'd better add this deprecated package to golangci-lint check lists

Sounds good, golangci-lint can check it now? And are there any other checks like it? @gy95

**Comment by Fish-pro** [comment]
> > lgtm, we'd better add this deprecated package to golangci-lint check lists
> 
> Sounds good, golangci-lint can check it now? And are there any other checks like it? @gy95

@fisherxu `staticcheck` can check it in golangci-lint
```bash
test.go:3:8: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
import "io/ioutil"
```

**Comment by gy95** [comment]
so, let's add staticcheck to golangci-lint config :)

**Comment by Fish-pro** [comment]
> so, let's add staticcheck to golangci-lint config :)

@gy95 

After adding `staticcheck` for `golangci-lint`, there are a lot of things that need to be changed. Can I add them in the new pr?

```bash
➜  kubeedge git:(master) ✗ ./bin/golangci-lint  run -c .golangci.yml
edge/pkg/devicetwin/dmiclient/client.go:63:57: SA1019: grpc.WithDialer is deprecated: use WithContextDialer instead.  Will be supported throughout 1.x. (staticcheck)
        conn, err := grpc.Dial(dc.socket, grpc.WithInsecure(), grpc.WithDialer(dialer))
                                                               ^
edge/pkg/devicetwin/dttype/types_helper_test.go:682:2: SA4006: this value of `resultDealTypeTwin` is never used (staticcheck)
        resultDealTypeTwin := make(map[string]*MsgTwin)
        ^
edge/pkg/devicetwin/dttype/types_helper_test.go:954:2: SA4006: this value of `delta` is never used (staticcheck)
        delta := make(map[string]string)
        ^
edge/test/integration/utils/helpers/helpers.go:161:2: SA5001: should check returned error before deferring row.Close() (staticcheck)
        defer row.Close()
        ^
edge/test/integration/utils/helpers/helpers.go:197:2: SA5001: should check returned error before deferring row.Close() (staticcheck)
        defer row.Close()
        ^
edge/test/integration/utils/helpers/helpers.go:160:2: SA4006: this value of `err` is never used (staticcheck)
        row, err := db.Query("SELECT * FROM device_twin")
        ^
edge/test/integration/utils/helpers/helpers.go:196:2: SA4006: this value of `err` is never used (staticcheck)
        row, err := db.Query("SELECT * FROM device_attr")
        ^
edge/pkg/eventbus/common/util/common.go:60:2: SA4006: this value of `tlsConfig` is never used (staticcheck)
        tlsConfig := &tls.Config{}
        ^
cloud/pkg/csidriver/controllerserver.go:26:2: SA1019: package github.com/golang/protobuf/jsonpb is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead. (staticcheck)
        "github.com/golang/protobuf/jsonpb"
        ^
edge/pkg/devicetwin/dtmanager/membership.go:182:3: SA4006: this value of `deviceInstance` is never used (staticcheck)
                deviceInstance, isDeviceExist := context.GetDevice(device.ID)
                ^
edge/pkg/devicetwin/dtmanager/twin.go:242:2: SA4006: this value of `result` is never used (staticcheck)
        result := []byte("")
        ^
edge/pkg/devicetwin/dtmanager/twin.go:296:2: SA4006: this value of `msg` is never used (staticcheck)
        msg := []byte("")
        ^
keadm/cmd/keadm/app/cmd/debug/check.go:374:2: SA4006: this value of `err` is never used (staticcheck)
        vMax, err := strconv.ParseFloat(rMax, 32)
        ^
keadm/cmd/keadm/app/cmd/debug/check.go:375:2: SA4006: this value of `err` is never used (staticcheck)
        v, err := strconv.ParseFloat(r, 32)
        ^
cloud/pkg/router/provider/servicebus/servicebus.go:125:2: SA4006: this value of `ok` is never used (staticcheck)
        messageID, ok := data["messageID"].(string)
        ^
cloud/pkg/router/provider/servicebus/servicebus.go:126:2: SA4006: this value of `ok` is never used (staticcheck)
        param, ok := data["param"].(string)
        ^
cloud/pkg/router/provider/servicebus/servicebus.go:127:2: SA4006: this value of `ok` is never used (staticcheck)
        nodeName, ok := data["nodeName"].(string)
        ^
cloud/pkg/router/provider/servicebus/servicebus.go:129:2: SA4006: this value of `ok` is never used (staticcheck)
        request.Method, ok = data["method"].(string)
        ^
cloud/pkg/router/provider/servicebus/servicebus.go:130:2: SA4006: this value of `ok` is never used (staticcheck)
        request.Header, ok = data["header"].(http.Header)
        ^
cloud/pkg/cloudstream/iptables/iptables.go:143:11: SA4021: x = append(y) is equivalent to x = y (staticcheck)
                args := append([]string{"-p", "tcp", "-j", "DNAT", "--dport", port, "--to", ip + ":" + strconv.Itoa(im.streamPort)})
                        ^
cloud/pkg/cloudstream/iptables/iptables.go:153:11: SA4021: x = append(y) is equivalent to x = y (staticcheck)
                args := append([]string{"-p", "tcp", "-j", "DNAT", "--dport", port, "--to", ip + ":" + strconv.Itoa(im.streamPort)})
                        ^
common/constants/default.go:161:2: SA9004: only the first constant in this group has an explicit type (staticcheck)
        MessageSuccessfulContent string = "OK"
        ^
edge/pkg/metamanager/process_test.go:500:2: SA4006: this value of `fakeDao` is never used (staticcheck)
        fakeDao := new([]dao.Meta)
        ^
edge/pkg/metamanager/process_test.go:521:2: SA4006: this value of `msg` is never used (staticcheck)
        msg = model.NewMessage("").BuildRouter(ModuleNameEdgeHub, GroupResource, model.ResourceTypePodStatus, OperationNodeConnection).FillBody(connect.CloudDisconnected)
        ^
edge/pkg/metamanager/metaserver/kubernetes/storage/sqlite/imitator/imitator.go:77:2: SA4006: this value of `err` is never used (staticcheck)
        objRv, err := s.versioner.ObjectResourceVersion(obj)
        ^
edge/test/integration/appdeployment/application_test.go:225:4: SA4006: this value of `err` is never used (staticcheck)
                        cpuReq, err := resource.ParseQuantity("0.50")
                        ^
edge/test/integration/appdeployment/application_test.go:226:4: SA4006: this value of `err` is never used (staticcheck)
                        memoReq, err := resource.ParseQuantity("512Mi")
                        ^
edge/test/integration/appdeployment/application_test.go:251:4: SA4006: this value of `err` is never used (staticcheck)
                        cpuReq, err := resource.ParseQuantity("0.25")
                        ^
edge/test/integration/appdeployment/application_test.go:252:4: SA4006: this value of `err` is never used (staticcheck)
                        memoReq, err := resource.ParseQuantity("512Mi")
                        ^
tests/integration/metaserver/main_test.go:11:1: SA3000: TestMain should call os.Exit to set exit code (staticcheck)
func TestMain(m *testing.M) {
^
keadm/cmd/keadm/app/cmd/edge/upgrade.go:336:2: SA4006: this value of `err` is never used (staticcheck)
        cliCrt, err := tls.LoadX509KeyPair(certFile, keyFile)
        ^
edge/pkg/metamanager/metaserver/server.go:220:70: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
                request = request.WithContext(context.WithValue(request.Context(), commontypes.AuthorizationKey, token))
                                                                                   ^
edge/pkg/devicetwin/process_test.go:43:2: SA4006: this value of `fakeDevice` is never used (staticcheck)
        fakeDevice := new([]dtclient.Device)
        ^
edge/pkg/devicetwin/process_test.go:52:2: SA4006: this value of `fakeDeviceAttr` is never used (staticcheck)
        fakeDeviceAttr := new([]dtclient.DeviceAttr)
        ^
edge/pkg/devicetwin/process_test.go:61:2: SA4006: this value of `fakeDeviceTwin` is never used (staticcheck)
        fakeDeviceTwin := new([]dtclient.DeviceTwin)
        ^
edge/pkg/metamanager/metaserver/agent/agent_test.go:54:33: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
                        ctx = context.WithValue(ctx, commontypes.AuthorizationKey, "Bearer xxxx")
                                                     ^
edge/pkg/edged/edged.go:36:2: SA1019: package github.com/golang/protobuf/jsonpb is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead. (staticcheck)
        "github.com/golang/protobuf/jsonpb"
        ^
edge/pkg/edged/edged.go:329:12: SA4010: this result of append is never used, except maybe in other appends (staticcheck)
                                pods = append(pods, &pod)
                                       ^
edgesite/cmd/edgesite-server/app/server.go:361:3: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
                fmt.Fprintf(w, msg)
                ^
keadm/cmd/keadm/app/cmd/version.go:55:3: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
                fmt.Printf(string(y))
                ^
keadm/cmd/keadm/app/cmd/version.go:61:3: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
                fmt.Printf(string(y))
                ^
➜  kubeedge git:(master) ✗ 
```

**Comment by gy95** [comment]
that's ok @Fish-pro

**Pull request closed without merging**
