### PR TITLE
update go 1.21 for kubeedge build image

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

update go 1.21 for kubeedge build tool image, keep consistent with Kubernetes

### CODE REVIEW

**Comment by WillardHu** [comment]
Does the version of golang also need to be upgraded in the go.mod?

**Comment by Shelley-BaoYue** [comment]
> Does the version of golang also need to be upgraded in the go.mod?

Yes, it will be put at a seperate PR. We need to upgrate the go version in KubeEdge basic image, and then upgrate it in other parts.  Ref to: https://github.com/kubeedge/kubeedge/pull/5123 and https://github.com/kubeedge/kubeedge/pull/5146

**Comment by Shelley-BaoYue** [comment]
PTAL @fisherxu @wbc6080

**Review by wbc6080 — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
