### PR TITLE
fix message handleserver close channel panic

### PR DESCRIPTION
**Pull request by drcwr**
**What type of PR is this?**
>  /kind bug
>

**What this PR does / why we need it**:
IMG_0962-2

In cloudhub, when HandleServer handle the ack message from edge, we will close the ackChan and delete ParentID.

```
func (mh *MessageHandle) HandleServer()
...
	// handle the ack message from edge
	if container.Message.Router.Operation == beehiveModel.ResponseOperation {
		if ackChan, ok := mh.MessageAcks.Load(container.Message.Header.ParentID); ok {
			close(ackChan.(chan struct{}))
			mh.MessageAcks.Delete(container.Message.Header.ParentID)
		}
		return
	}

func (mh *MessageHandle) sendMsg()
...
LOOP:
	for {
		select {
		case <-ackChan:
                        // mh.MessageAcks.Delete(msg.GetID())
			mh.saveSuccessPoint(copyMsg, info, nodeStore)
			break LOOP

```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
@drcwr Thanks for your fix! Looks good to me. Could you explain the details of the bug which fixed in the PR? if the ack received  after timeout occured, we can still delete it from ackChan, right?

**Comment by drcwr** [comment]
> @drcwr Thanks for your fix! Looks good to me. Could you explain the details of the bug which fixed in the PR? if the ack received after timeout occured, we can still delete it from ackChan, right?

panic:close of closed channel
close of ack1 and close of ack2 all done, when ackChan Map load1 and ackChan Map load2 done befor delete.

use MyClose() replace close(),print error.

> messagehandler.go:141] MyClose close(ch) panic occur.Failed to serve handle with error: close of closed channel

```
func MyClose(ch chan struct{}) {
	defer func() {
		if err := recover(); err != nil {
			klog.Errorln("MyClose close(ch) panic occur.Failed to serve handle with error:", err)
		}
	}()

	close(ch) // panic if ch is closed
}
```

**Comment by fisherxu** [comment]
Sounds good.
/lgtm
cc @kadisi

**Comment by fisherxu** [comment]
@drcwr Could you rebase the master branch? Let's fix the CI issue and get it merged. :)

**Pull request merged**
