### PR TITLE
Nominate new maintainer GsssC

### PR DESCRIPTION
**Pull request by fisherxu**
**What this PR does / why we need it**:
Nominate new maintainer @GsssC from HarmonyCloud, @GsssC has been active in the kubeegde community for more than a year, participated in the development of major features in recent releases, eg edgeside list-watch interface, also helped review lots of codes, have shown good technical judgement in feature design/development.

Looking forward to more contributions and help to community members.

**Special notes for your reviewer**:

/cc @kubeedge/maintainers 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by chendave — COMMENTED** [review]
/lgtm

**Comment by kevin-wangzefeng** [comment]
+1, Thanks @fisherxu for initiating this.

Nominee has been sponsored by two current maintainers, and no objections from other maintainers.
Let's welcome @GsssC as a new maintainer 👏 👏 

/lgtm
/approve

**Pull request merged**
