### PR TITLE
Removing code to update device state from edge to cloud in bluetooth mapper

### LINKED ISSUE #909: Remove code in bluetooth mapper to update device state
**What would you like to be added**:
Remove code in bluetooth mapper to update device state (Online/Offline)

**Why is this needed**:
Our device controller implementation does not update the state of the device (online/offline). Hence this should  be removed from bluetooth mapper

### PR DESCRIPTION
**Pull request by sujithsimon22**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
This PR cleans up unused code from bluetooth mapper 

**Which issue(s) this PR fixes**:

Fixes #909

### CODE REVIEW

**Comment by sujithsimon22** [comment]
cc @rohitsardesai83 @sids-b

**Comment by rohitsardesai83** [comment]
@sujithsimon22 , please check the CI test failure.

**Comment by sujithsimon22** [comment]
> @sujithsimon22 , please check the CI test failure.

@rohitsardesai83 Done

**Comment by sujithsimon22** [comment]
> > @sujithsimon22 , please check the CI test failure.
> 
> @rohitsardesai83 Done

looks to be a flaky integraton test, we can take a look at it, if we observe this problem repeating

**Pull request merged**
