### PR TITLE
EdgeMesh: refactor dns

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

Use `miekg/dns` as dns server, it is also used by CoreDns.

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
Please split vendor updates into separate commit

**Comment by daixiang0** [comment]
@kevin-wangzefeng done.

**Comment by daixiang0** [comment]
depend on #2212

**Comment by daixiang0** [comment]
@kevin-wangzefeng @fisherxu does it have chance to be merged?

**Comment by fisherxu** [comment]
> @kevin-wangzefeng @fisherxu does it have chance to be merged? If not, I would close this.

It's need more discussion, and edgemesh will have some refactor work, thanks.

**Comment by daixiang0** [comment]
Just hold.

/hold

/lifecycle frozen

**Comment by daixiang0** [comment]
ping @fisherxu @kevin-wangzefeng

**Comment by fisherxu** [comment]
Edgemesh will be decoupled lately, can reopen the pr in the new repo.
/close

**Comment by Poorunga** [comment]
@daixiang0  This is a great PR, would you like to move this design to the edgemesh new repo: https://github.com/kubeedge/edgemesh

**Comment by daixiang0** [comment]
let's do it.

**Comment by Poorunga** [comment]
> let's do it.

@daixiang0 Nice~

**Pull request closed without merging**
