### PR TITLE
fix daemonset pods not synced to edge

### PR DESCRIPTION
**Pull request by chenchunxiu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
After the edge-node broken and the db file is lost, if edge-node reconnect to the cloudcore again, the daemonset pod will not be synced to the edge-node, but the pod status is still running

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
this is not correct, upstream controller is for syncing edge messages from edge to cloud.

**Comment by chenchunxiu** [comment]
> this is not correct, upstream controller is for syncing edge messages from edge to cloud.

yes，upstream controller is uaually for syncing edge messages from edge to cloud.
but，downstream controller cannot watch the event of daemonset pods，so here i sync the ds pods to edge only when edge-node register agagin

**Comment by gy95** [comment]
If the database file is lost, edge node does not work well, what else do we need to consider? :)

**Comment by chenchunxiu** [comment]
> If the database file is lost, edge node does not work well, what else do we need to consider? :)
I may not get what you mean.
The scenario I am considering here is:  After the node broken and the db file lost, the daemonset pod can be restored after the edge-node is reconnected to cloudcore.

**Comment by chenchunxiu** [comment]
> If the database file is lost, edge node does not work well, what else do we need to consider? :)

When db file lost, we usually cannot restore it, but some users will access cloudcore with the same nodeName after restoring the node. 
After reconnect to cloudcore, the pod of the existing daemonset will not be synched to the edge-node, here is mainly to solve this problem.

**Pull request closed without merging**
