### PR TITLE
add env status.hostIP for pods

### PR DESCRIPTION
**Pull request by qingchen1203**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:
add env status.hostIP for pods
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fisherxu** [comment]
I'd suggest remove the commit `fix bug for close nil channel issue #1559` in this PR, which is another thing. And the `hostIP` looks good.  @qingchen1203

**Comment by kevin-wangzefeng** [comment]
hit shift when entering ctrl+enter

**Pull request merged**
