### PR TITLE
Delete redundant status field in CRD

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**
Delete the status in CRD, which will be populated by k8s.

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rohitsardesai83** [comment]
I tested with the crds in my system and the status fields of the crds are updated by the k8s api server : 

```yaml
  status:
    acceptedNames:
      kind: Device
      listKind: DeviceList
      plural: devices
      singular: device
    conditions:
    - lastTransitionTime: 2019-06-11T09:16:04Z
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: null
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
    storedVersions:
    - v1alpha1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```

**Comment by sids-b** [comment]
I don't know why cross build edge is failing here

**Comment by fisherxu** [comment]
I just rebased the master branch and force updated, the CI seems all failed... The other is when I force updated, the `lgtm` label should be removed.

**Comment by sids-b** [comment]
@fisherxu , can you please rebase your fork ? We have put the temporary workaround for CI problem.

**Comment by fisherxu** [comment]
@sids-b have done :) ptal

**Pull request merged**
