### PR TITLE
fix bug: cloud send twin_update confirm message to edge

### PR DESCRIPTION
**Pull request by jidalong**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
After deviceTwin send twin_update message to cloud,  communication module start to wait an confirm message from cloud and then remove related parentID message in confirmmap, but now cloud doesn't send any confirm message to edge, so deviceTwin module will send repeated message. This commit fix the problem above, cloud sends  confirm message to edge after successfully updated the device status.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by GsssC** [comment]
would better use 
`git pull --rebase upstream master` 
to fetch the lastest master commits and "rebase merge" to your pr branch

**Comment by jidalong** [comment]
> would better use
> `git pull --rebase upstream master`
> to fetch the lastest master commits and "rebase merge" to your pr branch



> would better use
> `git pull --rebase upstream master`
> to fetch the lastest master commits and "rebase merge" to your pr branch

Thank you, I have compressed my commits just in one commit.

**Comment by GsssC** [comment]
commit `Merge pull request #1 from kubeedge/master`is a dirty commit

u'd better drop it by 'git rebase'.
: )

**Comment by jidalong** [comment]
> commit `Merge pull request #1 from kubeedge/master`is a dirty commit
> 
> u'd better drop it by 'git rebase'.
> : )

Sorry, some problem was occured while merging this commit, I open a new pull request and close this request, please click the following link to review, thanks. 
[https://github.com/kubeedge/kubeedge/pull/2182](url)

**Pull request closed without merging**
