### PR TITLE
Test coverage for `edge/pkg/metamanager/client` module - `CSR` and `CM` files

### PR DESCRIPTION
**Pull request by 1Shubham7**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

I have added tests for two files in `edge/pkg/metamanager/client` module. more coming in next PRs.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by 1Shubham7** [comment]
Hey @Shelley-BaoYue, @WillardHu .

thank you for being supportive @Shelley-BaoYue, please review this PR so that I can accordingly write tests for other files in the package.

**Comment by 1Shubham7** [comment]
PTAL @Shelley-BaoYue @WillardHu @fisherxu : )

**Review by fisherxu — COMMENTED** [review]
/lgtm
/assign @WillardHu @Shelley-BaoYue

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by Shelley-BaoYue — COMMENTED** [review]
/approve

**Pull request merged**
