### PR TITLE
Add e2e test for arm64

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
Add e2e test for arm64 in travis.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by chendave** [comment]
"make e2e" failed with below errors, 
```
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged test-control-plane cat /kind/version" failed with error: exit status 1
```

is that expected?

**Comment by gy95** [comment]
now GO111MODULE="auto", need to set GO111Module to on?

**Comment by fisherxu** [comment]
> "make e2e" failed with below errors,
> 
> ```
> ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged test-control-plane cat /kind/version" failed with error: exit status 1
> ```
> 
> is that expected?

Not sure why the kind container will exit everytime.. @chendave

**Comment by fisherxu** [comment]
```
    - name: "e2e test"
      arch: arm64-graviton2
      virt: vm
      group: edge
```

After debuging and reading the docs, I found if set to `arch: arm64`, travis will run the lxd container, it's not a full vm,  so kind can't create container successfully.

Travis supports another arm64 arch, `arm64-graviton2` on AWS, we can set to full vm mode as above, so the kind can work as excepted. 

Has any ideas that whether we can simulate the arm64/arm32 tests on x86 server? @chendave @gy95

**Comment by chendave** [comment]
> After debuging and reading the docs, I found if set to arch: arm64, travis will run the lxd container, it's not a full vm, so kind can't create container successfully.

I believe this has been addressed, there is an option to opt in a full vm instead of lxd container.

**Comment by chendave** [comment]
something like this, 
```
      arch: arm64-graviton2
      virt: vm
```

**Comment by chendave** [comment]
pls ignore my comments above :)

> Has any ideas that whether we can simulate the arm64/arm32 tests on x86 server?

what's the purpose of this simulation?

**Comment by fisherxu** [comment]
> what's the purpose of this simulation?

Can run arm64 and arm32 e2e test in x86 vm, like in github action :) I noticed @gy95 has do some research about it? 

ref: https://github.com/kubeedge/kubeedge/pull/3751

**Review by chendave — APPROVED** [review]

**Pull request merged**
