### PR TITLE
trans troubleshooting.md

### PR DESCRIPTION
**Pull request by chuanhaojin**
Signed-off-by: chuanhaojin <chuanhao.jin@daocloud.io>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

trans troubleshooting.md

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
You can updated in one PR, no need to recreate PRs...

**Comment by chuanhaojin** [comment]
My fork Registry has done so much Useless merge， it cause that master branch is full with merge&commit log......but now it has been solved...Thanks for attention . It will not happen again.

**Comment by fisherxu** [comment]
> My fork Registry has done so much Useless merge， it causes that master branch is full with merge&commit log......but now it has been solved...Thanks for attention . It will not happen again.

You can force update the branch instead of always create new branch.

**Comment by chuanhaojin** [comment]
> > My fork Registry has done so much Useless merge， it causes that master branch is full with merge&commit log......but now it has been solved...Thanks for attention . It will not happen again.
> 
> You can force update the branch instead of always create new branch.
 
You are right . Get it

**Pull request merged**
