### PR TITLE
chore: remove duplicate error check code

### PR DESCRIPTION
**Pull request by XmchxUp**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
@XmchxUp Plz fix the failed DCO test as the instruction below, thanks
https://github.com/kubeedge/kubeedge/pull/5873/checks?check_run_id=30509143502

**Comment by XmchxUp** [comment]
ok, thanks for the reminder. @fisherxu

**Review by fisherxu — COMMENTED** [review]
/lgtm
Thanks for the fixing! @XmchxUp

**Pull request merged**
