### PR TITLE
Update device_controller.md

### PR DESCRIPTION
**Pull request by didier-durand**
Hi there, 
Fixing a couple of typos and harmonizing the spelling of web-socket / websocket
Best
Didier

### CODE REVIEW

**Comment by daixiang0** [comment]
Better title: "docs/device_controlller.md: fix a typo"

Also, please help check typos and put them in one pr :)

**Comment by didier-durand** [comment]
@daixiang0 : Ok, next time, I'll group all typos that I spot in a single PR. I did separate them because some other projects in which I reviewed docs prefer to have fixes regarding different pages in separate PRs. You prefer them to be grouped it seems. Correct? 
Best,
Didier

**Comment by daixiang0** [comment]
Yep, group them is fine here.

**Comment by didier-durand** [comment]
Ok, I'll do so next time. Didier

**Pull request merged**
