### PR TITLE
Automated cherry pick of #5392: fixed an issue where env support for edgeapplication was not

### PR DESCRIPTION
**Pull request by WillardHu**
Cherry pick of #5392 on release-1.16.

#5392: fixed an issue where env support for edgeapplication was not

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by WillardHu** [comment]
PTAL  /assign @Shelley-BaoYue

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by Shelley-BaoYue — COMMENTED** [review]
/approve

**Pull request merged**
