### PR TITLE
Automated cherry pick of #3114 origin release 1.8

### PR DESCRIPTION
**Pull request by siredmar**
What type of PR is this?
/kind feature

What this PR does / why we need it:
This PR is a spinoff of #3098 with only the needed changes

This PR uses official pause container image which are already multiarch images. Therefore the need to explicitly define the arch for the pause image wonn't be needed anymore. Examples kubeedge/pause, kubeedge/pause-arm64 and kubeedge/pause-arm.

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Could you also fix the UT in `pkg/util/util_test.go`? I'm not sure why the ci haven't reported in this pr.. @siredmar

**Comment by gy95** [comment]
branch release-1.8 don't have `GetPodSandboxImage` related test. only in master branch, we add more unit test for `util.go`
So this cherry-pick will pass all ci checks.

**Comment by siredmar** [comment]
@fisherxu @gy95 sound good too me. Then let's merge this. Thanks for the info.

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
