### PR TITLE
Lint: add link check

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:

Add link check.

### CODE REVIEW

**Comment by daixiang0** [comment]
depend on #1848

**Comment by daixiang0** [comment]
ping @fisherxu

**Review by fisherxu — COMMENTED** [review]
Small question, does the github action check can block the PR? Or could we add it in travis ci?

**Comment by daixiang0** [comment]
Github action would block merge if failed. Travis-ci is slow to test outside url and make it flaky.

@fisherxu seems this repo does not enable github action.

**Comment by fisherxu** [comment]
> Github action would block merge if failed. Travis-ci is slow to test outside url and make it flaky.
> 
> @fisherxu seems this repo does not enable github action, see this [doc](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository).

We'd better add the check to ci.

**Comment by daixiang0** [comment]
@fisherxu done.

**Comment by fisherxu** [comment]
Need to fix other broken link.

**Comment by daixiang0** [comment]
`liche` now works very falsky, switch to another one.

**Pull request closed without merging**
