### PR TITLE
Fixes #532

### LINKED ISSUE #532: handlePodListFromEdgeController don't work
**What happened**:
```
func (e *edged) handlePodListFromEdgeController(content []byte) (err error) {
	var lists []v1.Pod
// lists is empty, why for...
	for _, list := range lists {
		err = json.Unmarshal(content, &list)
		if err != nil {
			return err
		}
		e.addPod(&list)
	}

	return nil
}
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by lzx258**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixed handlePodListFromEdgeController don't work in edged/edged.go

**Which issue(s) this PR fixes**:

Fixes #532

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by lzx258** [comment]
@sids-b @m1093782566 pls review

**Comment by m1093782566** [comment]
/lgtm

leave approve to @sids-b

**Comment by lzx258** [comment]
> @lzx258 , I don't think it will work this way. The content that comes from metaManager can be unmarshalled into []string but the content from edgeController is in form of []v1.Pod. Can you share some log screenshots where it is working please ?

Oh,yes  this is problem!  let us update it

**Comment by sids-b** [comment]
The reason I feel there will be a problem is that, when metaManager receives the pod addition message, it marshal's the content and saves it in string([]byte) form in db. So the podList from metamanager can be unmarshaled successfully into []string. Please refer to line https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/metamanager/msg_processor.go#L150

**Comment by lzx258** [comment]
@sids-b  done

**Comment by sids-b** [comment]
Lets merge this once CI passes :)

**Comment by m1093782566** [comment]
@pavan187 When people update the commits, ci bot should remove the attached `lgtm` label.

**Comment by pavan187** [comment]
> eople update the commits

Got it, will implement

**Comment by sids-b** [comment]
> @pavan187 When people update the commits, ci bot should remove the attached `lgtm` label.

+1 . CI-bot should have this same behavior of github. Github also dismisses approved reviews based on settings when commits in the pr are modified.

**Pull request merged**
