### PR TITLE
Issue #631: Add validation of required fields for device model and device instance

### PR DESCRIPTION
**Pull request by rohitsardesai83**
**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:
This PR introduces very basic validation of required fields while creating device models and device instances. It doesn't take care of the rest of the validations mentioned in #631.

**Which issue(s) this PR fixes**:
xref #631 : 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rohitsardesai83** [comment]
@chendave , added a few more validations with enums to validate valid values for certain fields like access modes , baud rate etc.

**Comment by rohitsardesai83** [comment]
@sids-b , @kevin-wangzefeng , please review.

**Comment by kevin-wangzefeng** [comment]
Can you add e2e tests as well?

**Comment by chendave** [comment]
Looks like there is no good way to reject an unknown property which is a kind of object, I saw "additionalProperties" is banned.

**Comment by rohitsardesai83** [comment]
> Looks like there is no good way to reject an unknown property which is a kind of object, I saw "additionalProperties" is banned.

We can reject unknown properties in the custom validation hooks , if usage of `additionalProperties:false` is not recommended.

**Comment by rohitsardesai83** [comment]
> Can you add e2e tests as well?

@kevin-wangzefeng , yes we can add , but there is another PR dealing with e2e tests for device management already : https://github.com/kubeedge/kubeedge/pull/669.

Once this PR gets merged , I can add some tests for validation.

**Pull request merged**
