### PR TITLE
Echo the build error message to stderr instead of stdout

### PR DESCRIPTION
**Pull request by llhuii**
**What type of PR is this?**

**What this PR does / why we need it**:
For example, **SHOW** the error message `can not find binary: abc` in the terminal when `make all WHAT=abc` (just to **trigger the build script error**):
```
bash hack/verify-golang.sh
go detail version: go version go1.14.7 linux/amd64
go version: 1.14.7
hack/make-rules/build.sh abc 
can not find binary: abc
Makefile:41: recipe for target 'all' failed
make: *** [all] Error 1
```
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
`make HELP=y` is enough.

**Comment by llhuii** [comment]
> `make HELP=y` is enough.

It's another command.

I want to say that the build scripts should echo the error message in the terminal when it wants to.

But now the message would be discard by the shell assignment command like `read -r ldflags <<< "$(kubeedge::version::ldflags)"` even when `kubeedge::version::ldflags` errors.

**Comment by daixiang0** [comment]
So the desribtion of pr is wrong since your point was incorrect **WHAT**.

**Comment by llhuii** [comment]
> So the desribtion of pr is wrong since your point was incorrect **WHAT** while HELP would explain it.
Ok, it is misleading, just to an example to trigger the build error.

**Comment by fisherxu** [comment]
Just small question, is any issue without this patch? :)

**Comment by llhuii** [comment]
> Just small question, is any issue without this patch? :)

Can't find one. I guess no one notice this.

**Comment by fisherxu** [comment]
> > Just small question, is any issue without this patch? :)
> 
> Can't find one. I guess no one notice this.

So let's keep as it is now :)

**Comment by llhuii** [comment]
> > > Just small question, is any issue without this patch? :)
> > 
> > 
> > Can't find one. I guess no one notice this.
> 
> So let's keep as it is now :)

I thought you wanted me to check any open github issues related to this one.

Yes, it has something wrong with me:
- These `echo` commands would be useless without the patch since it would be discard. I think the authors of this code doesn't means that.
- For the view of Error message, I think it should be echoed to stderr either.

**Comment by llhuii** [comment]
PS: These `echo`s can be wrapped into bash functions, like [k8s do this](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/logging.sh).

**Comment by llhuii** [comment]
From this shell guide https://google.github.io/styleguide/shellguide.html#stdout-vs-stderr:

image

**Comment by llhuii** [comment]
FYI, I submited this to k8s project and it merged. https://github.com/kubernetes/kubernetes/pull/97999.

**Comment by llhuii** [comment]
sorry some wrong: my origin commit was overwritten by mistake.

**Comment by fisherxu** [comment]
> sorry something wrong: my origin commit was overwritten by mistake.

Not good choice to use master branch :)

**Comment by llhuii** [comment]
> > sorry something wrong: my origin commit was overwritten by mistake.
> 
> Not good choice to use master branch :)

Learned😄

**Pull request closed without merging**
