### PR TITLE
Keadm: add LinuxMint OS support

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**

 /kind feature

**What this PR does / why we need it**:

Linux Mint is a popular Linux release based on debian and ubuntu, see [doc](https://linuxmint.com/about.php).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Keadm: support LinuxMint
```

### CODE REVIEW

**Comment by fisherxu** [comment]
Has any shell oupt about the OS info?

**Comment by daixiang0** [comment]
No recent docker image, so share community bug track [here](https://bugs.launchpad.net/linuxmint/+bug/1641491).

**Comment by fisherxu** [comment]
> No official docker image, so share community bug track [here](https://bugs.launchpad.net/linuxmint/+bug/1641491).

Need more tests in the real environment.

**Pull request closed without merging**
