### PR TITLE
mapper framework fix

### PR DESCRIPTION
**Pull request by cl2017**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
mapper framework fix
- We shloud move `pkg/util/grpcclient` to `pkg/grpcclient`.
- `RegisterMapper` function should use `pkg/grpcclient/config`  instead of function argument

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wbc6080** [comment]
This is a good modification. Indeed, we have stored config in a global variable when initializing grpcclient and do not need to write it in function argument. But I find that you didn't fix the import path in device/devicetwin.go. Please fix it, thank you

**Comment by cl2017** [comment]
> This is a good modification. Indeed, we have stored config in a global variable when initializing grpcclient and do not need to write it in function argument. But I find that you didn't fix the import path in device/devicetwin.go. Please fix it, thank you

Yes, I'll open another PR to rewrite `pkg/config`, in this PR, we fix `pkg/grpcclient` fisrt.
I have already fix `devicetwin.go`, thanks.

**Review by fisherxu — COMMENTED** [review]
/approve
/assign @WillardHu @wbc6080

**Pull request merged**
