### PR TITLE
fix import to upgrade mapper

### PR DESCRIPTION
**Pull request by wbc6080**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
fix import to upgrade mapper. If mapper needs to be upgraded, you can directly modify the version in go.mod
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wbc6080** [comment]
PTAL @cl2017 @WillardHu  This is the PR used to upgrade mapper

**Comment by wbc6080** [comment]
And @fisherxu please help to add the 1.16 tag

**Comment by wbc6080** [comment]
Could you help to add the 1.16 tag? thank you @Shelley-BaoYue

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
