### PR TITLE
Edged: fix containers residual problem

### LINKED ISSUE #2034: Containers does not clean up after deleted
**What happened**:

After delete deployment, some related containers still exist while `kubectl get pod` can not see it.
```
$ kubectl get pod
$ docker ps
727506f4daf5        8cf1bfb43ff5           "/docker-entrypoint.…"   6 minutes ago        Up 6 minutes                                    k8s_nginx_nginx-6fcf476c4-p2p6p_default_39996f8e-b354-4879-8891-85415b045361_0
3be0b395df6a        kubeedge/pause:3.1     "/pause"                 6 minutes ago        Up 6 minutes                                    k8s_POD_nginx-6fcf476c4-p2p6p_default_39996f8e-b354-4879-8891-85415b045361_0
3d52c7ec6ef2        kubeedge/pause:3.1     "/pause"                 7 minutes ago        Up 7 minutes                                    k8s_POD_nginx-6fcf476c4-56rvw_default_1016b445-9922-4c69-b7ad-cee9c8903b61_0
c8f265549636        kubeedge/pause:3.1     "/pause"                 7 minutes ago        Up 7 minutes                                    k8s_POD_nginx-6fcf476c4-j6vh8_default_3e2b12a7-5968-4ca8-8c3c-ec325f294e28_0
1fddd9532f83        kindest/node:v1.17.0   "/usr/local/bin/entr…"   9 minutes ago        Up 9 minutes        127.0.0.1:32809->6443/tcp   test-control-plane
```

**What you expected to happen**:

No related contains exist.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ cat test.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1000
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
$ kubectl apply -f test.yaml
$ sleep 10
$ kubectl delete -f test.yaml
```

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Optimize cleanup function to ensure only desired containers run.

**Which issue(s) this PR fixes**:

Fixes #2034

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix containers containers residual problem
```

### CODE REVIEW

**Comment by daixiang0** [comment]
update

**Comment by daixiang0** [comment]
update

**Comment by daixiang0** [comment]
Fix #1955 too

**Comment by kevin-wangzefeng** [comment]
Could you add test for this fix?

**Comment by daixiang0** [comment]
ping @fisherxu @kevin-wangzefeng

**Pull request closed without merging**
