### PR TITLE
Fixed the cloudcore panic caused by the ClusterObjectSyncList item error

### LINKED ISSUE #4912: Failed to restart cloudcore
**What happened**:
After restarting cloudcore, it throws an error.
```
panic: interface conversion: interface {} is *v1alpha1.ObjectSync, not *v1alpha1.ClusterObjectSync

goroutine 582 [running]:
github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1.(*clusterObjectSyncLister).List.func1({0x189d4c0, 0x40036b0810})
	/go/src/github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go:53 +0xf8
github.com/kubeedge/kubeedge/vendor/k8s.io/client-go/tools/cache.ListAll({0x1bcd028, 0x40005ac9d8}, {0x1bc96e0, 0x400159ae10}, 0x4000812d38)
	/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/client-go/tools/cache/listers.go:40 +0xb8
github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1.(*clusterObjectSyncLister).List(0x40009c1140, {0x1bc96e0, 0x400159ae10})
	/go/src/github.com/kubeedge/kubeedge/pkg/client/listers/reliablesyncs/v1alpha1/clusterobjectsync.go:52 +0x8c
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).deleteClusterObjectSyncs(0x4000805a00)
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:167 +0x64
github.com/kubeedge/kubeedge/cloud/pkg/synccontroller.(*SyncController).Start(0x4000805a00)
	/go/src/github.com/kubeedge/kubeedge/cloud/pkg/synccontroller/synccontroller.go:109 +0x84
github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.moduleKeeper({0x18e5c3e, 0xe}, 0x4000990990, {{0x18e5c3e, 0xe}, {0x18ddcda, 0x7}, {0x0, {0x0, 0x0}}})
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:77 +0xf0
created by github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core.StartModules
	/go/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:45 +0x428
```

**What you expected to happen**:
After restarting cloudcore, it can run correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Restarting cloudcore with clusterobjectsyncs resource present.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.24.13
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.14.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by ZhengXinwei-F**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

The items in the ClusterObjectSyncList are ObjectSync lists, causing panic to occur when cloudcore format assertions

**Which issue(s) this PR fixes**:

Fixes #4912

**Special notes for your reviewer**:

/cc @fisherxu @AXHMFHNP

**Does this PR introduce a user-facing change?**: no

```
[root@master1 ~]# kubectl apply -f objectsyncs.yaml
objectsync.reliablesyncs.kubeedge.io/cloudcore-objectsync unchanged
clusterobjectsync.reliablesyncs.kubeedge.io/cloudcore-clusterobjectsync created
[root@master1 ~]# kubectl get pods -nkubeedge
NAME                        READY   STATUS    RESTARTS   AGE
cloudcore-cd58b85fb-kzdgm   1/1     Running   0          21m
[root@master1 ~]# kubectl scale deploy/cloudcore -nkubeedge --replicas=0
deployment.apps/cloudcore scaled
[root@master1 ~]# kubectl scale deploy/cloudcore -nkubeedge --replicas=1
deployment.apps/cloudcore scaled
[root@master1 ~]# kubectl get pods -nkubeedge
NAME                        READY   STATUS    RESTARTS   AGE
cloudcore-cd58b85fb-sfm7v   1/1     Running   0          2s
```

### CODE REVIEW

**Comment by AXHMFHNP** [comment]
LGTM

**Comment by fisherxu** [comment]
@ZhengXinwei-F Please signoff the commit to fix the failed DCO test.

**Comment by ZhengXinwei-F** [comment]
> @ZhengXinwei-F Please signoff the commit to fix the failed DCO test.

done

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Comment by fisherxu** [comment]
Please cherry-pick to release-1.14 branch using `hack/cherry_pick_pull.sh`

**Pull request merged**
