### PR TITLE
Keadm: update OWNERS

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**

**What this PR does / why we need it**:

Add @daixiang0.

Contributions about keadm see this [link](https://github.com/kubeedge/kubeedge/pulls?q=is%3Apr+author%3Adaixiang0+keadm+).

### CODE REVIEW

**Comment by daixiang0** [comment]
update

**Comment by daixiang0** [comment]
ping @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
/approve
Thanks, deferring to other maintainers for final check.

**Pull request merged**
