### PR TITLE
Complete tests for `edge/pkg/metamanager/client`

### PR DESCRIPTION
**Pull request by 1Shubham7**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

I have added rest of the tests for `edge/pkg/metamanager/client` module

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Shelley-BaoYue — COMMENTED** [review]
Hi, @1Shubham7    the unit test occasionally appears the error shown in the figure recently. Would you please help find the reason?

image

**Comment by 1Shubham7** [comment]
> Hi, @1Shubham7 the unit test occasionally appears the error shown in the figure recently. Would you please help find the reason?
> 
> image

Hey @Shelley-BaoYue, I think this is happening because the `options.go` was defining its own version flag, while we also have a version flag implementation in `verflag` package. I guess that's why due to the flag initialization order, the CI unit tests were failing sometimes and sometimes not : ) I fixed this in [this PR](https://github.com/kubeedge/kubeedge/pull/5928)

**Comment by 1Shubham7** [comment]
@Shelley-BaoYue @WillardHu PTAL : )

**Comment by 1Shubham7** [comment]
@WillardHu @fisherxu PTAL : )

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
