### PR TITLE
Update modbus_mapper.md

### PR DESCRIPTION
**Pull request by soyoo**
documentation: typo issue.

### CODE REVIEW

**Comment by daixiang0** [comment]
Please config your name and email and then run `git commit -s --amend` to generate signoff, and update pr decription since i we usually say "typo issue" not "type error".

**Comment by soyoo** [comment]
> Please config your name and email and then run `git commit -s --amend` to generate signoff, and update pr decription since i we usually say "typo issue" not "type error".

**Comment by soyoo** [comment]
> Please config your name and email and then run `git commit -s --amend` to generate signoff, and update pr decription since i we usually say "typo issue" not "type error".

sorry, I do not how to do it. The PR will delete.

**Comment by fisherxu** [comment]
@soyoo Thanks for your supporting and fixing! I think the PR title and commit message is not issue, can just reopen and got it merged.

**Comment by soyoo** [comment]
> @soyoo Thanks for your supporting and fixing! I think the PR title and commit message is not issue, we can just reopen and got it merged.

@fisherxu This PR had merged in another PR #2209

**Comment by fisherxu** [comment]
> > @soyoo Thanks for your supporting and fixing! I think the PR title and commit message is not issue, we can just reopen and got it merged.
> 
> @fisherxu This PR had merged in another PR #2209

Okey.

**Pull request closed without merging**
