### PR TITLE
Merge pull request #5352 from Windrow14/bugfix/metaserver_panic_when_…

### PR DESCRIPTION
**Pull request by Windrow14**
Cherry-pick https://github.com/kubeedge/kubeedge/pull/5352 for release-1.16.

### CODE REVIEW

**Review by wbc6080 — COMMENTED** [review]
DCO need to be fixed firstly :)

**Review by fujitatomoya — APPROVED** [review]
lgtm, @Windrow14 thanks!

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm 
The failure CI tests is not relevant to this PR. Using https://github.com/kubeedge/kubeedge/issues/5482 to track the failure and fix it later.

**Pull request merged**
