### PR TITLE
judge faild whether is nil for SetPods func

### PR DESCRIPTION
**Pull request by kadisi**
Signed-off-by: zhangjie <iamkadisi@163.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by m1093782566** [comment]
@kadisi A general comment, better to provide how to reproduce if you think it's a bug.

BTW, I feel `pm.podByUID` and `pm.podByFullName` should be ALWAYS nil in this case?

**Comment by kadisi** [comment]
@m1093782566 yes,  it should be always nil, but you can't guarantee that developers will use it incorrectly, i think SetPods functions is no usefull.   SetPods `s function can be directly integrated into NewPodManager function。 SetPods function only be called once in this project.

`
//NewPodManager creates new pod manager object
func NewPodManager() pod.Manager {
	pm := &podManager{
		MockManager: new(testing.MockManager),
	}
	pm.podByUID = make(map[types.UID]*v1.Pod)
	pm.podByFullName = make(map[string]*v1.Pod)
	return pm
}
`

**Comment by m1093782566** [comment]
@kadisi Thanks for your information.

>SetPods function only be called once in this project.

If so, I would like to move the logic of `SetPods()` into ` NewPodManager()`.

**Comment by sids-b** [comment]
@kadisi , thanks. SetPods() is only called once in edged. 
As @m1093782566 suggested. The logic of setPods can be moved inside NewPodManager().

**Comment by kadisi** [comment]
@sids-b @m1093782566 PTAL

**Comment by m1093782566** [comment]
LGTM, please squash the commits.

**Comment by kadisi** [comment]
@m1093782566  i have squashed the commits

**Pull request merged**
