### PR TITLE
Supports defining the message buffer length through configuration

### PR DESCRIPTION
**Pull request by zc2638**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
```
Supports defining the message buffer length through configuration.

In many cases, because the buffer size of the message channel at the edge is only 1024, the message processing stops, resulting in false death.

When the resources are controllable, the message channel length of each module can be customized.
```
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
@zc2638  Thanks for the fixing, and could you please rebase to the master branch to fix the failed ci tests?

**Review by fisherxu — COMMENTED** [review]
Looks like there's too many size configuration fields, maybe we can use one common config?

**Comment by zc2638** [comment]
No matter what the problem is, it should support custom message buffer length.

**Pull request closed without merging**
