### PR TITLE
Remove mappers from kubeedge/kubeedge repo

### PR DESCRIPTION
**Pull request by fisherxu**
Signed-off-by: fisherxu <xufei40@huawei.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Now all the mappers have been move to mapper-go repo, and delete them from kubeedge/kubeedge repo.

Will fix docs in website in follow-up prs.

**Which issue(s) this PR fixes**:

Fixes #
Ref: https://github.com/kubeedge/kubeedge/issues/2775

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
+1
And we will need to wait until we have a working version of bluetooth mapper available in https://github.com/kubeedge/mappers-go
/hold

**Comment by fisherxu** [comment]
> +1
> And we will need to wait until we have a working version of bluetooth mapper available in https://github.com/kubeedge/mappers-go
> /hold

New version of bluetooth mapper authored by @ttlv (👍 )has been merged in https://github.com/kubeedge/mappers-go/pull/13 :)

**Comment by kevin-wangzefeng** [comment]
Just found that the bluetooth mapper is already available in https://github.com/kubeedge/mappers-go.

/hold cancel

**Comment by fisherxu** [comment]
The CI all passed. 
/assign @kevin-wangzefeng @sailorvii

**Review by sailorvii — COMMENTED** [review]
Should the build/crd-samples/devices also be removed?

**Comment by ttlv** [comment]
> Should the build/crd-samples/devices also be removed?

agree

**Comment by fisherxu** [comment]
> > Should the build/crd-samples/devices also be removed?
> 
> agree

Done.

**Pull request merged**
