### PR TITLE
bugfix get bad anonName when send twin message to cloud

### PR DESCRIPTION
**Pull request by QianQianowo**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The `beehiveContext.Send` method is used in device twin module to send twin message to cloud before. But the response message is send by edgehub module using method `beehiveContext.SendResp`. It may cause an error and the response message will be lost.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RyanZhaoXB** [comment]
please fix UT

**Comment by TianTianBigWang** [comment]
why use `beehiveContext.SendSync` rather than `beehiveContext.SendResp`?

**Review by fisherxu — COMMENTED** [review]
/sig device-iot

**Comment by QianQianowo** [comment]
> 

`beehiveContext.SendSync` means send a synchronized beehive message and wait for the response. The reply message will be returned through `beehiveContext.SendResp`. `beehiveContext.SendResp` is always used to send a reply message to the synchronized messages.

**Comment by QianQianowo** [comment]
> why use `beehiveContext.SendSync` rather than `beehiveContext.SendResp`?

beehiveContext.SendSync means send a synchronized beehive message and wait for the response. The reply message will be returned through beehiveContext.SendResp. beehiveContext.SendResp is always used to send a reply message to the synchronized messages.

**Pull request closed without merging**
