### PR TITLE
 Refactor the code for skip environment check

### PR DESCRIPTION
**Pull request by ZhengXinwei-F**
**What type of PR is this?**

Refactor the code for skip environment check.

**What this PR does / why we need it**:

Current code that skips environment checks is not elegant. Because environment checking is enabled by default but the default value in golang is false. Changing this parameter to DISABLE_ENVIRONMENT_CHECK is the best answer. However, the change on the user-facing is too large. Only the code is optimized in this case.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Should we consider changing CHECK_EDGECORE_ENVIRONMENT to DISABLE_ENVIRONMENT_CHECK.

**Does this PR introduce a user-facing change?**:

```
none
```

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
fix the DCO

**Comment by ZhengXinwei-F** [comment]
> fix the DCO

done

**Review by fisherxu — COMMENTED** [review]
/approve

**Review by fisherxu — COMMENTED** [review]
/assign @WillardHu @Shelley-BaoYue

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Pull request merged**
