### PR TITLE
Add .gitignore, remove example

### PR DESCRIPTION
**Pull request by yongwww**
- Add .gitignore
- Remove example since there is nothing under it and examples is a separate repo, make no sense to have empty example here

### CODE REVIEW

**Comment by yongwww** [comment]
@sids-b @m1093782566 take a look pls

**Comment by yongwww** [comment]
Not sure why ci failed

**Comment by sids-b** [comment]
@yongwww , all the CI jobs were stuck due to unknown reason. I just restarted the build. No worries :)

**Comment by sids-b** [comment]
@srivatsav123 @pavan187 , Can you please have a look at the CI ??

**Pull request merged**
