### PR TITLE
Fixed bug in performance test update_configmap script

### LINKED ISSUE #973: Bug in update_configmap script of performance tests
**What happened**:
While running the existing update_configmap script of performance tests the field edged.interface-name is also overwritten with the name of the configmap instead of just updating metadata.name field

**What you expected to happen**:
Only metadata.name field should be updated with the name of the configmap

### PR DESCRIPTION
**Pull request by sujithsimon22**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
This PR fixes the bug #973

**Which issue(s) this PR fixes**:

Fixes #973

### CODE REVIEW

**Comment by sujithsimon22** [comment]
cc @edisonxiang @rohitsardesai83 @sids-b @subpathdev

**Comment by edisonxiang** [comment]
/lgtm
Thanks @sujithsimon22

**Comment by sids-b** [comment]
thanks @sujithsimon22 

/approve

**Pull request merged**
