### PR TITLE
update docs/roadmap_zh.md

### PR DESCRIPTION
**Pull request by chuanhaojin**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by chuanhaojin** [comment]
Thanks for your attention.I will try my best to learn and do better.

**Comment by fisherxu** [comment]
> Thanks for your attention.I will try my best to learn and do better.

I just mean to copy the chinese roadmap from shimo docs to this PR :) @chuanhaojin 

/reopen

**Comment by fisherxu** [comment]
There are too many files in the PR...

**Comment by chuanhaojin** [comment]
> > Thanks for your attention.I will try my best to learn and do better.
> 
> I just mean to copy the chinese roadmap from shimo docs to this PR :) @chuanhaojin
> 
> /reopen

Note：

A line  is not in kubeedge project , but in the shimo docs：

“
#### DevicePlugin支持
- 支持DevicePlugin插件在边端运行
”

And  it`s not add to this PR .

Thanks

**Comment by fisherxu** [comment]
The pr now modified 37 files.

**Comment by fisherxu** [comment]
> > > Thanks for your attention.I will try my best to learn and do better.
> > 
> > 
> > I just mean to copy the chinese roadmap from shimo docs to this PR :) @chuanhaojin
> > /reopen
> 
> Note：
> 
> A line is not in kubeedge project , but in the shimo docs：
> 
> “
> 
> #### DevicePlugin支持
> * 支持DevicePlugin插件在边端运行
>   ”
> 
> And it`s not add to this PR .
> 
> Thanks

Sounds good.

**Comment by chuanhaojin** [comment]
This PR/branch has so many mistakes about merge & pull, I would create a new PR ....

**Comment by fisherxu** [comment]
/close
In favor of #2620

**Pull request closed without merging**
