### PR TITLE
Fix the hard coded links of docs

### PR DESCRIPTION
**Pull request by llhuii**
The links of docs linking for this repo should be relative, mainly:
For already released docs would be 404 in the future since the corresponding
doc of master branch would be moved, renamed or deleted etc.

Note, the docs in vendor dir keep unchanged.

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
@llhuii  Please don't write too many infos in the commit message, one sentence is enough :)

**Comment by llhuii** [comment]
> @llhuii Please don't write too many infos in the commit message later, one sentence is enough :)

OK.

**Pull request merged**
