### PR TITLE
Make the timestamps of kubeedge resources support international time

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Using "2006-01-02T15:04:05Z" layout to format the time zone is not utc, the time zone will be lost.
```golang
// The time with Asia/ShangHai time zone is 2024-08-26T17:24:00Z.
// We lost the time zone now.
pt, err := time.Parse("2006-01-02T15:04:05Z", "2024-08-26T17:24:00Z")
fmt.Println(pt) // 2024-08-26 17:24:00 +0000 UTC
```

At this point, we can no longer support international time. Therefore, we use a layout that contains the time zone.
```golang
time.Now().UTC().Format(time.RFC3339)  // 2024-08-26T17:24:00Z
time.Now().Format(time.RFC3339)  // 2024-08-26T17:24:00+08:00

pt, err := time.Parse(time.RFC3339, "2024-08-26T17:24:00+08:00")
fmt.Println(pt)  // 2024-08-26 17:24:00 +0800 CST
fmt.Println(pt.UTC())  // 2024-08-26 09:24:00 +0000 UTC
```

So, we need to format the time using `time.Now().UTC().Format(time.RFC3339)` to support international time.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by Shelley-BaoYue — COMMENTED** [review]
/approve

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Comment by fisherxu** [comment]
Plz cherry-pick to v1.15~1.18 release branch if needed :) @WillardHu

**Comment by WillardHu** [comment]
I have cherry-picked this PR to release-1.16, release-1.17 and release-1.18

**Pull request merged**
