### PR TITLE
fix wrong use of e.namespace when get imagePullSecret

### PR DESCRIPTION
**Pull request by GsssC**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
It is a cherry-pick, better to use `hack/cherry_pick_pull.sh`, then we can easily recognize it.

**Comment by GsssC** [comment]
@daixiang0 I am trying to use hack/cherry-pick to cherry-pick my pr to release-1.3, but there is a error, so I try to submit pr manully.
image

**Comment by daixiang0** [comment]
It needs `hub` cmd, refer to https://github.com/github/hub.

**Comment by GsssC** [comment]
@daixiang0 I have already downloaded hub and auto create brahch of `automated-cherry-pick-of-#1809-upstream-release-1.3` in my repo by `hack/cherry-pick.sh` but failed to auto submit pr.
image

**Comment by daixiang0** [comment]
Do you have set github account? It needs write permission.

**Comment by GsssC** [comment]
@daixiang0 it means it's the error of github but not me?

**Comment by daixiang0** [comment]
I guess so.

**Pull request merged**
