### PR TITLE
fix start local cluster cloudStream and edgeStream disabled

### LINKED ISSUE #2994: Configuration for CloudStream and EdgeStream module don't work
**What happened**:
When I run `hack\local-up-kubeedge.sh` to start a local cluster, the CloudStream and EdgeStream in config file have been enabled, but after cloudcore/edgecore started, the CloudStream and EdgeStream is disabled.

Looks like the config file does't work after v1.7. And it works in v1.6.

/assign @gy95 

**What you expected to happen**:

Make the configuration file work as expected.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by gy95**
Signed-off-by: gy95 <guoyao17@huawei.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2994

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Looks good, remove the empty commit.

**Comment by gy95** [comment]
> Looks good, remove the empty commit.

e2e failed, how to fix it?

**Comment by fisherxu** [comment]
> > Looks good, remove the empty commit.
> 
> e2e failed, how to fix it?

It's related to the OS env in github action.

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
