### PR TITLE
Kubeedge Installer to support Centos #454

### PR DESCRIPTION
**Pull request by congfairy**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #Kubeedge Installer to support Centos #454
/kind bug
**Special notes for your reviewer**:

### CODE REVIEW

**Comment by samy2019** [comment]
@congfairy , Please squash your changes. There are lot of commits. We can't see your changes.

**Comment by sids-b** [comment]
@congfairy , the PR is raised to v0.3.0-beta.0 .... Can you please raise the PR to the master branch ?

**Comment by congfairy** [comment]
> PR is raised to v0.3.0-beta.0 .... Can you please raise the PR to the master branc
@samy2019 ok ,I will fix that.

**Comment by congfairy** [comment]
@sids-b ok,I will close this one and raise a new pr.

**Pull request closed without merging**
