### PR TITLE
Delete the historical version of CRD in cloudcore/CRD.

### PR DESCRIPTION
**Pull request by luomengY**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In Kubeedge v1.15.0, when executing keadm init, it was found that the production device and devicemodel versions were still v1alpha2. Through debugging, it was found that there were both v1alpha1 and v1beta1 versions of device and devicemodel in the CRD of cloudcore/chart, because the generate-crds.sh script did not delete the old version when generating the new version of CRD.
keadm
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
@cl2017 
**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
/assign @cl2017 @wbc6080

**Comment by wbc6080** [comment]
We considered that version 1.15 was a transitional version for device modification, so v1alpha2 was retained. I think this part of the change can be merged when version 1.16 is launched. But still thanks for your contribution!

**Comment by luomengY** [comment]
> We considered that version 1.15 was a transitional version for device modification, so v1alpha2 was retained. I think this part of the change can be merged when version 1.16 is launched. But still thanks for your contribution!

However, currently both v1alpha2 and v1alpha1 versions of yaml exist in the v1.15.0 chart package. The final deployment of helm is random, depending on which device. yaml of v1alpha2 and v1alpha1 is first rendered. This means that users using keadm init may have either installed v1alpha2 or v1alpha1 versions, which I think is not very appropriate.

**Comment by luomengY** [comment]
> We considered that version 1.15 was a transitional version for device modification, so v1alpha2 was retained. I think this part of the change can be merged when version 1.16 is launched. But still thanks for your contribution!

The generate-crds.sh script does not delete historical versions of crds when the version changes and generates new crds into the chart package. This can result in multiple versions of crds being stored in the chart package. When executing help deployment with keadm init, it is uncertain which version of crd will be installed, which can lead to some issues.

**Comment by wbc6080** [comment]
OK, now we will delete the v1alpha2 device yaml in manifests, but the yaml in build will still exist. We will delete the v1alpha2 api  
definition in code in 1.16

**Comment by luomengY** [comment]
> OK, now we will delete the v1alpha2 device yaml in manifests, but the yaml in build will still exist. We will delete the v1alpha2 api definition in code in 1.16

Yes, this PR will not delete the yaml generated by generate crd under build. It will only delete the excess version of yaml in the chart package, so as not to affect the correct deployment.

**Comment by luomengY** [comment]
> OK, now we will delete the v1alpha2 device yaml in manifests, but the yaml in build will still exist. We will delete the v1alpha2 api definition in code in 1.16

Yes, this PR will not delete the yaml generated by generate crd under build. It will only delete the historical version of yaml in the chart package, so as not to affect the correct deployment.

**Comment by wbc6080** [comment]
I have a new idea. The generate-crds.sh script will only generate the v1beta1 version of yaml, so we only need to delete the v1alpha2 version of device.yaml under the manifests. There is no need to modify the script. Prevent script deleting user-defined files under some special circumstances

**Comment by luomengY** [comment]
> I have a new idea. The generate-crds.sh script will only generate the v1beta1 version of yaml, so we only need to delete the v1alpha2 version of device.yaml under the manifests. There is no need to modify the script. Prevent script deleting user-defined files under some special circumstances



> v1alpha2

Okay, considering this, I can remove the modified script. The v1alpha2 version under the manifest has been removed from this PR.

**Comment by Shelley-BaoYue** [comment]
/lgtm 

I think this PR is necessary and need cherry-pick to release-1.15. When keadm init registers the v1alpha2 device and devicemodel crds, CloudCore reports too many error logs.

image

**Comment by luomengY** [comment]
> /lgtm
> 
> I think this PR is necessary and need cherry-pick to release-1.15. When keadm init registers the v1alpha2 device and devicemodel crds, CloudCore reports too many error logs.
> 
> image

There is indeed a problem with not removing v1alpha2. Wait for this PR to merge before cherry-pick to release-1.15.

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by fisherxu** [comment]
Let's cherry-pick to release-1.15, thanks

**Comment by luomengY** [comment]
> Let's cherry-pick to release-1.15, thanks

ok，Can you help Cherry Pick? Every time I execute this script, it is interrupted due to network issues. @cl2017 @wbc6080

**Comment by fisherxu** [comment]
@luomengY Can you show the error logs when it's interrupted?

**Comment by luomengY** [comment]
> @luomengY Can you show the error logs when it's interrupted?

error

**Comment by luomengY** [comment]
> @luomengY Can you show the error logs when it's interrupted?

Now it's ok.

**Pull request merged**
