### PR TITLE
Fix some spelling errors

### PR DESCRIPTION
**Pull request by muxuelan**
**What type of PR is this?**
/kind lgtm

**What this PR does / why we need it**:
Fix some spelling errors.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
lgtm

**Comment by fisherxu** [comment]
@muxuelan Please squash the commits :)

**Comment by muxuelan** [comment]
的

**Comment by muxuelan** [comment]
> @muxuelan Please squash the commits :)

okay~

**Comment by muxuelan** [comment]
okay~

**Comment by muxuelan** [comment]
> @muxuelan Please squash the commits :)

okay~

**Comment by fisherxu** [comment]
> > @muxuelan Please squash the commits :)
> 
> okay~

The commit message needs to be updated too.

**Comment by muxuelan** [comment]
> > > @muxuelan Please squash the commits :)
> > 
> > 
> > okay~
> 
> The commit message needs to be updated too.



> > > @muxuelan Please squash the commits :)
> > 
> > 
> > okay~
> 
> The commit message needs to be updated too.

okay ~

**Pull request merged**
