### PR TITLE
fix log output format fails

### PR DESCRIPTION
**Pull request by Fish-pro**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

The log output format fails to be changed

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by vincentgoat — COMMENTED** [review]
/lgtm

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
