### PR TITLE
adding lint checking in keadm

### PR DESCRIPTION
**Pull request by subpathdev**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**
Add lint checking on kubeadm as a separate travis job

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by subpathdev** [comment]
why is this pending? how can i receive information about this?

**Comment by sids-b** [comment]
@subpathdev , we have deployed PROW as bot for this repository recently. Some features may not have been configured correctly. We will manually merge the PR soon :)

**Comment by kevin-wangzefeng** [comment]
Manually merging since bot not yet fixed.

**Pull request merged**
