### PR TITLE
move constants in common

### LINKED ISSUE #1221: suggest  put all the module name definitions under /common/constants/module.go
**What would you like to be added/modified**:

now , The name and group name of each module is defined under its own package , but we often need to quote each other. Even a lot of local code  redefined the module name.

**Why is this needed**:

suggest  put all the module name definitions under  `/common/constants/module.go`。Use these constants in the code as long as you use module name and group.

### PR DESCRIPTION
**Pull request by du2016**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

/kind feature

**What this PR does / why we need it**:

move constants in common

**Which issue(s) this PR fixes**:

Fixes #1221 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
Thanks! @du2016  Will help to review soon.

**Comment by kadisi** [comment]
good, but It is recommended to reduce the number of source files in the `common/constants`  directory.  Merge some source files into one。

**Comment by kadisi** [comment]
@du2016 It is recommended to split into multiple prs and create an issue , use task list to track it。

**Comment by du2016** [comment]
@kadisi ok ,thanks, i will split it.

**Pull request closed without merging**
