### PR TITLE
run fuzzers in CI

### PR DESCRIPTION
**Pull request by AdamKorcz**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR will run the fuzzers every time a PR is made. It is enabled by way of OSS-Fuzz's CIFuzz: https://google.github.io/oss-fuzz/getting-started/continuous-integration/. Each fuzzer will run for 20 minutes.

@gy95 @vincentgoat @kevin-wangzefeng

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by AdamKorcz** [comment]
Failing CI should be fixed by https://github.com/kubeedge/kubeedge/pull/3911

**Review by vincentgoat — APPROVED** [review]
LGTM

**Comment by vincentgoat** [comment]
cc @fisherxu, it is ready for oss-fuzz CI integration, please take a look and merge this PR, thanks.

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
