### PR TITLE
delete useless old container_manager

### PR DESCRIPTION
**Pull request by kadisi**
Signed-off-by: zhangjie <iamkadisi@163.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

/kind cleanup
**What this PR does / why we need it**:

old `container_manager` is useless, now we use new `container_manager` of kubelet package.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
/lgtm
Thanks for the cleanup.

**Comment by fisherxu** [comment]
@kadisi  please resolve the conflict, and let's got it merged :)

**Comment by sids-b** [comment]
Thanks @kadisi 

/approve

/lgtm

**Pull request merged**
