### PR TITLE
keadm support to fix panic error when port field is not mentioned during keadm join and reset

### PR DESCRIPTION
**Pull request by srivatsav123**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind bug

**What this PR does / why we need it**:
keadm support to fix panic error when port field is not mentioned during keadm join and reset
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
keadmjoin
keadmreset

### CODE REVIEW

**Comment by rohitsardesai83** [comment]
@srivatsav123 , please create an issue to track this.

**Comment by subpathdev** [comment]
https://github.com/kubeedge/kubeedge/blob/4315a2ce5f5772c4c719e2a00038f11fcdedae32/keadm/app/cmd/util/edgecoreinstaller.go#L155
has the same if condition as line 150; please merge the if body

**Comment by rohitsardesai83** [comment]
@srivatsav123 , please address the review comments.

**Comment by sids-b** [comment]
Lets get this one merged as it is a non-blocking code issue and we can fix it in further PRs

**Pull request merged**
