### PR TITLE
fix iptables-manager controller-manager image name

### PR DESCRIPTION
**Pull request by gy95**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix release image name
iptablesmanager -> iptables-manager
controllermanager -> controller-manager
**Which issue(s) this PR fixes**:

Fixes #
https://github.com/kubeedge/kubeedge/pull/4615#issuecomment-1442711469
test on private branch: https://github.com/gy95/kubeedge/actions/runs/4268110773
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by vincentgoat — COMMENTED** [review]
/lgtm

**Review by wenchajun — APPROVED** [review]

**Comment by wenchajun** [comment]
If so, can you release a new version of the image as soon as possible, I can't wait to use the latest version.

**Comment by gy95** [comment]
sure,we can just sync images between controllermanager and controller-manager :)

**Comment by benjaminhuo** [comment]
Can this be merged ASAP?
The 1.13 release image is still 1.12

**Comment by gy95** [comment]
> sure,we can just sync images between controllermanager and controller-manager :)
> 
> ```
> skopeo copy -a docker://kubeedge/controllermanager:v1.13.0 docker://kubeedge/controller-manager:v1.13.0
> skopeo copy -a docker://kubeedge/iptablesmanager:v1.13.0 docker://kubeedge/iptables-manager:v1.13.0
> ```

can use skopeo to sync images, ptal @fisherxu

**Comment by wenchajun** [comment]
Are there any updates or progress?

**Comment by benjaminhuo** [comment]
> Are there any updates or progress?

@fisherxu @gy95 @vincentgoat @chendave Guys, are you ok with this PR?

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Comment by benjaminhuo** [comment]
> sure,we can just sync images between controllermanager and controller-manager :)
> 
> ```
> skopeo copy -a docker://kubeedge/controllermanager:v1.13.0 docker://kubeedge/controller-manager:v1.13.0
> skopeo copy -a docker://kubeedge/iptablesmanager:v1.13.0 docker://kubeedge/iptables-manager:v1.13.0
> ```

@fisherxu Would you help to sync the images to the correct repo?
And then this PR can be merged too! https://github.com/kubeedge/kubeedge/pull/4615

Thanks
Ben

**Pull request merged**
