### PR TITLE
Stop to output the detail of licenses diff

### LINKED ISSUE #2168: Stop to output the detail of licenses diff
**What would you like to be added/modified**:
When developer use `make verify` to vefity vendor-license, it log out too long information and make it hard to get useful information. Out put below have 18000+ lines:
image

### PR DESCRIPTION
**Pull request by GsssC**
**What type of PR is this?**
Improvment

**What this PR does / why we need it**:
When developer use make verify to vefity vendor-license, it log out too long information and make it hard to get useful information
**Which issue(s) this PR fixes**:

Fixes #2168

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
This file is from upstream kubernetes, maybe add inline comments on the changed line?

**Comment by GsssC** [comment]
@kevin-wangzefeng  :-), well, I have added comment below `KubeEdge Authors`

**Pull request merged**
