### PR TITLE
context_channel clean up

### PR DESCRIPTION
**Pull request by wackxu**
Signed-off-by: wackxu <xushiwei5@huawei.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
LGTM   please rebase master to fix keadm e2e CI @wackxu

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
