### PR TITLE
Updated keadm setup files for successful installation of KubeEdge

### PR DESCRIPTION
**Pull request by bitvijays**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
1. Updated constant.go to install a) DefaultK8SVersion to 1.16.1 from 1.14.1 b) DefaultKubeEdgeVersion to 1.1.0 from 0.30
2. Updated cloudinstaller.go to fix Issue 1245, 1139
3. Updated ubuntuinstaller.go to fix Issue 1356

**Which issue(s) this PR fixes**:
Fixes # 
https://github.com/kubeedge/kubeedge/issues/1245, https://github.com/kubeedge/kubeedge/issues/1139,
https://github.com/kubeedge/kubeedge/issues/1356

Also, closes Pull-Request https://github.com/kubeedge/kubeedge/pull/1193

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No

### CODE REVIEW

**Comment by bitvijays** [comment]
@fisherxu @naveensriram Hope you are doing well. Would it be possible to review this Pull-Request? The more we delay, the more difficult it would become to approve this? If there are some changes to be met, let me know.

**Comment by subpathdev** [comment]
Please update the versions to KubeEdge 1.2.0 and Kubernetes 1.17.0

**Comment by subpathdev** [comment]
Close #1472

**Comment by fisherxu** [comment]
Dumplicate with #1475 , close it first :)

**Pull request closed without merging**
