### PR TITLE
Add a note comment for default value modification of `edged.rootDirectory`

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Add a note comment for change default value of `edged.rootDirectory`, from `/var/lib/edged` to `/var/lib/kubelet`, to keep consistent with kubelet.  

File directories consistent with kubelet can reduce maintain costs. In addition, kubeedge can seamlessly connect to native Kubernetes resources.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**: 

**Does this PR introduce a user-facing change?**:

```release-note
In v1.20, the default value of edged.rootDirectory will be changed to "/var/lib/kubelet". If you want to continue using "/var/lib/edged", please modify the edgecore configuration. 
```

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
/hold
wait for discussion.

**Review by fujitatomoya — COMMENTED** [review]
@Shelley-BaoYue i believe that this is a right way to go, but only questions is there would be conflict possibility with `kubelet` in any ways? for example, i do not think this is likely but if user is trying both `kubelet` and `edgecore` for testing or something (production phase, this is not gonna happen), they do not want to see the conflicts and unexpected problems.

**Comment by Shelley-BaoYue** [comment]
> @Shelley-BaoYue i believe that this is a right way to go, but only questions is there would be conflict possibility with `kubelet` in any ways? for example, i do not think this is likely but if user is trying both `kubelet` and `edgecore` for testing or something (production phase, this is not gonna happen), they do not want to see the conflicts and unexpected problems.

@fujitatomoya Thank you for your advice. It's true that the question you raised has not been considered before. Although kubelet and edgecore cannot run on edge nodes at the same time https://github.com/kubeedge/kubeedge/blob/master/edge/cmd/edgecore/app/server.go#L187, I will seriously consider whether there is a possibility of running at the same time in the future.

**Comment by fujitatomoya** [comment]
> Although kubelet and edgecore cannot run on edge nodes at the same time

yeah, i am aware of this. i was thinking more like, deleting the files under `/var/lib/kubelet` that kind of unexpected problem for each other. sorry i do not have actual conflict use case to point that out, maybe this is false alarm... just wanted to know if there is a possibility. thanks for checking!

**Comment by Shelley-BaoYue** [comment]
> > Although kubelet and edgecore cannot run on edge nodes at the same time
> 
> yeah, i am aware of this. i was thinking more like, deleting the files under `/var/lib/kubelet` that kind of unexpected problem for each other. sorry i do not have actual conflict use case to point that out, maybe this is false alarm... just wanted to know if there is a possibility. thanks for checking!

I have thought this problem, but as edged and kubelet are same in functionalities, there may be relatively few scenarios deploy both on same node. If such a situation does raise in the future, we'll need to consider not only directory conflict, but also port conflicts and other problem. 😄  

To ensure compatibility during version upgrades, I plan to first update the node comment in the upcoming 1.19 and note it in changelog. And make this modification in v1.20.

**Review by fisherxu — COMMENTED** [review]
/approve
/assign @WillardHu

**Pull request merged**
