### PR TITLE
Automated cherry pick of #3444: fix crd version error

### PR DESCRIPTION
**Pull request by gy95**
Cherry pick of #3444 on release-1.9.

#3444: fix crd version error

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by gy95** [comment]
cc @fisherxu PTAL 😄

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Comment by llhuii** [comment]
Will these v1.9.0 package files in https://github.com/kubeedge/kubeedge/releases/tag/v1.9.0 be updated automatically?

**Comment by fisherxu** [comment]
> 

No, we need to release v1.9.1 to fix the bug.

**Comment by llhuii** [comment]
Then incomplete, need to update these files, otherwise just cherry pick is not very useful

**Comment by llhuii** [comment]
> > 
> 
> No, we need to release v1.9.1 to fix the bug.

When to release v1.9.1? A CI checker of Sedna depends the latest kubeedge.

**Pull request merged**
