### PR TITLE
Add slack channel for kubeedge

### PR DESCRIPTION
**Pull request by m1093782566**

### CODE REVIEW

**Comment by mtk54101** [comment]
@m1093782566  we do not have the access power to the website(https://kubeedge.slack.com/).

**Comment by mtk54101** [comment]
@m1093782566  is there any business project using the KubeEdge

**Comment by m1093782566** [comment]
@mtk54101 I can invite you into the slack channel.

So, could you please tell me the email address that you login slack?

**Comment by mtk54101** [comment]
@m1093782566 my mailbox is 57170956@qq.com. I feel the website is very slowly, which is hard to access.

**Comment by m1093782566** [comment]
@mtk54101 No worries, invitation is just sent, please check your mail box.

**Comment by mtk54101** [comment]
@m1093782566 OK, thanks. i had joined the slack.

**Pull request merged**
