### PR TITLE
keadm: upgrade CRD version

### LINKED ISSUE #2797: Error: CustomResourceDefinition.apiextensions.k8s.io "clusterobjectsyncs.reliablesyncs.kubeedge.io" is invalid: [spec.versions: Invalid value
**What happened**:
**root@douding-test:/home/douding# keadm init                                              
Kubernetes version verification passed, KubeEdge installation will start...
--2021-04-21 16:18:08--  https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_device.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8715 (8.5K) [text/plain]
Saving to: ‘devices_v1alpha1_device.yaml’

devices_v1alpha1_de 100%[===================>]   8.51K  --.-KB/s    in 0.03s   

2021-04-21 16:18:09 (261 KB/s) - ‘devices_v1alpha1_device.yaml’ saved [8715/8715]

Converted links in 0 files in 0 seconds.
--2021-04-21 16:18:09--  https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha1_devicemodel.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10576 (10K) [text/plain]
Saving to: ‘devices_v1alpha1_devicemodel.yaml’

devices_v1alpha1_de 100%[===================>]  10.33K  --.-KB/s    in 0.04s   

2021-04-21 16:18:10 (290 KB/s) - ‘devices_v1alpha1_devicemodel.yaml’ saved [10576/10576]

Converted links in 0 files in 0 seconds.
--2021-04-21 16:18:10--  https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/reliablesyncs/cluster_objectsync_v1alpha1.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2861 (2.8K) [text/plain]
Saving to: ‘cluster_objectsync_v1alpha1.yaml’

cluster_objectsync_ 100%[===================>]   2.79K  --.-KB/s    in 0.03s   

2021-04-21 16:18:10 (91.7 KB/s) - ‘cluster_objectsync_v1alpha1.yaml’ saved [2861/2861]

Converted links in 0 files in 0 seconds.
Error: CustomResourceDefinition.apiextensions.k8s.io "clusterobjectsyncs.reliablesyncs.kubeedge.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc006ca0190), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00c8724e0), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc006ca0190), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00c8724e0), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead)]
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.2.1  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver

Flags:
      --advertise-address string   Use this key to set SANs in certificate of cloudcore. eg: 10.10.102.78,10.10.102.79
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080

F0421 16:18:10.931681   25006 keadm.go:27] CustomResourceDefinition.apiextensions.k8s.io "clusterobjectsyncs.reliablesyncs.kubeedge.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc006ca0190), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00c8724e0), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc006ca0190), Subresources:(*apiextensions.CustomResourceSubresources)(0xc00c8724e0), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead)]
goroutine 1 [running]:
k8s.io/klog.stacks(0xc000448000, 0xc000482500, 0x470, 0x4c4)
        /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:883 +0xb8
k8s.io/klog.(*loggingT).output(0x1f9cf60, 0xc000000003, 0xc0004408c0, 0x1f0d095, 0x8, 0x1b, 0x0)
        /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:834 +0x330
k8s.io/klog.(*loggingT).printDepth(0x1f9cf60, 0xc000000003, 0x1, 0xc000027f40, 0x1, 0x1)
        /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:706 +0x129
k8s.io/klog.(*loggingT).print(...)
        /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:697
k8s.io/klog.Fatal(...)
        /root/.gvm/pkgsets/go1.13.4/global/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1264
main.main()
        /root/codes/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0x8a**
**What you expected to happen**:
Kubernetes version verification passed, KubeEdge installation will start...
Expected or Default KubeEdge version 1.2.1 is already downloaded
...
KubeEdge cloudcore is running, For logs visit:  /var/log/kubeedge/cloudcore.log
CloudCore started
**How to reproduce it (as minimally and precisely as possible)**:
```
# curl -fsSL https://get.docker.com | sudo sh -s -- --mirror Aliyun
# sudo usermod -aG docker $USER
# sudo mkdir -p /etc/docker
# sudo tee /etc/docker/daemon.json <<-'EOF'
{
 "exec-opts": ["native.cgroupdriver=systemd"],
 "log-driver": "json-file",
 "log-opts": {
 "max-size": "100m"
 },
 "storage-driver": "overlay2",
 "registry-mirrors": ["https://t9ab0rkd.mirror.aliyuncs.com"]
}
EOF
# sudo systemctl daemon-reload
# sudo systemctl restart docker
# curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | sudo apt-key add -
# add-apt-repository "deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main"
# apt-get update
# apt-get install -y kubelet=1.18.5* kubeadm=1.18.5* kubectl=1.18.5*
# wget https://github.com/kubeedge/kubeedge/releases/download/v1.3.1/keadm-v1.3.1-linux-amd64.tar.gz
# tar zxvf keadm-v1.3.1-linux-amd64.tar.gz
# cd keadm-v1.3.1-linux-amd64
# ./keadm init

```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           4
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               62
Model name:          Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
Stepping:            4
CPU MHz:             2693.509
BogoMIPS:            5387.01
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            30720K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep arat md_clear flush_l1d arch_capabilities
  - OS (e.g. `cat /etc/os-release`):
 NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
  - Kernel (e.g. `uname -a`):
 Linux douding-test 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by daixiang0**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

After upgrade CRD from v1beta1 to v1, client-go caller should update as well.

**Which issue(s) this PR fixes**:

Fixes #2797 #2795

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
/hold
For version compatibility, holding for a while.

**Comment by zhaochengwei** [comment]
i merge the pr local
I still got 
```
root@douding-test:/home/douding/go/src/github.com/kubeedge/kubeedge# ./_output/local/bin/keadm init
Kubernetes version verification passed, KubeEdge installation will start...
Error: CustomResourceDefinition.apiextensions.k8s.io "devicemodels.devices.kubeedge.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of KubeEdge cloud component

keadm init --kubeedge-version=1.5.0  --kube-config=/root/.kube/config

  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --advertise-address string   Use this key to set IPs in cloudcore's certificate SubAltNames field. eg: 10.10.102.78,10.10.102.79
      --domainname string          Use this key to set domain names in cloudcore's certificate SubAltNames field. eg: www.cloudcore.cn,www.kubeedge.cn
  -h, --help                       help for init
      --kube-config string         Use this key to set kube-config path, eg: $HOME/.kube/config (default "/root/.kube/config")
      --kubeedge-version string    Use this key to download and use the required KubeEdge version
      --master string              Use this key to set K8s master address, eg: http://127.0.0.1:8080
      --tarballpath string         Use this key to set the temp directory path for KubeEdge tarball, if not exist, download it

F0422 14:18:07.373976   87898 keadm.go:27] CustomResourceDefinition.apiextensions.k8s.io "devicemodels.devices.kubeedge.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc0006c4000, 0x172, 0x1c6)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2bde320, 0xc000000003, 0x0, 0x0, 0xc000204bd0, 0x21bf2fa, 0x8, 0x1b, 0x1dbc200)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printDepth(0x2bde320, 0xc000000003, 0x0, 0x0, 0x1, 0xc0009bff68, 0x1, 0x1)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:718 +0x165
k8s.io/klog/v2.(*loggingT).print(...)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:703
k8s.io/klog/v2.Fatal(...)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1436
main.main()
        /home/douding/go/src/github.com/kubeedge/kubeedge/keadm/cmd/keadm/keadm.go:27 +0xa6

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2bde320)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 45 [IO wait]:
internal/poll.runtime_pollWait(0x7f9855b700c8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00065e998, 0x72, 0x800, 0x8b2, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00065e980, 0xc000211b00, 0x8b2, 0x8b2, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc00065e980, 0xc000211b00, 0x8b2, 0x8b2, 0x8ad, 0xc000211b00, 0x5)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0001c4000, 0xc000211b00, 0x8b2, 0x8b2, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0005682b8, 0xc000211b00, 0x8b2, 0x8b2, 0x8ad, 0xc000620800, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0001c6278, 0x1dbad00, 0xc0005682b8, 0x419925, 0x19b3660, 0x1b22ac0)
        /usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0001c6000, 0x1dbc820, 0xc0001c4000, 0x5, 0xc0001c4000, 0x392)
        /usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0001c6000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0001c6000, 0xc00022b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc000949b00, 0xc00080a2d8, 0x9, 0x9, 0x90b94b, 0xc000951c78, 0x4151a5)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1dbab60, 0xc000949b00, 0xc00080a2d8, 0x9, 0x9, 0x9, 0xc0001cbb40, 0x8aa2bd43299a00, 0xc0001cbb40)
        /usr/local/go/src/io/io.go:328 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader(0xc00080a2d8, 0x9, 0x9, 0x1dbab60, 0xc000949b00, 0x0, 0x0, 0x0, 0x0)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00080a2a0, 0xc0004f7fb0, 0x0, 0x0, 0x0)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000951fa8, 0x0, 0x0)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1794 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc00018aa80)
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:1716 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /home/douding/go/src/github.com/kubeedge/kubeedge/vendor/golang.org/x/net/http2/transport.go:695 +0x66e
```

**Comment by zhaochengwei** [comment]
image

**Comment by daixiang0** [comment]
@zhaochengwei now do not need this patch any more :)

/retitle keadm: upgrade CRD version

**Comment by daixiang0** [comment]
@fisherxu 

In fact even we say that only support 3 version, our codes support more.

In this way, I think #2450 also fix version compatibility.

**Comment by zhaochengwei** [comment]
So what I need to do and solve the problem

**Pull request closed without merging**
