### PR TITLE
fix: missing invoke StartGarbageCollection func bug

### LINKED ISSUE #2562: Why so many dead containers？MaxContainers is not effect
**What happened and what you expected to happen**:
I noticed that there are many dead containers on the node. So I modified the MaxContainers configuration in edgecore.yaml, but it didn't work.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>

### PR DESCRIPTION
**Pull request by hackers365**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
edge missing invoke StartGarbageCollection func

**Which issue(s) this PR fixes**:

Fixes #2562

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
Thanks for the fix, could you also add tests?

And DCO check is failing, please commit with author info that is associated with your github account, and commit with `git commit -s`

**Comment by hackers365** [comment]
> 
> 
> Thanks for the fix, could you also add tests?

I test it on my edge node, everything is ok.

Do you mean adding unit tests？

> 
> And DCO check is failing, please commit with author info that is associated with your github account, and commit with `git commit -s`

done

**Comment by kevin-wangzefeng** [comment]
Better add e2e tests, but unit tests are also fine.

**Comment by hackers365** [comment]
> 
> 
> Better add e2e tests, but unit tests are also fine.

I try do it

**Comment by fisherxu** [comment]
Looks like the `StartGarbageCollection` is deleted by mistake in this PR, let's add back first, and add test in follow-up pr.   https://github.com/kubeedge/kubeedge/pull/2223/files#diff-ad180820c34699a742bd7e2b672c310cfc1a3e8da8ad5a40c78623cbcd8d0472L320

**Comment by fisherxu** [comment]
@hackers365 Looks like your email addr in the commit haven't associated with your github account :)
image

**Comment by fisherxu** [comment]
So github cannot identify you as a contributor :)

**Comment by hackers365** [comment]
> 
> 
> So github cannot identify you as a contributor :)

I will fix this problem in the next pr

**Comment by fisherxu** [comment]
> > So github cannot identify you as a contributor :)
> 
> I will fix this problem in the next pr

Just need to add your email addr to your github settings.

**Pull request merged**
