### PR TITLE
Automated cherry pick of #470: update setup steps in docs.kubeedge.io

### PR DESCRIPTION
**Pull request by rohitsardesai83**
Cherry pick of #470 on release-0.3.

#470: update setup steps in docs.kubeedge.io

### CODE REVIEW

**Comment by m1093782566** [comment]
We may do not need to cherry-pick document updates?

**Comment by rohitsardesai83** [comment]
> We may do not need to cherry-pick document updates?

These setup steps are needed for the release 0.3

**Comment by m1093782566** [comment]
> These setup steps are needed for the release 0.3

Okay to have the fix if we need it.

/approve

**Pull request merged**
