### PR TITLE
README: update compatibility for Golang

### LINKED ISSUE #2089: KubeEdge 1.4 compatibility for Golang 1.13
**What happened**:

My golang version is 1.13.4, and the kubeedge version is as same as the repo.

When `$ make verify`, it reports:

```
bash hack/verify-vendor-licenses.sh
-mod=mod not supported (can be '', 'readonly', or 'vendor')
```

image

And for golang 1.13.4, `$ go help build` says:

```
	-mod mode
		module download mode to use: readonly or vendor.
		See 'go help modules' for more.
```

image

But according to `https://docs.kubeedge.io/en/latest/contributing/contribute.html#preparation`, it supports golang1.13 version.

image

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2089

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
KubeEdge 1.4 works fine with go 1.13.

**Comment by daixiang0** [comment]
In fact it may mislead contirbutors, since we need 1.14+ go version to build.
See https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#go.

**Comment by fisherxu** [comment]
1.13 can build successfully

**Comment by daixiang0** [comment]
See #2089

**Pull request merged**
