### PR TITLE
kubeedge installer for centos

### PR DESCRIPTION
**Pull request by congfairy**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/kind feature

I have tried to squash my previous commit,but the commits are still there,could anyone help to explain how could I submit the pr with only one commit?Thanks.

### CODE REVIEW

**Comment by congfairy** [comment]
@m1093782566 @kevin-wangzefeng  could help me to review the code?Thanks.

**Comment by subpathdev** [comment]
you can squash your commit by using rebase. These sample command could help:
```
git rebase -i master
```
This will compare the master branch with your own branch and in a list you will find all your commits.
It will also print a dialog with the meaning of the commands.
If you need further help, you can write a message to me in the slack workspace.

**Comment by congfairy** [comment]
@subpathdev Hi, I still have some problem but I couldn't find you on slack now.And I would like to ask that must I submit the pr from my master?Is that ok for me to submit the pr from my other branch?Thanks.

**Comment by kevin-wangzefeng** [comment]
Once a PR is opened, you can always push to the source branch to refresh the PR.
And you may indicate the "--force" flag when pushing after you use `git rebase` command to squash your commits.

**Pull request closed without merging**
