### PR TITLE
E2E test for application with liveness probe

### PR DESCRIPTION
**Pull request by 1Shubham7**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

I have added e2e for adding the liveness probe configurations in deployment and checking if it works.

**Which issue(s) this PR fixes**:

Fixes a part of #5043 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by 1Shubham7** [comment]
please review this maintainers so that I can also work on other probe configurations.

Also I wanted to ask should we change these e2e tests to -

```
. "github.com/onsi/ginkgo/v2"
. "github.com/onsi/gomega"
```

like we do in some tests ([here](https://github.com/kubeedge/kubeedge/blob/master/cloud/test/integration/controllermanager/controllermanager_test.go))
that would make the code less verbose and more readable. You can choose one of the two so that it is consistent throughout the tests.

**Comment by 1Shubham7** [comment]
cc @fisherxu @Shelley-BaoYue @WillardHu

**Review by fisherxu — COMMENTED** [review]
The `liveness probe` e2e test should be included in conformance test? PTAL @Shelley-BaoYue @bzsuni @liyuerich

**Comment by Shelley-BaoYue** [comment]
> The `liveness probe` e2e test should be included in conformance test? PTAL @Shelley-BaoYue @bzsuni @liyuerich

Yes, conformance test has included this test.

**Review by Shelley-BaoYue — COMMENTED** [review]
Hi, @1Shubham7  you have done a perfect work with this e2e test, but in PR https://github.com/kubeedge/kubeedge/pull/5663, we has integrated Kubernetes conformance test in KubeEdge e2e CI, which includes probe related tests. Still thanks for your contributions!

**Comment by 1Shubham7** [comment]
thanks for acknowledging my work @Shelley-BaoYue. also thanks for positive evaluations. at that case we can close this PR, I will work on writing E2E for device plugin and complete my uncompleted PRs in coming days. thanks for guiding me and for these 3 months of mentorship @Shelley-BaoYue and @fisherxu  :)

**Pull request closed without merging**
