### PR TITLE
updating error message with keadm

### PR DESCRIPTION
**Pull request by subpathdev**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
we have now three commands with `make WHAT=cloud` `make WHAT=edge` `make WHAT=keadm` 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sids-b** [comment]
I think make currently builds edgesite as well

**Comment by subpathdev** [comment]
> I think make currently builds edgesite as well

Yes you are right. We should add `make WHAT=edgesite`.

**Comment by subpathdev** [comment]
I added `make WHAT=edgesite` as an extra option.

**Pull request merged**
