### PR TITLE
remove unused struct

### PR DESCRIPTION
**Pull request by xuxiawei**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by vincentgoat — APPROVED** [review]
LGTM

**Review by chendave — COMMENTED** [review]
Can you pls also remove this line pls?
https://github.com/kubeedge/kubeedge/blob/8ccc5e4668bfebb7f38cbd2f0329e57abd9fc211/pkg/stream/edgedexecconnection.go#L50

**Comment by xuxiawei** [comment]
> Can you pls also remove this line pls?

@chendave Thank you for your suggestion.
And I'd love to delete it, but I found that the associated branch was accidentally deleted by me and is now in an uneditable state. 
I can submit another PR to remove it later.
I'm very sorry about that.

**Comment by chendave** [comment]
> And I'd love to delete it, but I found that the associated branch was accidentally deleted by me and is now in an uneditable state.
I can submit another PR to remove it later.
I'm very sorry about that.

you needn't do that, pull this branch directly, following by edit and "push -f", just need to make sure the branch name is the same as this.

**Pull request closed without merging**
