### PR TITLE
Automated cherry pick of #5047: Fix upgrade time layout and lost time value issue

### PR DESCRIPTION
**Pull request by WillardHu**
Cherry pick of #5047 on release-1.15.

#5047: Fix upgrade time layout and lost time value issue

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by fisherxu** [comment]
The `Multiple docker image build ` failed is because disk space issue, is fixing in #5071

**Comment by WillardHu** [comment]
> The `Multiple docker image build ` failed is because disk space issue, is fixing in #5071

Ok, I'll wait for this issue to be fixed.

**Comment by fisherxu** [comment]
> > The `Multiple docker image build ` failed is because disk space issue, is fixing in #5071
> 
> Ok, I'll wait for this issue to be fixed.

The fix has been git merged, please rebase or generate new PR :)

**Comment by WillardHu** [comment]
> > > The `Multiple docker image build ` failed is because disk space issue, is fixing in #5071
> > 
> > 
> > Ok, I'll wait for this issue to be fixed.
> 
> The fix has been got merged, please rebase or generate new PR :)

I see there's already a cherry pick #5080. I'm waiting for it to be merged.

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
