### PR TITLE
fix the broken link

### PR DESCRIPTION
**Pull request by lou-lan**
**What type of PR is this?**
/kind documentation

**Which issue(s) this PR fixes**:
fix the broken link

### CODE REVIEW

**Comment by edisonxiang** [comment]
Thank you!
/lgtm

**Comment by m1093782566** [comment]
@edisonxiang You can merge this PR :)

**Comment by sids-b** [comment]
LGTM feature looks to be working for bot. Thanks @edisonxiang @pavan187

**Comment by m1093782566** [comment]
I think next we should enable ci-robot to merge PR by `lgtm` and `approve` labels?

cc @kevin-wangzefeng

**Comment by edisonxiang** [comment]
Yep. "/lgtm" is used by k8s:)

**Comment by kevin-wangzefeng** [comment]
Agreed, and probably include automatic cherry pick by bot？
发件人：Jun Du <notifications@github.com>
收件人：kubeedge/kubeedge <kubeedge@noreply.github.com>
抄 送：Kevin Wang <kevinwzf0126@gmail.com>;Mention <mention@noreply.github.com>
时间：2019-05-09 11:38:52
主 题：Re: [kubeedge/kubeedge] fix the broken link (#481)


I think next we should enable ci-robot to merge PR by lgtm and approve labels?

cc @kevin-wangzefeng<https://github.com/kevin-wangzefeng>

**Comment by sids-b** [comment]
@edisonxiang has already added code for merging PR I guess, Instead of OWNERS file in all packages, we currently have 1 Maintainers file now. I think that's the only change required ?

We may need to add few features for release purpose in bot. Like automated cherry pick suggested by Kevin, then it should be able to generate release tars and their checksums as well.
Thoughts ??

**Comment by m1093782566** [comment]
> Instead of OWNERS file in all packages, we currently have 1 Maintainers file now. I think that's the only change required ?

I like the OWNERS files instead of Mainters file as we can do fine-grained base on OWNERS file.

**Comment by kevin-wangzefeng** [comment]
Even for OWNERS files we don't need to add it everywhere in the begining. There's no much difference if we just have a top level OWNERS file.

As for the bot, probably we should just migrate to prow.

**Comment by kevin-wangzefeng** [comment]
> Even for OWNERS files we don't need to add it everywhere in the begining. There's no much difference if we just have a top level OWNERS file.

Just to be clear, I don't mind making the change now or later on. The bot issue should get more attention.

**Pull request merged**
