### PR TITLE
once is an unused value

### PR DESCRIPTION
**Pull request by cl2017**
Signed-off-by: chenlin.liu <chenlin.liu@daocloud.io>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
once is an unused value, add once.Do function

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gy95** [comment]
lgtm

**Comment by wackxu** [comment]
lgtm

**Comment by zc2638** [comment]
It is not necessary for the once of the `context` and the once of the `channel` to exist at the same time. Some refactoring may be required here.
ref: https://github.com/kubeedge/kubeedge/blob/master/staging/src/github.com/kubeedge/beehive/pkg/core/channel/context_channel.go#L41

**Comment by cl2017** [comment]
If it is not necessary for the once, we can remove unused once variable?

**Pull request closed without merging**
