### PR TITLE
Git ignore `coverage.out`

### PR DESCRIPTION
**Pull request by martin-g**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:
With it the `make integrationtest` CI job sometimes fails with:
```
 kubeedge::version::get_version_info
2024-11-06T14:46:03.0460491Z +++ git rev-parse 'HEAD^{commit}'
2024-11-06T14:46:03.0461327Z ++ GIT_COMMIT=b41528df048bc22e001b5c6a7eaa9d55ee08e121
2024-11-06T14:46:03.0462223Z +++ git status --porcelain
2024-11-06T14:46:03.1184989Z ++ git_status='?? coverage.out'
2024-11-06T14:46:03.1185834Z ++ [[ -z ?? coverage.out ]]
2024-11-06T14:46:03.1186468Z ++ GIT_TREE_STATE=dirty
2024-11-06T14:46:03.1189596Z +++ git describe --tags --abbrev=14 'b41528df048bc22e001b5c6a7eaa9d55ee08e121^{commit}'
2024-11-06T14:46:03.1211688Z ++ GIT_VERSION=
2024-11-06T14:46:03.1218025Z +++ echo ''
2024-11-06T14:46:03.1218878Z +++ sed 's/[^-]//g'
2024-11-06T14:46:03.1234968Z ++ DASHES_IN_VERSION=
2024-11-06T14:46:03.1235694Z ++ [[ '' == \-\-\- ]]
2024-11-06T14:46:03.1236302Z ++ [[ '' == \-\- ]]
2024-11-06T14:46:03.1236852Z ++ [[ dirty == \d\i\r\t\y ]]
2024-11-06T14:46:03.1237529Z ++ GIT_VERSION+=-dirty
2024-11-06T14:46:03.1238397Z ++ [[ -dirty =~ ^v([0-9]+)\.([0-9]+)(\.[0-9]+)?([-].*)?([+].*)?$ ]]
2024-11-06T14:46:03.1239665Z ++ [[ -dirty =~ ^v([0-9]+)\.([0-9]+)(\.[0-9]+)?(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]
2024-11-06T14:46:03.1241095Z ++ echo 'GIT_VERSION should be a valid Semantic Version. Current value: -dirty'
2024-11-06T14:46:03.1242927Z ++ echo 'Please see more details here: https://semver.org'
2024-11-06T14:46:03.1243813Z ++ exit 1
2024-11-06T14:46:03.1244969Z + goldflags='-s -w -buildid= GIT_VERSION should be a valid Semantic Version. Current value: -dirty
2024-11-06T14:46:03.1246280Z Please see more details here: https://semver.org'
2024-11-06T14:46:03.1247258Z make: *** [Makefile:160: integrationtest] Error 1
```

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE

### CODE REVIEW

**Review by wbc6080 — COMMENTED** [review]
Overall lgtm, but if I'm not mistaken this tip `goldflags='-s -w -buildid= GIT_VERSION should be a valid Semantic Version. Current value: -dirty` doesn't seem to have anything to do with `coverage.out`. Did you only clone the master branch of kubeedge? It cause that local kubeedge not containing any tag information, so the above error occurred.

**Comment by martin-g** [comment]
I don't know the code as good as you but:
```
2024-11-06T14:46:03.1185834Z ++ [[ -z ?? coverage.out ]]
2024-11-06T14:46:03.1186468Z ++ GIT_TREE_STATE=dirty
```
looks like the cause to me. 
`coverage.out` is returned by `git status --porcelain` and this leads to `GIT_TREE_STATE=dirty`

**Review by wbc6080 — COMMENTED** [review]
This problem may be because there is no tag information in your kubeedge repo, so GIT_VERSION+=-dirty is displayed instead of GIT_VERSION+=v1.19.0-dirty. However, it is also necessary to add coverage.out to Git ignore.
lgtm

**Comment by martin-g** [comment]
I think you are right!
The forking via the Github UI is usually shallow (just the default branch) and I don't remember checking the box for forking all tags.
This really explains the problem!

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
