### PR TITLE
fix pod exec is not close conn when edgecore is closed

### PR DESCRIPTION
**Pull request by lvfei103650**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When we use the exec pod function, when edgecore fails (for example, systemctl stop edgecore), exec will hang, the command line cannot be entered, and the tcp connection between apiserver and cloudcore's 10003 port is still connected.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by lvfei103650** [comment]
exec_hang
企业微信截图_16383497762296
the connection between apiserver and cloudcore:10003 canot closed


image

if edgecore is stoped, the second for{} cannot break and exit, so this case <-c.EdgePeerDone()  can't enter

so we add break for{} when c.WriteToTunnel(msg) is failed.

test reult:
exec_ok

企业微信截图_1638349804475

**Review by fisherxu — COMMENTED** [review]
Thanks for the fixing, looks good, and have you tried that if edgecore stopped and then restarted, will the terminal exit when type something?

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Comment by lvfei103650** [comment]
> Thanks for the fixing, looks good, and have you tried that if edgecore stopped and then restarted, will the terminal exit when type something?

yes,the terminal exit when type something

**Pull request merged**
