### PR TITLE
Add a timeout option to the golangci-lint command

### PR DESCRIPTION
**Pull request by WillardHu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Sometime the lint CI job will have a timeout error when executing golangci-lint, and now the `/retest` comment cannot be executed to re-execute CI, this will result in frequent close-reopen the PR to pass the CI check.

This fix sets the kubeedge repository's golangci-lint timeout option to 12min to reduce the probability of failure, the beehive and viaduct repository's golangci-lint execute quickly.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
`Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded`

Seems the lint check still failed after 5 mins..

**Comment by WillardHu** [comment]
> `Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded`
> 
> Seems the lint check still failed after 5 mins..

Yes, I saw another PR take a little more then 10 minutes to execute, the log likes: `level=info msg="Execution took 10m0.015152445s"`. I set the timeout to 12min and will try test it a few more times.

The error logs for action:
- https://github.com/kubeedge/kubeedge/actions/runs/6105784341/job/16569806562
- https://github.com/kubeedge/kubeedge/actions/runs/6105104617/job/16568090485
- https://github.com/kubeedge/kubeedge/actions/runs/6105024678/job/16567890581

**Comment by fisherxu** [comment]
Seems `keadm e2e` test always report Segmentation fault  error... `tests/scripts/keadm_e2e.sh: line 69: 28517 Segmentation fault      /usr/local/bin/keadm init --advertise-address=$MASTER_IP --profile version=$KUBEEDGE_VERSION --set cloudCore.service.enable=false --kube-config=$KUBECONFIG --force`

**Comment by WillardHu** [comment]
> Seems `keadm e2e` test always report Segmentation fault error... `tests/scripts/keadm_e2e.sh: line 69: 28517 Segmentation fault /usr/local/bin/keadm init --advertise-address=$MASTER_IP --profile version=$KUBEEDGE_VERSION --set cloudCore.service.enable=false --kube-config=$KUBECONFIG --force`
> 
> I have open an issue to track it, #5003

Yes, it works sometimes. It's amazing...

**Review by fisherxu — COMMENTED** [review]
/approve
/assign @Shelley-BaoYue

**Pull request merged**
