### PR TITLE
Remove useless parentheses

### PR DESCRIPTION
**Pull request by lvchenggang**
Signed-off-by: lvchenggang lvchenggang_yewu@cmss.chinamobile.com

What type of PR is this?
/kind feature

What this PR does / why we need it:
Remove useless parentheses in edged module.

Does this PR introduce a user-facing change?:
NONE

### CODE REVIEW

**Comment by zc2638** [comment]
There should be many such problems.
Can you try to add configuration to CI, as much as possible to automate to avoid the occurrence of such problems in the future.

**Comment by lvchenggang** [comment]
> There should be many such problems. Can you try to add configuration to CI, as much as possible to automate to avoid the occurrence of such problems in the future.

I will try it, if the implementation is successful, I will submit to next PR.

**Comment by lvchenggang** [comment]
Could this PR be merged?

**Comment by gy95** [comment]
some codes are derived from kubernetes, so better keep compatible with upstream code :)

**Comment by lvchenggang** [comment]
> some codes are derived from kubernetes, so better keep compatible with upstream code :)

......

**Pull request closed without merging**
