### PR TITLE
use net.JoinHostPort to assemble URL

### PR DESCRIPTION
**Pull request by YaozhongZhang**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
/lgtm
Would you like add your eamil that used in the commit to your github profile? Since now the github can't identify and count your contribution. @YaozhongZhang 
image

**Comment by daixiang0** [comment]
@YaozhongZhang hi, there are more than one place use ": port" , would you like to find and optimize all of them in this pr?

**Comment by YaozhongZhang** [comment]
> /lgtm
> Would you like add your eamil that used in the commit to your github profile? Since now the github can't identify and count your contribution. @YaozhongZhang
> image

@fisherxu Done, thanks.

**Comment by YaozhongZhang** [comment]
> @YaozhongZhang hi, there are more than one place use ": port" , would you like to find and optimize all of them in this pr?

@daixiang0  /PTAL

**Comment by kadisi** [comment]
/lgtm

thanks @YaozhongZhang

**Pull request merged**
