### PR TITLE
refine edgesite

### LINKED ISSUE #2869: Import apiserver-network-proxy dependency instead copy in
Ref: #2858

/assign @liufen90

### PR DESCRIPTION
**Pull request by liufen90**
Signed-off-by: liufen90 <564795204@qq.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
import functions and structs instead of copying code

**Which issue(s) this PR fixes**:

Fixes #2869 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by liufen90** [comment]
@fisherxu  Please have a look.

**Review by fisherxu — COMMENTED** [review]
Seems edgesite-agent only have main file now 👍  but edgesite-server still has lots of code?

**Comment by liufen90** [comment]
> Seems edgesite-agent only have main file now 👍 but edgesite-server still has lots of code?

Because we modified some functions of anp in edgesite-server.

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
