### PR TITLE
fix: security docs link 404

### LINKED ISSUE #4449: report security docs link 404
**What would you like to be added/modified**:

**Why is this needed**:

### PR DESCRIPTION
**Pull request by YTGhost**
Signed-off-by: HIHIA <283304489@qq.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4449 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by vincentgoat — COMMENTED** [review]
/lgtm

**Comment by vincentgoat** [comment]
Hi @YTGhost 
Can you also update the link in files [README.md](https://github.com/kubeedge/kubeedge/blob/master/README.md), [README_zh.md](https://github.com/kubeedge/kubeedge/blob/master/README_zh.md)?

In the repo [kubeedge/community](https://github.com/kubeedge/community) still exist this issue.

**Comment by YTGhost** [comment]
> Hi @YTGhost Can you also update the link in files [README.md](https://github.com/kubeedge/kubeedge/blob/master/README.md), [README_zh.md](https://github.com/kubeedge/kubeedge/blob/master/README_zh.md)?
> 
> In the repo [kubeedge/community](https://github.com/kubeedge/community) still exist this issue.

ok

**Comment by YTGhost** [comment]
@vincentgoat PTAL

**Comment by fisherxu** [comment]
@gy95 Please take a look at the CI, because we skip the test for docs, so all the actions are `Waiting for status to be reported`, can we try to skip the test and return success result?

**Comment by gy95** [comment]
we maybe need to create  a generic workflow to fix this

https://docs.github.com/cn/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

**Comment by fisherxu** [comment]
> we maybe need to create a generic workflow to fix this
> 
> https://docs.github.com/cn/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

Yes, in generic workflow we can skip the doc test as below? And remove the paths-ingnore in main workflow. @gy95 
```
name: ci
on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'
      - '**/OWNERS'
      - '**/MAINTAINERS'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - run: 'echo "No test required"'
```

**Comment by gy95** [comment]
no, I think we need two workflows, one conatains `paths`, the other contains `paths-ignore`
```
name: ci
on:
  pull_request:
    paths:
      - '**.md'
```
```
name: ci
on:
  pull_request:
    paths-ignore:
      - '**.md'
```
I guess that it's just the second CI overwrite the first, the second triggered,but the first not, with the same name, so that it display the second CI success status.

But this seems more complicated and duplicated

**Comment by gy95** [comment]
reference: https://github.com/gy95/kubeedge/pull/16

**Comment by fisherxu** [comment]
> reference: [gy95#16](https://github.com/gy95/kubeedge/pull/16)

Looks good, can open a pr to fix this.

**Review by vincentgoat — COMMENTED** [review]
lgtm

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
