### PR TITLE
cleanup all lint issue

### LINKED ISSUE #1623: make lint not cover all codes
Now `make lint` check codes by components, it miss check codes under pkgs and tests dirs.

I think run do lint check at root directory is enough.

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

Fixes #1623

/kind cleanup

### CODE REVIEW

**Comment by daixiang0** [comment]
CI failed since #1627.

**Comment by kevin-wangzefeng** [comment]
looks like git history is messed up on your branch

**Comment by daixiang0** [comment]
Emm, my mistake.

**Pull request merged**
