### PR TITLE
Device value not updated

### PR DESCRIPTION
**Pull request by subpathdev**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
the device values which are updated by the edge should be synchronized with the device resources in the K8S. (updating reported status)

**Special notes for your reviewer**:
the first two commits are issues, which are found in the process of identify the error

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sids-b** [comment]
I think a problem here is that edgecontroller group should be controller. Currently in edgecontroller/module.go the group function returns "edgecontroller" as module group.

Both devicecontroller and edgecontroller should either belong to same group "controller" or each of them should have a different group "edgecontroller" and "devicecontroller". The "controller" group should not be used only for devicecontroller.

**Comment by subpathdev** [comment]
@sids-b yes you are right this is a problem but can we discuss this in an extra issue and get this merged?

**Comment by sids-b** [comment]
Sure @subpathdev . Can we use sendToModule instead of sendToGroup here to avoid any confusions of module groups ?

**Comment by subpathdev** [comment]
I have renamed the group of the device controllers to mentioned your comment @sids-b. I think this is the best way to handle it. In the beehive module which are used to forward the message to the group of channels is not Send2Module (or SendToModule) implemented.

**Comment by subpathdev** [comment]
@kevin-wangzefeng please check again

**Comment by sids-b** [comment]
Thanks @subpathdev 

/approve

/assign @kevin-wangzefeng

**Comment by sids-b** [comment]
/hold 
for @kevin-wangzefeng re-approval

**Pull request merged**
