### PR TITLE
fix unlock in addDevice of membership

### PR DESCRIPTION
**Pull request by jidalong**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
a lock was in line 195-197:
> ```go
>if delta {
>	context.Lock(device.ID)
>}
> ```
unlock was in line 251-253:
> ```go
>if delta {
>	context.Unlock(device.ID)
>}
> ```
PR #3348 add log err if convert membership failed , if we use "continue" in line 244 before unlock, it may cause not relase lock as mentioned, so here we should remove it.

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
LGTM

**Comment by jidalong** [comment]
> LGTM

@gy95 Sorry to disturb, maybe kubeedge project need label '/lgtm' instead of 'LGTM' :)

**Comment by gy95** [comment]
this is waiting for approve @fisherxu :)

**Comment by jidalong** [comment]
> this is waiting for approve @fisherxu :)

OKey~Thanks

**Comment by zc2638** [comment]
Hello @jidalong, 
Because this project is internationally oriented, and English is the international common language. 
It is recommended that all submissions contain only English.
Could you change the title to pure English?
Thanks.

**Comment by jidalong** [comment]
> Hello @jidalong, Because this project is internationally oriented, and English is the international common language. It is recommended that all submissions contain only English. Could you change the title to pure English? Thanks.

@zc2638 Okey，Done.

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
