### PR TITLE
fix wrong build image command for cloudclore

### PR DESCRIPTION
**Pull request by wackxu**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```
/assign @gy95 @fisherxu

### CODE REVIEW

**Comment by gy95** [comment]
LGTM but need to fix DCO first :)

**Comment by gy95** [comment]
And there're three places need fixing also
https://github.com/kubeedge/kubeedge/blob/master/build/cloud/README.md
https://github.com/kubeedge/kubeedge/blob/master/build/cloud/README_zh.md

**Review by gy95 — COMMENTED** [review]
LGTM, @fisherxu  PTAL

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
