### PR TITLE
keadm: reset supports checking the node type according to the default configuration file

### LINKED ISSUE #2630: Keadm will not remove edge components when running "keadm reset" in v1.6.0
**What happened**:
Keadm will not remove edge component when running "keadm reset" in v1.6.0  

**What you expected to happen**:
Remove all edge components just like v1.5.0

  **v1.5.0:**
```bash
[root@centos78-edge-1 kubeedge]# keadm version
version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"8b0913e04ef4ef826af6715d336e23a66e3774df", GitTreeState:"clean", BuildDate:"2020-11-13T08:04:56Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
[root@centos78-edge-1 kubeedge]# ls -lh
total 115M
drwxr-xr-x 2 root root  24 Feb 20 15:54 ca
drwxr-xr-x 2 root root  42 Feb 20 15:54 certs
drwxr-xr-x 2 root root  27 Feb 20 16:20 config
-rwxr-xr-x 1 root root 70M Feb 20 15:54 edgecore
-rw-r--r-- 2 root root 159 Feb 20 15:50 edgecore.service
drwxr-xr-x 4 root root  46 Nov 13 16:56 kubeedge-v1.5.0-linux-amd64
-rw-r--r-- 1 root root 46M Feb 20 15:54 kubeedge-v1.5.0-linux-amd64.tar.gz
[root@centos78-edge-1 kubeedge]# keadm reset
KubeEdge edgecore is stopped, For logs visit:  /var/log/kubeedge/edgecore.log
[root@centos78-edge-1 kubeedge]# ls -la
total 12
drwxr-xr-x   2 root root    6 Mar 12 16:29 .
drwxr-xr-x. 85 root root 8192 Mar 12 16:00 ..
```
  **v1.6.0:**
```bash
[root@centos78-edge-1 kubeedge]# keadm version
version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"497b04a346f828b8e73601e6b0fc947f4184aed3", GitTreeState:"clean", BuildDate:"2021-02-27T12:21:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
[root@centos78-edge-1 kubeedge]# keadm reset
None of KubeEdge components are running in this host, exit
[root@centos78-edge-1 kubeedge]# ls -lh
total 122M
drwxr-xr-x 2 root root  27 Mar 12 17:05 config
-rwxr-xr-x 1 root root 74M Mar 12 17:05 edgecore
-rw-r--r-- 2 root root 160 Mar 12 17:05 edgecore.service
drwxr-xr-x 4 root root  46 Feb 27 20:30 kubeedge-v1.6.0-linux-amd64
-rw-r--r-- 1 root root 49M Mar 12 16:40 kubeedge-v1.6.0-linux-amd64.tar.gz
[root@centos78-edge-1 kubeedge]# ls /etc/systemd/system/edgecore.service -l
-rw-r--r-- 2 root root 160 Mar 12 17:05 /etc/systemd/system/edgecore.service
[root@centos78-edge-1 kubeedge]# systemctl status edgecore
● edgecore.service
   Loaded: loaded (/etc/systemd/system/edgecore.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2021-03-12 17:26:30 CST; 3s ago
  Process: 24563 ExecStart=/usr/local/bin/edgecore (code=exited, status=203/EXEC)
 Main PID: 24563 (code=exited, status=203/EXEC)
^C
```

**Environment**:
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.6.0
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): CentOS Linux release 7.8.2003 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1127.el7.x86_64

### PR DESCRIPTION
**Pull request by zc2638**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

`keadm reset` only checks whether the edgecore/cloudcore is running to judge whether to continue the reset operation.Many times when the node is not running properly, it needs to be reset

**Which issue(s) this PR fixes**:

Fixes #2630

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by swartz-k** [comment]
I think it would be better to check all files , if exist clean it, if not skip it. 
One possible situation, EdgeCore is not running, first  has cleaned YAML file but  broken by network or signal, second clean will stop because of no YAML file.

**Comment by zc2638** [comment]
/cc @fisherxu 
How about your opinion? Do you need to add a node type parameter to execute `reset` operation?

**Comment by fisherxu** [comment]
> I think it would be better to check all files , if exist clean it, if not skip it.
> One possible situation, EdgeCore is not running, first has cleaned YAML file but broken by network or signal, second clean will stop because of no YAML file.

> How about your opinion? Do you need to add a node type parameter to execute reset operation?

It's hard to find a perfect way to detect the nodetype, maybe we can do same reset actions in all cloud and edge nodes? And if the reset/uninstall targets does not exist, just ignore it. How do you think? @zc2638 @swartz-k

**Comment by swartz-k** [comment]
> It's hard to find a perfect way to detect the nodetype, maybe we can do same reset actions in all cloud and edge nodes? And if the reset/uninstall targets does not exist, just ignore it. How do you think? @zc2638 @swartz-k

Almost agree. But I think `cloudcore` and `edgecore` do have somethings different, example systemd service.

**Comment by zc2638** [comment]
> > I think it would be better to check all files , if exist clean it, if not skip it.
> > One possible situation, EdgeCore is not running, first has cleaned YAML file but broken by network or signal, second clean will stop because of no YAML file.
> 
> > How about your opinion? Do you need to add a node type parameter to execute reset operation?
> 
> It's hard to find a perfect way to detect the nodetype, maybe we can do same reset actions in all cloud and edge nodes? And if the reset/uninstall targets does not exist, just ignore it. How do you think? @zc2638 @swartz-k

I don't think it is a good idea If do same reset actions.It is a bad thing to delete the running container in the cloud, if kubeedge is deployed in the running k8s cluster environment.

**Pull request closed without merging**
