### PR TITLE
fix: print token with newline

### PR DESCRIPTION
**Pull request by wuxs**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
For a more friendly user interface when get token.

**Which issue(s) this PR fixes**:

Nope.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wackxu** [comment]
Please signoff the commit to fix the failed DCO test, thx :)

**Review by gy95 — CHANGES_REQUESTED** [review]
LGTM

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
