### PR TITLE
fix the groupmap while edgehub processing message

### PR DESCRIPTION
**Pull request by muxuelan**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
1. Before: The function pubConnectInfo of process.go will send same message twice to metamanager; 
    After: Tunction pubConnectInfo just send message to metamanager once.
2. The group name of ServiceBus is user, so in groupMap of process.go, key "user" is more suitable for ServiceBus instead of Eventbus.
3. Gropus of messages from cloud to edge just include resource(MetaGroup) and twin (TwinGroup) now,  so renaming the key "func" and "user"  don't affect edgehub dispatching message.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
Good catch!

Could add unit test for this?

**Comment by muxuelan** [comment]
> Good catch!
> 
> Could add unit test for this?

I think process_test.go is no problem, needn't to change.

**Comment by daixiang0** [comment]
Test case for twice send :)

**Comment by muxuelan** [comment]
> Test case for twice send :)

You mean add the test for func  pubConnectInfo ?

**Comment by muxuelan** [comment]
> Good catch!
> 
> Could add unit test for this?

Could this be approved?

**Comment by muxuelan** [comment]
> Test case for twice send :)

Could this be approved too as soon as possible？◠‿◠

**Pull request closed without merging**
