### PR TITLE
update sandboxImage to kubeedge/pause:3.6

### PR DESCRIPTION
**Pull request by gy95**
**What type of PR is this?**

**What this PR does / why we need it**:
keep kubeedge/pause version the same with k8s vendor sandbox image tag
https://github.com/kubeedge/kubeedge/blob/0de307ffae3694c8b45c510ddae0f9b8aef5f4c2/vendor/k8s.io/kubernetes/cmd/kubelet/app/options/container_runtime.go#L28-L32
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wackxu** [comment]
Do we  upload the image kubeedge/pause:3.5 to dockerhub?

**Comment by gy95** [comment]
yes, and if we bump k8s dependency to v1.23, we should also update kubeedge/pause:3.6 to dockerhub

**Comment by wackxu** [comment]
> yes, and if we bump k8s dependency to v1.23, we should also update kubeedge/pause:3.6 to dockerhub

In this version, we will upgrade the k8s dependency to v1.23, so we can update to kubeedge/pause:3.6 directly

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
