### PR TITLE
Apply become a reviewer

### PR DESCRIPTION
**Pull request by tangming1996**
Signed-off-by: ming.tang <ming.tang@daocloud.io>

What type of PR is this?
/kind documentation

What this PR does / why we need it:
I participated in the design and development of some features, such as edgeapp, nodegroup, keadm, sedna and so on. In addition, I often participate in community meetings and events, such as Open Source Summer 、lfx、academic Workshop. In the future, I hope to continue to be deeply involved in the development of community. My PR list is as follows:
https://github.com/kubeedge/kubeedge/pulls/tangming1996
https://github.com/kubeedge/kubeedge/pulls?q=is%3Apr+author%3Atangming1996+is%3Aclosed
https://github.com/kubeedge/kubeedge/issues/created_by/tangming1996
https://github.com/kubeedge/kubeedge/issues?q=is%3Aissue+author%3Atangming1996+is%3Aclosed
https://github.com/kubeedge/sedna/pulls?q=is%3Apr+author%3Atangming1996+is%3Aclosed
https://github.com/kubeedge/sedna/issues/created_by/tangming1996

Sponsors
@fisherxu 
@Shelley-BaoYue
@WillardHu

### CODE REVIEW

**Comment by tangming1996** [comment]
@fisherxu @Shelley-BaoYue @WillardHu Please help review my contribution, thank you very much！

**Review by fisherxu — COMMENTED** [review]
/lgtm
Thanks for your contributions :)
/hold
Wait for more comments :)

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm 
Thanks for your contributions!

**Review by fisherxu — COMMENTED** [review]
It seems that there are no objections, congratulations! @tangming1996 


/approve
/hold cancel

**Pull request merged**
