### PR TITLE
Automated cherry pick of #5086: Determine whether to push device data from mapper to edgeCore

### PR DESCRIPTION
**Pull request by wbc6080**
Cherry pick of #5086 on release-1.15.

#5086: Determine whether to push device data from mapper to edgeCore

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by Shelley-BaoYue** [comment]
You need to rebase the newest release-1.15 and push again to solve the failed ci.

**Review by fisherxu — COMMENTED** [review]
/approve

**Review by fisherxu — COMMENTED** [review]
/assign @WillardHu @Shelley-BaoYue

**Pull request merged**
