### PR TITLE
Add file suffix for edge/test/integration/scripts/fast_test

### PR DESCRIPTION
**Pull request by kuramal**
Signed-off-by: kuramal <linxxnil@126.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design

/kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:
Add file suffix for edge/test/integration/scripts/fast_test which is a shell script, and update the docs

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fisherxu** [comment]
Plz fix the CI :) @kuramal

**Comment by kuramal** [comment]
@fisherxu done.

**Pull request merged**
