### PR TITLE
Fix-4077: remove edgecontroller downstream endpointsManager avoid mem…

### LINKED ISSUE #4077: cloudcore memory leak in edgecontroller downstream endpointsmanager
**What happened**:

cloudcore memory leak happen in edgecontroller downstream endpointsmanager when k8s endpoints updated

**What you expected to happen**:

when k8s endpoints updated, endpointsmanager informer call updateFunc and push event to endpoints channel, but no consumer will receive it. When endpoints channel full, endpoints informer updateFunc halt and  informer DeltaFIFO get more and more event.
Remove endpointsmanager and servicemanager from downstream controller since them not be used any more, [remove edgemesh from edgecore](https://github.com/kubeedge/kubeedge/commit/dc9b9ba453f64fe27298405d17ca48fe70fe5ecd)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by neiba**
…ory leak

Signed-off-by: chengengkun <1366542563@qq.com>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4077

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wackxu** [comment]
please also remove file service.go and endpoint.go in  manager dir

**Comment by neiba** [comment]
> please also remove file service.go and endpoint.go in manager dir

**Comment by wackxu** [comment]
lgtm

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
