### PR TITLE
Enable e2e and integration test on ARM CI

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**

Add one of the following kinds:
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
Better to post pr in own repo, then CI would run in no time.

**Comment by chendave** [comment]
> Better to post pr in own repo, then CI would run in no time.
my personal repo is using travis-ci.org, this needs to test with travis-ci.com.

I think this won't work since `arm64-graviton2` need to run with travis-ci.com, there is no other way to provide the full VM solution.

see: https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by chendave** [comment]
> Better to post pr in own repo, then CI would run in no time.

>  my personal repo is using travis-ci.org, this needs to test with travis-ci.com.

Sorry, need to reverse the above statement, 
my personal repo is using travis-ci.com, this needs to test with travis-ci.org.
KubeEdge is using travis-ci.org, but seems `arm64-graviton2` doesn't support travis-ci.org

**Comment by daixiang0** [comment]
See [this](https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com) about difference between org and com.

**Comment by chendave** [comment]
okay, per the post here: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom, we need to switch to "travis-ci.com" ASAP, the deadline is approaching (December 31st, 2020), this might be reason why  `arm64-graviton2` doesn't support travis-ci.org.

**Comment by chendave** [comment]
This won't  be an issue after switching to travis-ci.com. 

/cc @kevin-wangzefeng  @fisherxu

**Comment by chendave** [comment]
looks like travis team did some update recently to support legacy *.org as well, but we still move to *.com soon.

**Comment by chendave** [comment]
see: https://docs.travis-ci.com/user/migrate/open-source-repository-migration for the migration.

**Comment by chendave** [comment]
@kevin-wangzefeng @fisherxu let's get this in, after this PR all the testcase are covered on ARM architecture.

**Comment by daixiang0** [comment]
Now org support it?

**Comment by chendave** [comment]
> Now org support it?

yes, but we still move to traivs.com sooner the better.

**Comment by kevin-wangzefeng** [comment]
/lgtm
/approve

Thanks

**Pull request merged**
