### PR TITLE
Grammar fixed in edged module

### PR DESCRIPTION
**Pull request by lvchenggang**
Signed-off-by: lvchenggang lvchenggang_yewu@cmss.chinamobile.com

What type of PR is this?
/kind feature

What this PR does / why we need it:
Fix some grammar problems in edged module.

Does this PR introduce a user-facing change?:
NONE

### CODE REVIEW

**Comment by gy95** [comment]
seems fossa error. :(

**Comment by lvchenggang** [comment]
> seems fossa error. :(

Yes it is.

**Comment by gy95** [comment]
/retest
Seems to have been recovered.

**Comment by lvchenggang** [comment]
Yeah, it has been recovered.

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
