### PR TITLE
add domain support for certgen.sh

### PR DESCRIPTION
**Pull request by lwabish**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
the original script failed when providing a domain name.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by fisherxu** [comment]
@lwabish Why do you build the certs manually instead of using the certs generted by cloudcore?

**Review by fisherxu — COMMENTED** [review]
@lwabish Why do you build the certs manually instead of using the certs generted by cloudcore?

**Comment by lwabish** [comment]
> @lwabish Why do you build the certs manually instead of using the certs generted by cloudcore?

I was following the [Enable kubectl logs Feature](https://kubeedge.io/en/docs/setup/keadm/#enable-kubectl-logs-feature)steps after install cloudcore and init my edge node. @fisherxu

**Comment by fisherxu** [comment]
Ok, it should only use the stream func.

**Comment by lwabish** [comment]
> Ok, it should only use the stream func.

yes,indeed. So should I leave the genCert() funciton as it was?

**Comment by lwabish** [comment]
> 

oh I see.
In this case, I deployed cloudcore in k8s,so I need to use cloudcore.kubeedge to generate the stream cert so that apiserver can locate cloudcore, is this right?

**Review by ramezanius — APPROVED** [review]

**Comment by fisherxu** [comment]
> In this case, I deployed cloudcore in k8s,so I need to use cloudcore.kubeedge to generate the stream cert so that apiserver can locate cloudcore, is this right?

Yes, if the cloudocre domain used for edgeside, the domain name maybe a public domain. If apiserver connects to the cloudcore, it may not have to use that public domin, domain name incluster should be also fine, like `svc.ns.cluster.local`.

Anyway, set the domain name in stream's certs is reasonable, and can we set another env value like `CLOUDCORE_DOMAINS`? And the docs also need to be updated :) @lwabish

**Review by fisherxu — COMMENTED** [review]
Looks good, and could you please squash the 4 commits? Thanks.

**Comment by lwabish** [comment]
previous commits squashed. 
is the "fetch upstream commit" necessary to be squashed too?

**Comment by fisherxu** [comment]
> previous commits squashed. is the "fetch upstream commit" necessary to be squashed too?

Yes, fetch upstream commit is no needed here :)

**Comment by lwabish** [comment]
> > previous commits squashed. is the "fetch upstream commit" necessary to be squashed too?
> 
> Yes, fetch upstream commit is no needed here :)

done

**Comment by fisherxu** [comment]
Thanks, and would you like to update the docs? Ref: https://github.com/kubeedge/website/blob/master/content/en/docs/setup/keadm.md#enable-kubectl-logs-feature

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Comment by lwabish** [comment]
> 

sure, i'll work on it later.
I also found that the stream certs of cloudcore deployed using helm was generated within the helm chart,  running `certgen.sh stream` is not needed in this case.  So maybe I could also try improving the doc about stream certs.

**Comment by lwabish** [comment]
> Thanks, and would you like to update the docs? Ref: https://github.com/kubeedge/website/blob/master/content/en/docs/setup/keadm.md#enable-kubectl-logs-feature

sure, i'll work on it later.
I also found that the stream certs of cloudcore deployed using helm was generated within the helm chart, running certgen.sh stream is not needed in this case. So maybe I could also try improving the doc about stream certs.

**Pull request merged**
