### PR TITLE
fix device status problem

### LINKED ISSUE #5327: Failed to update device status in the cloud
**What happened**:
Failed to update device status in the cloud
device状态未上报

**What you expected to happen**:
Correctly report device status to the cloud, and we can obtain the data reported by the device through the` kubectl describe` command
**How to reproduce it (as minimally and precisely as possible)**:
Create a mapper and create a device at the same time. The device data is correctly collected in the mapper log and reported to edgecore, but it is not updated successfully in the cloud.
**Anything else we need to know?**:
Analyzing the `upstream` code of `devicecontroller`, we can find that we look for the `devicestatus.twin` structure according to `twinName` and update the value of the `report` field. But the address returned here is the index variable `twin`, not the real `devicestatus.twin` address. Therefore, the device reported value in devicestatus was not successfully updated.

upstream
error

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25.10
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.15.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

### PR DESCRIPTION
**Pull request by wbc6080**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As described in #5327 , since we return the address of the index variable, not the address of `devicestatus.twin`, updating the status of devicetwin will fail. This PR returns the correct address of `devicestatus.twin`
**Which issue(s) this PR fixes**:

Fixes #5327 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wbc6080** [comment]
PTAL @luomengY @cl2017  thanks

**Comment by luomengY** [comment]
Thank you very much for discovering this issue. /lgtm

**Comment by wbc6080** [comment]
PTAL @cl2017 @WillardHu @fisherxu,  thanks

**Review by fisherxu — COMMENTED** [review]
/approve

**Comment by fisherxu** [comment]
@wbc6080 Plz cherry-pick to the release1.12~1.15 brranch if needed.

**Pull request merged**
