### PR TITLE
remove gpu codes

### PR DESCRIPTION
**Pull request by edisonxiang**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Support for the alpha.kubernetes.io/nvidia-gpu resource, which was deprecated in k8s v1.10, has been removed. The latest k8s version is using the resource exposed by DevicePlugins instead (nvidia.com/gpu). 

https://github.com/kubernetes/kubernetes/pull/61498

Since we will upgrade the k8s version in kubeedge, we need to cleanup these codes including gpu and nvida.

* "k8s.io/kubernetes/pkg/kubelet/gpu",	
* "k8s.io/kubernetes/pkg/kubelet/gpu/nvidia"

### CODE REVIEW

**Comment by rohitsardesai83** [comment]
@edisonxiang , please resolve the conflicts. Thanks.

**Comment by rohitsardesai83** [comment]
There is an open issue where this might be needed: https://github.com/kubeedge/kubeedge/issues/779. 
Should this code removal be part of the upgrade process ?

**Comment by edisonxiang** [comment]
@rohitsardesai83 rebased. I think we need to make a test for the way using device plugin to support gpu, and give some documents or some modifications in kubeedge.

**Comment by edisonxiang** [comment]
@rohitsardesai83 yep, it is better to make that gpu test after upgrade:)

**Comment by kevin-wangzefeng** [comment]
/approve
Thanks

**Pull request merged**
