### PR TITLE
Patch cloudcore rbac

### PR DESCRIPTION
**Pull request by zhu733756**
Signed-off-by: zhu733756 <zhu733756@kubesphere.io>

/kind bug

See https://github.com/kubeedge/edgemesh/issues/252#issuecomment-1000006246

/cc @fisherxu @gy95 @Poorunga

### CODE REVIEW

**Review by gy95 — COMMENTED** [review]
this file need fixing too
https://github.com/kubeedge/kubeedge/blob/eecaacaf9e0e1067189098b68a348db6a5155a8b/build/cloud/ha/01-ha-prepare.yaml#L32-L33

**Comment by zhu733756** [comment]
> this file need fixing too
> 
> https://github.com/kubeedge/kubeedge/blob/eecaacaf9e0e1067189098b68a348db6a5155a8b/build/cloud/ha/01-ha-prepare.yaml#L32-L33

Fixed

**Comment by gy95** [comment]
LGTM

**Review by fisherxu — COMMENTED** [review]
Looks good for this pr.
And we need a mechanism to manage the role, if add a client in edge, then always update the config file here, maybe it's not the right way..
/approve

**Comment by zhu733756** [comment]
> Looks good for this pr. And we need a mechanism to manage the role, if add a client in edge, then always update the config file here, maybe it's not the right way.. /approve

I think we can use a verify script integrated into CI to check these CRDs or K8s resources, developers will be reminded to find the changes.

**Comment by zhu733756** [comment]
> > Looks good for this pr. And we need a mechanism to manage the role, if add a client in edge, then always update the config file here, maybe it's not the right way.. /approve
> 
> I think we can use a verify script integrated into CI to check these CRDs or K8s resources, developers will be reminded to find the changes.

Or later, we can integrate a make cmd to do these changes at the same time.

**Comment by fisherxu** [comment]
> Or later, we can integrate a make cmd to do these changes at the same time.

There will be other resources that users use we don't know, so we need a extensionable mechanism to do this, it will be a big feature.

**Comment by zhu733756** [comment]
> > Or later, we can integrate a make cmd to do these changes at the same time.
> 
> There will be other resources that users use we don't know, so we need a extensionable mechanism to do this, it will be a big feature.

K8s use the kubebuilder annotations/markers to create roles.  The problem is how we catch the permissions, then we can remind users or patch it automatically.

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Pull request merged**
