### PR TITLE
Make ChannelContext a singleton

### PR DESCRIPTION
**Pull request by dddddai**
**What type of PR is this?**

/kind api-change
/kind design

**What this PR does / why we need it:**

As TODO addressed, make ChannelContext a singleton

**Which issue(s) this PR fixes:**

Fixes #

**Special notes for your reviewer:**

**Does this PR introduce a user-facing change?:**

NONE

### CODE REVIEW

**Comment by fisherxu** [comment]
@dddddai  Thanks for the fixing, and could you please add any PR description?

**Comment by dddddai** [comment]
> @dddddai Thanks for the fixing, and could you please add any PR description?

Thanks for your review, I have added a description

**Comment by fisherxu** [comment]
Since `InitContext` has called `once.Do`, so it's maybe no necessary to do it in `GetChannelContext`. :) @dddddai

**Comment by dddddai** [comment]
> Since `InitContext` has called `once.Do`, so it's maybe no necessary to do it in `GetChannelContext`. :) @dddddai

Yes,`NewChannelContext` is only called by `InitContext`, it's unnecessary if `NewChannelContext` won't be called elsewhere in the future.

**Pull request closed without merging**
