### PR TITLE
remove getURL func

### PR DESCRIPTION
**Pull request by fisherxu**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sids-b** [comment]
@fisherxu , we need to fix the UT for the corresponding file

**Comment by fisherxu** [comment]
@sids-b Have removed the getCloudUrl test

**Comment by sids-b** [comment]
Thanks @fisherxu 
/approve

**Pull request merged**
