### PR TITLE
fix force delete pod when node offline

### PR DESCRIPTION
**Pull request by Shelley-BaoYue**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix the same bug with this pr #4141 since v1.12 version

when node is offline and we force delete the pod in the node, and then the edge node is online,
the deleted pod container is always in the edge node unless we restart the edgecore.

### CODE REVIEW

**Comment by gy95** [comment]
not stale, continue?

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
