### PR TITLE
fix typing and grammar errors

### PR DESCRIPTION
**Pull request by suojy**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
fix typing and grammar errors
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
@suojy thanks for your contribution!

Now docs are moved to https://github.com/kubeedge/website, if you are interested, please check and fix in that repo!

**Comment by fisherxu** [comment]
> @suojy thanks for your contribution!
> 
> Now user docs are moved to https://github.com/kubeedge/website, if you are interested, please check and fix in that repo!

Proposals should bot be moved to website repo, need to find another place or keep them here.

**Comment by daixiang0** [comment]
Proposals do not belong to user docs, it is only for developers.

**Comment by fisherxu** [comment]
@suojy Could you please to rebase to the latest `master branch` to fix the ci issue?

**Comment by suojy** [comment]
> @suojy Could you please to rebase to the latest `master branch` to fix the ci issue?

Sure.

**Comment by fisherxu** [comment]
> > @suojy Could you please to rebase to the latest `master branch` to fix the ci issue?
> 
> Sure.

You need to squash the 5 commits to 1.

**Comment by fisherxu** [comment]
/lgtm
/approve
Thanks for the fixing!

**Pull request merged**
