### PR TITLE
initialize OWNERS file for device management

### PR DESCRIPTION
**Pull request by sids-b**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR adds OWNERS file for main device management modules at cloud(deviceController) and edge(deviceTwin)

**Which issue(s) this PR fixes**:
XREF #638

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
+1, binding.
Let's keep this PR open till end of Friday, to make sure no objections from others :-)

**Comment by chendave** [comment]
+1 from me

**Comment by fisherxu** [comment]
Seems fine to everyone :)  And does the `kubeedge-bot` will request review from the new added OWNER to the corresponding module? @sids-b 
And the bot will request review both the approver and reviewer or only the reviewer?

**Comment by sids-b** [comment]
@fisherxu , yess KubeEdge bot will add new OWNERS to the corresponding module. We have currently deployed prow as our bot so I think it should request review from approvers as well as reviewers.

**Comment by fisherxu** [comment]
@sids-b Ok, thanks. Let's see the result, If not, I think it's OK to add approver to reviewer.

**Pull request merged**
