### PR TITLE
solve unregular default config item-- dynamicController

### PR DESCRIPTION
**Pull request by GsssC**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Now, cmd `cloudcore --defaultconfig` will print the default config, but the dynamicController item is unregular and confusing.
Delete the tag`omitempty` will help.
- before
image

- after 
image

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Maybe need delete for all the enable fields?

**Comment by GsssC** [comment]
@fisherxu  agree

**Review by fisherxu — COMMENTED** [review]
/lgtm
/approve

**Comment by fisherxu** [comment]
> @fisherxu agree

Can do it in follow-up prs.

**Pull request merged**
