### PR TITLE
fix device mapper generate script error

### PR DESCRIPTION
**Pull request by Catherine-monk**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Device mapper generate script don't support macOS.
**Which issue(s) this PR fixes**:

Fixes #
none
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by wbc6080 — COMMENTED** [review]
Thanks for finding and fixing this problem
/lgtm

**Review by Shelley-BaoYue — COMMENTED** [review]
/lgtm

**Review by Shelley-BaoYue — COMMENTED** [review]
There are something wrong with ci and I have solved it and merge it into master. Please rebase the new master branch and push again. Thx : ）  https://github.com/kubeedge/kubeedge/pull/5517 also need rebase

**Comment by Catherine-monk** [comment]
> There are something wrong with ci and I have solved it and merge it into master. Please rebase the new master branch and push again. Thx : ） #5517 also need rebase

I have rebased the new master branch and push again.

**Comment by wbc6080** [comment]
I think it can be cherry-pick to release 1.15 and release 1.16

**Comment by WillardHu** [comment]
> I think it can be cherry-pick to release 1.15 and release 1.16

+1

**Pull request merged**
