### PR TITLE
add reviewer

### PR DESCRIPTION
**Pull request by zc2638**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

PRs reviewed / authored:
https://github.com/search?q=org%3Akubeedge+zc2638&type=commits

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
/lgtm
You'd better to list the prs and issues you created and involved(reviewed) :)

**Comment by fisherxu** [comment]
Leave to other reviewers :) 
/assign @kevin-wangzefeng @chendave

**Comment by chendave** [comment]
> You'd better to list the prs and issues you created and involved(reviewed) :)
+1

Anyway, I am ok to add @zc2638 as reviewer.

**Pull request merged**
