### PR TITLE
replace deprecated package io/ioutil with packages io and os

### PR DESCRIPTION
**Pull request by gy95**
Signed-off-by: gy95 <guoyao17@huawei.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
package `io/ioutil` is deprecated in Go1.16, and according to the official doc(https://golang.org/doc/go1.16#ioutil), we could use definitions in `io` and `os`.
So replace all codes using `io/ioutil` with package `os` and `io`
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by gy95** [comment]
go.mod has already specified the golang version to go1.16
https://github.com/kubeedge/kubeedge/blob/4ff2d99da342e3623141665696f23ca85e12d675/go.mod#L1-L6
this patch can be pushed in progress.

**Comment by gy95** [comment]
ping @fisherxu @zc2638 PTAL

**Review by fisherxu — COMMENTED** [review]
/approve

**Pull request merged**
